(define   pri_surf_ampl_no_statement               0)
(define   pri_surf_ampl_combatant                  1 )
(define   pri_surf_ampl_line                       2 )
(define   pri_surf_ampl_patrol_vessel              3 )
(define   pri_surf_ampl_amphibious                 4 )
(define   pri_surf_ampl_non_naval                  5 )
(define   pri_surf_ampl_non_combatant              6 )
(define   pri_surf_ampl_mine_warfare               7 )
(define   pri_surf_ampl_size                       8 )

(define   sec_surf_ampl_no_statement               0)
(define   sec_surf_ampl_carrier                     1 )
(define   sec_surf_ampl_destroyer                   2 )
(define   sec_surf_ampl_asw                         3 )
(define   sec_surf_ampl_asuw                        4 )
(define   sec_surf_ampl_underway_replenishment      5 )
(define   sec_surf_ampl_fleet_support               6 )
(define   sec_surf_ampl_hospital                    7 )
(define   sec_surf_ampl_mine_layer                  8 )
(define   sec_surf_ampl_mine_sweeper                9 )
(define   sec_surf_ampl_cruiser                    10 )
(define   sec_surf_ampl_frigate                    11 )
(define   sec_surf_ampl_landing_ship               12 )
(define   sec_surf_ampl_landing_craft              13 )
(define   sec_surf_ampl_assault_vessel             14 )
(define   sec_surf_ampl_intelligence               15 )
(define   sec_surf_ampl_merchant                   16 )
(define   sec_surf_ampl_fishing                    17 )
(define   sec_surf_ampl_leisure                    18 )
(define   sec_surf_ampl_acv_hydro                  19 )
(define   sec_surf_ampl_auxiliary                  20 )
(define   sec_surf_ampl_battleship                 21 )
(define   sec_surf_ampl_cargo                      22 )
(define   sec_surf_ampl_command                    23 )
(define   sec_surf_ampl_sec_surf_ampl_destroyer_aaw 24 )
(define   sec_surf_ampl_sec_surf_ampl_destroyer_asw 25 )
(define   sec_surf_ampl_landing_platform           26 )
(define   sec_surf_ampl_ocean_research             27 )
(define   sec_surf_ampl_surfaced_submarine         28 )
(define   sec_surf_ampl_tanker                     29 )
(define   sec_surf_ampl_size                       30 ) 

(define priampl 0)
(define secampl 0))
(foreach-tnum
 1
 (lambda (x)
   (set! priampl (nth 0 x))
   (set! secampl (nth 1 x)))
 (combi (num-list 0 8) (num-list 0 30)))

(case (testsc-get-testnum)              
  ((241)
   (testsc-debug "241")
   (set! priampl -1))) 
