(testsc-require system_types)
(case (testsc-get-testnum)
  ((18)
   (define testsc 1)
   (define te system_types-threat ))
  ((19)
   (define testsc 1)
   (define te system_types-non_threat ) )
  ((20)
   (define testsc 1)
   (define te system_types-unknown_threat_evaluation))
  ((21)
   (define testsc 1)
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 1)
    (list M86BEVSW  SECOND_FRAME_OFFSET 0)
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )))
  ((22)
   (define testsc 1)
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 1)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )
    (list M86BEVSW  SECOND_FRAME_OFFSET 1 )
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14 ))))
