(define  DB_ID_ASWPLAN_NOTACK_INFO                      5997)
(define  DB_ID_ASWPLAN_OAKTREE_DISPLAY                  6020)
(define  DB_ID_ASWPLAN_OAKTREE_EDIT                     6054)
(define  DB_ID_ASWPLAN_OAKTREE_INFO                     5998)
(define  DB_ID_ASWPLAN_PINEAPPLE_EDIT                   6055)
(define  DB_ID_ASWPLAN_PINEAPPLE_INFO                   5999)
(define  DB_ID_ASWPLAN_PLANNET_DISPLAY                  6021)
(define  DB_ID_ASWPLAN_PLANNET_EDIT                     6056)
(define  DB_ID_ASWPLAN_PLANNET_INFO                     6000)
(define  DB_ID_ASWPLAN_REDWOOD_EDIT                     6057)
(define  DB_ID_ASWPLAN_REDWOOD_INFO                     6001)
(define  DB_ID_ASWPLAN_SECTOR_SCREEN_EDIT               6058)
(define  DB_ID_ASWPLAN_SECTOR_SCREEN_INFO               6002)
(define  DB_ID_ASWPLAN_SKELETON_SCREEN_DISPLAY          6022)
(define  DB_ID_ASWPLAN_SKELETON_SCREEN_EDIT             6059)
(define  DB_ID_ASWPLAN_SKELETON_SCREEN_INFO             6003)
(define  DB_ID_ASWPLAN_SONOBUOY_DISPLAY                 6023)
(define  DB_ID_ASWPLAN_SONOBUOY_EDIT                    6060)
(define  DB_ID_ASWPLAN_SONOBUOY_INFO                    6004)
(define  DB_ID_ASWPLAN_SQUEEZE_EDIT                     6061)
(define  DB_ID_ASWPLAN_SQUEEZE_INFO                     6005)
(define  DB_ID_ASWPLAN_SUB_MOVE_AREA_DISPLAY            6024)
(define  DB_ID_ASWPLAN_SUB_MOVE_AREA_EDIT               6062)
(define  DB_ID_ASWPLAN_SUB_MOVE_AREA_INFO               6006)
(define  DB_ID_ASWPLAN_SUB_PATROL_AREA_DISPLAY          6025)
(define  DB_ID_ASWPLAN_SUB_PATROL_AREA_EDIT             6063)
(define  DB_ID_ASWPLAN_SUB_PATROL_AREA_INFO             6007)
(define  DB_ID_ASWPLAN_TDA_DISPLAY                      6026)
(define  DB_ID_ASWPLAN_TDA_EDIT                         6064)
(define  DB_ID_ASWPLAN_TDA_INFO                         6008)
(define  DB_ID_ASWPLAN_TDZ_DISPLAY                      6027)
(define  DB_ID_ASWPLAN_TDZ_EDIT                         6065)
(define  DB_ID_ASWPLAN_TDZ_INFO                         6009)
(define  DB_ID_CIWS_CDS_TRACK_DATA                      5816)
(define  DB_ID_CIWS_COMMAND_ACK                         5827)
(define  DB_ID_CIWS_DESIG_TRACK_INFO                    5828)
(define  DB_ID_CIWS_EMCON                               5817)
(define  DB_ID_CIWS_ENG_STATUS                          5807)
(define  DB_ID_CIWS_MODE_SET_INFO                       5808)
(define  DB_ID_CIWS_NO_ENG_SECTOR_DEF                   5819)
(define  DB_ID_CIWS_PROCESSED_TRACK_DATA                5809)
(define  DB_ID_CIWS_RADAR_SECTOR_CONTROL                5820)
(define  DB_ID_CIWS_SECTOR_DEF_REQ                      6082)
(define  DB_ID_CIWS_SPEED_THRESHOLD_SET                 5811)
(define  DB_ID_CIWS_SURFACE_CUE                         5821)
(define  DB_ID_CIWS_SURFACE_CUE_ACK                     5822)
(define  DB_ID_CIWS_SURFACE_CUE_REQ                     5823)
(define  DB_ID_CIWS_THREAT_TRACK_INFO                   5829)
(define  DB_ID_CIWS_WEAPON_DESIG                        5825)
(define  DB_ID_CIWS_WEAPON_DIRECTIVE_ACK                5812)
(define  DB_ID_CIWS_WEAPON_SECTOR_INFO                  5813)
(define  DB_ID_CIWS_WEAPON_STATE_CONTROL                5826)
(define  DB_ID_CIWS_WEAPON_SYS_STATUS                   5815)
(define  DB_ID_COMM_ALERT                               1555)
(define  DB_ID_COMM_ALERT_RESULT_ACK                    1610)
(define  DB_ID_COMM_FILE_UPDATE                         2585)
(define  DB_ID_COMM_HCI_NETWORK_TRACK_BALANCE           6173)
(define  DB_ID_COMM_INF_CTRL                            2117)
(define  DB_ID_COMM_INIT_TRACK                          1259)
(define  DB_ID_COMM_JOYSTICK_ALLOC                      1467)
(define  DB_ID_COMM_JOYSTICK_ALLOC_STATUS               1622)
(define  DB_ID_COMM_KILL_ASSESSMENT                     1436)
(define  DB_ID_COMM_LOGOFF                              2509)
(define  DB_ID_COMM_MODIFY_TRACK_INFO                   1261)
(define  DB_ID_COMM_NETWORK_TRACK_CANCEL                2527)
(define  DB_ID_COMM_NETWORK_TRACK_INFO                  2526)
(define  DB_ID_COMM_NETWORK_TRACK_SHAPE_INFO            6163)
(define  DB_ID_COMM_OPER_RSC_ALLOC_DEALLOC_REQ          1433)
(define  DB_ID_COMM_PRIMITIVE_TRACK_ADD_INFO_REQ        2396)
(define  DB_ID_COMM_PRIMITIVE_TRACK_CANCEL              2347)
(define  DB_ID_COMM_PRIMITIVE_TRACK_INFO                1785)
(define  DB_ID_COMM_RSC_ALLOC_DEALLOC_RESULT            1561)
(define  DB_ID_COMM_RSC_DEALLOC_NOTIFY                  1799)
(define  DB_ID_COMM_RSC_ENGAGEABLE_STATUS               1836)
(define  DB_ID_COMM_RSC_ENGAGEMENT_INFO                 1801)
(define  DB_ID_COMM_SIM_TRACK_CTRL                      2510)
(define  DB_ID_COMM_SIM_TRACK_CTRL_ACK                  2511)
(define  DB_ID_COMM_SK_ENGAGED_TRACK_STATUS             2421)
(define  DB_ID_COMM_SUBSYSTEM_STATUS_INFO               2119)
(define  DB_ID_COMM_SW_STATUS                           2285)
(define  DB_ID_COMM_SYSTEM_PERFORMANCE_INFO             5357)
(define  DB_ID_COMM_SYS_PARAMETER_REQ                   1283)
(define  DB_ID_COMM_TDL_CDO                             2593)
(define  DB_ID_COMM_TDL_CONFLICT                        1526)
(define  DB_ID_COMM_TDL_FILTER_INFO                     5699)
(define  DB_ID_COMM_TDL_FILTER_SETTING                  2369)
(define  DB_ID_COMM_TDL_INFO_REQ                        5499)
(define  DB_ID_COMM_TDL_JTDLS_COMMMAND_ORDER            5673)
(define  DB_ID_COMM_TDL_LINK11_COMMAND_ORDER            1516)
(define  DB_ID_COMM_TDL_MAX_RX_TRACK_COUNT              5697)
(define  DB_ID_COMM_TDL_MAX_RX_TRACK_COUNT_SETTING      2563)
(define  DB_ID_COMM_TDL_NTN                             1908)
(define  DB_ID_COMM_TDL_POINTER                         1883)
(define  DB_ID_COMM_TDL_TQ_UPDATE                       2601)
(define  DB_ID_COMM_TDL_WEAPON_ENGAGEMENT               2425)
(define  DB_ID_COMM_TDL_WEAPON_ENGAGEMENT_SETTING       2299)
(define  DB_ID_COMM_TIME_AND_DATE_REQ                   1285)
(define  DB_ID_COMM_TORPEDO_ALERT                       2293)
(define  DB_ID_COMM_TORPEDO_ALERT_INFO                  5838)
(define  DB_ID_COMM_TORPEDO_BITMAP_NOTIFICATION         2623)
(define  DB_ID_COMM_WEAPON_RESTRICTION_STATE_REQ        2418)
(define  DB_ID_COMM_WF_USER_OFFSET_VALUE_SET_REQ        1437)
(define  DB_ID_EOTS_AIM_POINT_CTRL                      5709)
(define  DB_ID_EOTS_AIM_POINT_STATUS                    5708)
(define  DB_ID_EOTS_CALIBRATION_CTRL                    1468)
(define  DB_ID_EOTS_CALIBRATION_STATUS                  1767)
(define  DB_ID_EOTS_DIRECTOR_STATUS                     1925)
(define  DB_ID_EOTS_EOTS_TRACK_INFO                     2297)
(define  DB_ID_EOTS_EQUIP_CTRL                          1469)
(define  DB_ID_EOTS_EQUIP_STATUS                        1766)
(define  DB_ID_EOTS_FORCED_MEMORY_TRACKING_CTRL         3022)
(define  DB_ID_EOTS_FRONT_DIRECTION_CTRL                2427)
(define  DB_ID_EOTS_FRONT_DIRECTION_STATUS              2428)
(define  DB_ID_EOTS_JOYSTICK_DATA                       1475)
(define  DB_ID_EOTS_LOCK_AND_LRF_STATUS                 2521)
(define  DB_ID_EOTS_LOCK_ON_CTRL                        2517)
(define  DB_ID_EOTS_LRF_FIRE_ON                         2518)
(define  DB_ID_EOTS_SECONDARY_TARGET                    2305)
(define  DB_ID_EOTS_SECTOR_SEARCH_CTRL                  1471)
(define  DB_ID_EOTS_SECTOR_SEARCH_STATUS                1764)
(define  DB_ID_EOTS_SLAVE_TRACKING_CTRL                 1476)
(define  DB_ID_EOTS_SLAVE_TRACKING_CTRL_STATUS          1765)
(define  DB_ID_EOTS_TRACKING_CTRL                       1473)
(define  DB_ID_EOTS_TRACKING_CTRL_STATUS                1768)
(define  DB_ID_EOTS_TRACKING_MAIN_CTRL                  2522)
(define  DB_ID_EOTS_TRACKING_MAIN_INFO                  2519)
(define  DB_ID_EOTS_TRACKING_SENSOR_CTRL                1474)
(define  DB_ID_EOTS_TRACKING_SENSOR_STATUS              1763)
(define  DB_ID_ES_PRIMTRK_ADD_INFO                      2398)
(define  DB_ID_ES_STATUS                                1788)
(define  DB_ID_ES_TRK_LIST                              1566)
(define  DB_ID_EW_BRN_LIST                              5848)
(define  DB_ID_EW_BRN_RPT_REQ                           5857)
(define  DB_ID_EW_BRN_SEC                               5856)
(define  DB_ID_EW_DEL_BRN_RPT_REQ                       5858)
(define  DB_ID_EW_EMITTER_LIST_INFO                     5867)
(define  DB_ID_EW_EMITTER_LIST_SET_REQ                  5869)
(define  DB_ID_EW_HK_STATUS                             5850)
(define  DB_ID_EW_INH_JAM_SECTOR                        5868)
(define  DB_ID_EW_INH_JAM_SECTOR_REQ                    5870)
(define  DB_ID_EW_JAMMING_CMD                           5851)
(define  DB_ID_EW_MAN_MODE_INFO                         5852)
(define  DB_ID_EW_PRIMTRK_ADD_INFO                      5853)
(define  DB_ID_EW_STATUS                                5854)
(define  DB_ID_EW_TRK_ADD_INFO_REQ                      5859)
(define  DB_ID_EW_TRK_LIST                              5849)
(define  DB_ID_EW_TRK_STATUS_SET_REQ                    5855)
(define  DB_ID_FFX_VIEW_OPERATION                       3231)
(define  DB_ID_GENPLAN_AAW_PLAN_EDIT                    5710)
(define  DB_ID_GENPLAN_AAW_PLAN_INFO                    1699)
(define  DB_ID_GENPLAN_ASUW_PLAN_EDIT                   5711)
(define  DB_ID_GENPLAN_ASUW_PLAN_INFO                   1694)
(define  DB_ID_GENPLAN_CHARGE_EDIT                      5924)
(define  DB_ID_GENPLAN_CHARGE_INFO                      5923)
(define  DB_ID_GENPLAN_COMPLAN_EDIT                     5713)
(define  DB_ID_GENPLAN_COMPLAN_INFO                     1695)
(define  DB_ID_GENPLAN_EMCONF_EDIT                      6108)
(define  DB_ID_GENPLAN_EMCONF_INFO                      6107)
(define  DB_ID_GENPLAN_EMCON_EDIT                       5714)
(define  DB_ID_GENPLAN_EMCON_INFO                       1700)
(define  DB_ID_GENPLAN_GENERAL_EDIT                     5715)
(define  DB_ID_GENPLAN_GENERAL_INFO                     2163)
(define  DB_ID_GENPLAN_NBC_DISPLAY                      1702)
(define  DB_ID_GENPLAN_NBC_DISPLAY_EDIT                 5716)
(define  DB_ID_GENPLAN_NBC_EDIT                         5717)
(define  DB_ID_GENPLAN_NBC_INFO                         1701)
(define  DB_ID_GENPLAN_NGS_PLAN_EDIT                    5712)
(define  DB_ID_GENPLAN_NGS_PLAN_INFO                    3257)
(define  DB_ID_GENPLAN__EMCON_INFO_WINDOW_POPUP         2413)
(define  DB_ID_GUN127_AIM_MODE_SET                      5763)
(define  DB_ID_GUN127_AMMUNTION_SELECT_ORDER            5764)
(define  DB_ID_GUN127_BM_AMMUNITION_INVENTORY           5720)
(define  DB_ID_GUN127_BM_BARREL_INDICATE_POSITION       5721)
(define  DB_ID_GUN127_BM_BARREL_INFORMATION             5722)
(define  DB_ID_GUN127_BM_CORRECTION_DATA_ACK            5724)
(define  DB_ID_GUN127_BM_DEFAULT_PARAMETER              5725)
(define  DB_ID_GUN127_BM_ENG_TIME_INFO                  5726)
(define  DB_ID_GUN127_BM_EOTS_LOCK_ON_STATUS_REQ        5727)
(define  DB_ID_GUN127_BM_FIRE_BT_CTRL                   5728)
(define  DB_ID_GUN127_BM_FIRE_CMD_ACK                   5729)
(define  DB_ID_GUN127_BM_FIRE_INFO                      5730)
(define  DB_ID_GUN127_BM_GUN_STATUS_INFO                5731)
(define  DB_ID_GUN127_BM_HIGH_MANEUVER_TGT_INFO         5732)
(define  DB_ID_GUN127_BM_INFO                           5733)
(define  DB_ID_GUN127_BM_MVR_STATUS                     5757)
(define  DB_ID_GUN127_BM_OSD_WEATHER_REQ                5758)
(define  DB_ID_GUN127_BM_PAC_DATA_ALL                   5759)
(define  DB_ID_GUN127_BM_RESET_TRACKING_ACK             5760)
(define  DB_ID_GUN127_CORRECTION_DATA                   5774)
(define  DB_ID_GUN127_CTRL_ORDER                        5765)
(define  DB_ID_GUN127_FUZE_SET                          5766)
(define  DB_ID_GUN127_HIGH_MANEUVER_TGT_SOLUTION        5767)
(define  DB_ID_GUN127_HIGH_SOLUTION                     5776)
(define  DB_ID_GUN127_MVR_SET                           5768)
(define  DB_ID_GUN127_PAC_DATA_SET                      5769)
(define  DB_ID_GUN127_PARA_SET                          5770)
(define  DB_ID_GUN127_PHP_DISPLAY                       5771)
(define  DB_ID_GUN127_STAR_SHELL_SET                    5772)
(define  DB_ID_GUN127_THROW_OFF_SET                     5773)
(define  DB_ID_GUN127_TRN_STATUS                        5785)
(define  DB_ID_GUN76_AIM_MODE_SET                       5569)
(define  DB_ID_GUN76_BM_BARREL_INDICATE_POSITION        5644)
(define  DB_ID_GUN76_BM_BARREL_INFORMATION              5540)
(define  DB_ID_GUN76_BM_CORRECTION_DATA_ACK             5539)
(define  DB_ID_GUN76_BM_DEFAULT_PARAMETER               5542)
(define  DB_ID_GUN76_BM_ENG_TIME_INFO                   5551)
(define  DB_ID_GUN76_BM_EOTS_LOCK_ON_STATUS_REQ         5550)
(define  DB_ID_GUN76_BM_FIRE_BT_CTRL                    5645)
(define  DB_ID_GUN76_BM_FIRE_CMD_ACK                    5646)
(define  DB_ID_GUN76_BM_FIRE_INFO                       5647)
(define  DB_ID_GUN76_BM_FIRE_STATUS                     5581)
(define  DB_ID_GUN76_BM_FIRING_DURATION_TIME_ACK        5648)
(define  DB_ID_GUN76_BM_GUN_DAILY_FIRE_COUNT            5649)
(define  DB_ID_GUN76_BM_GUN_STATUS_INFO                 5650)
(define  DB_ID_GUN76_BM_INFO_FIRE_SET_INFO              5651)
(define  DB_ID_GUN76_BM_INFO_MAIN                       5652)
(define  DB_ID_GUN76_BM_OSD_WEATHER_REQ                 5548)
(define  DB_ID_GUN76_BM_PAC_DATA_ALL                    5653)
(define  DB_ID_GUN76_BM_RESET_TRACKING_ACK              5552)
(define  DB_ID_GUN76_CORRECTION_DATA                    5567)
(define  DB_ID_GUN76_CTRL_ORDER                         5565)
(define  DB_ID_GUN76_DAILY_FIRE_COUNT                   5571)
(define  DB_ID_GUN76_DEFAULT_PARA_REQ                   5572)
(define  DB_ID_GUN76_FIRING_DURATION_TIME               5641)
(define  DB_ID_GUN76_NGS_CORRECTION_DATA                5578)
(define  DB_ID_GUN76_PAC_DATA_SET                       5558)
(define  DB_ID_GUN76_PARA_SET                           5563)
(define  DB_ID_GUN76_PHP_DISPLAY                        5642)
(define  DB_ID_GUN76_THROW_OFF_SET                      5643)
(define  DB_ID_GUN76_TRN_STATUS                         5659)
(define  DB_ID_GUN76_TRN_STATUS_REQ                     5660)
(define  DB_ID_GUN_BM_AMMUNITION_INVENTORY              2540)
(define  DB_ID_GUN_BM_MVR_STATUS                        3030)
(define  DB_ID_HMS_BEARING_LIST                         5903)
(define  DB_ID_HMS_ENERGYSPECTRUM                       5894)
(define  DB_ID_HMS_HMSINFO                              5895)
(define  DB_ID_HMS_MAX_SENSE_RANGE                      5896)
(define  DB_ID_HMS_MAX_SENSE_RANGE_INFO                 5904)
(define  DB_ID_HMS_PRIMTRK_ADD_INFO                     5897)
(define  DB_ID_HMS_RADAR_TRACK                          5901)
(define  DB_ID_HMS_RANGE                                5939)
(define  DB_ID_HMS_SONAR_ORDER                          5902)
(define  DB_ID_HMS_SONAR_ORDER_ACK                      5898)
(define  DB_ID_HMS_TORPEDO_ALERT_LIST                   5905)
(define  DB_ID_HMS_TORPEDO_DETECT_DISP                  5899)
(define  DB_ID_HMS_TORPEDO_DISCERN_DISP                 5900)
(define  DB_ID_IFF_BDS_DISP_DATA                        5394)
(define  DB_ID_IFF_BIT_INFO                             1967)
(define  DB_ID_IFF_CODE_SET                             1477)
(define  DB_ID_IFF_CODE_STATUS                          1623)
(define  DB_ID_IFF_EQUIP_CTRL                           3088)
(define  DB_ID_IFF_EQUIP_CTRL_ACK                       3270)
(define  DB_ID_IFF_EQUIP_STATUS                         3089)
(define  DB_ID_IFF_INTERROGATE_STATUS                   1966)
(define  DB_ID_IFF_MODE1_STATUS                         1625)
(define  DB_ID_IFF_MODE2_STATUS                         1626)
(define  DB_ID_IFF_MODE3A_STATUS                        1627)
(define  DB_ID_IFF_MODE3A_TIME                          2122)
(define  DB_ID_IFF_MODE_DATA                            1624)
(define  DB_ID_IFF_MODE_INFO_REQ                        2500)
(define  DB_ID_IFF_PRIMTRK_ADD_INFO                     5344)
(define  DB_ID_IFF_RADAR_SILENCE_CTRL_ACK               2214)
(define  DB_ID_IISS_GFE_MESSAGE                         5916)
(define  DB_ID_INFRA_IPN_WC_INIT_CTRL                   5582)
(define  DB_ID_IPNTRN_GUN_AMMOLIST                      2608)
(define  DB_ID_IPNTRN_IFF_STATUS                        5657)
(define  DB_ID_IRST_MODE_CTRL                           6215)
(define  DB_ID_IRST_PANORAMIC_CTRL                      6216)
(define  DB_ID_IRST_PANORAMIC_REQ                       6225)
(define  DB_ID_IRST_PANORAMIC_STATUS                    6220)
(define  DB_ID_IRST_POWER_CTRL                          6229)
(define  DB_ID_IRST_POWER_STATUS                        6232)
(define  DB_ID_IRST_PRIMTRK_ADD_INFO                    6234)
(define  DB_ID_IRST_SEARCH_SECTOR_CTRL                  6219)
(define  DB_ID_IRST_SEARCH_SECTOR_STATUS                6223)
(define  DB_ID_IRST_SECTOR_SURVEIL_CTRL                 6217)
(define  DB_ID_IRST_SECTOR_SURVEIL_REQ                  6224)
(define  DB_ID_IRST_SECTOR_SURVEIL_STATUS               6221)
(define  DB_ID_IRST_SENSOR_CONFIG_CTRL                  6230)
(define  DB_ID_IRST_SENSOR_CONFIG_STATUS                6231)
(define  DB_ID_IRST_STATUS                              5740)
(define  DB_ID_IRST_TRK_LIST                            5937)
(define  DB_ID_ISDL_AIRCRAFT_SHIP_CONTROL               1874)
(define  DB_ID_ISDL_AIRCRAFT_SHIP_CONTROL_SETTING       2115)
(define  DB_ID_ISDL_ASSOCIATION                         1875)
(define  DB_ID_ISDL_COMMAND                             1877)
(define  DB_ID_ISDL_COMMAND_LIST                        2489)
(define  DB_ID_ISDL_COMMAND_ORDER_ACK                   2512)
(define  DB_ID_ISDL_CORRELATION_STATUS                  1863)
(define  DB_ID_ISDL_ENGAGEMENT_STATUS                   1878)
(define  DB_ID_ISDL_GEN_CTRL_ACK                        1880)
(define  DB_ID_ISDL_GEN_CTRL_SETTING                    1536)
(define  DB_ID_ISDL_INFORMATION_DIFFERENCE_REPORT       1867)
(define  DB_ID_ISDL_MAIN_WND_INFO                       2485)
(define  DB_ID_ISDL_NETWORK_TRACK_ADD_INFO              2582)
(define  DB_ID_ISDL_NTN                                 1868)
(define  DB_ID_ISDL_OPNOTE_INFO                         5700)
(define  DB_ID_ISDL_OPNOTE_SEND                         1617)
(define  DB_ID_ISDL_PU_TABLE_CONFIG                     2577)
(define  DB_ID_ISDL_PU_TABLE_CONFIG_SETTING             2584)
(define  DB_ID_ISDL_REMOTE_TRACK_LIST                   2492)
(define  DB_ID_ISDL_REMOTE_TRACK_SEARCH_SETTING         2455)
(define  DB_ID_ISDL_TDL_OPNOTE_INFO                     1881)
(define  DB_ID_ISDL_TDL_OPNOTE_SEND                     5701)
(define  DB_ID_ISDL_TDL_RESILIENCE                      6127)
(define  DB_ID_ISDL_TRACK_ALERT                         1872)
(define  DB_ID_ISDL_TRACK_HOOKING_REQ                   2587)
(define  DB_ID_ISDL_WEAPON_STATUS                       1884)
(define  DB_ID_JTDLS_ADMISSION_RESPONSE                 5622)
(define  DB_ID_JTDLS_ALERT_LIST                         5635)
(define  DB_ID_JTDLS_COMMAND_LINE                       5666)
(define  DB_ID_JTDLS_COMMAND_LIST                       5624)
(define  DB_ID_JTDLS_CONTROL_UNIT_CHANGE                6179)
(define  DB_ID_JTDLS_CORREATION                         5625)
(define  DB_ID_JTDLS_ENGAGEMENT_STATUS_LIST             5626)
(define  DB_ID_JTDLS_FILTER                             6180)
(define  DB_ID_JTDLS_FREETEXT                           6185)
(define  DB_ID_JTDLS_FREETEXT_LIST                      5639)
(define  DB_ID_JTDLS_HANDOVER                           6177)
(define  DB_ID_JTDLS_IDENTIFIER_LIST                    6184)
(define  DB_ID_JTDLS_MISSION_ASSIGNMENT                 6174)
(define  DB_ID_JTDLS_NETWORK_TRACK_ADD_INFO             5623)
(define  DB_ID_JTDLS_NETWORK_TRACK_ADD_INFO_FOR_MD      5667)
(define  DB_ID_JTDLS_NETWORK_TRACK_ASSOCIATION_LIST     5627)
(define  DB_ID_JTDLS_NETWORK_TRACK_PAIRING_LIST         5628)
(define  DB_ID_JTDLS_SHAPE_LIST                         5640)
(define  DB_ID_JTDLS_TARGET_SORTING_LIST                5654)
(define  DB_ID_JTDLS_THREAT_WARNING_LIST                5629)
(define  DB_ID_JTDLS_TRACK_SEND_RESULT                  5655)
(define  DB_ID_JTDLS_VECTOR                             6176)
(define  DB_ID_KEYBOARD_SHORTCUTS                       5398)
(define  DB_ID_KNCCS_KNCCS_TRACK_LIST                   1860)
(define  DB_ID_KNCCS_STATUS_INFO                        1861)
(define  DB_ID_KSAAM_BREAK_ENG_COMPLETED                5799)
(define  DB_ID_KSAAM_DESIGNATION                        5798)
(define  DB_ID_KSAAM_DOCTRINE_REQ                       6080)
(define  DB_ID_KSAAM_DOCTRINE_SETTINGS                  5800)
(define  DB_ID_KSAAM_DOCTRINE_SETTINGS_REQ              5824)
(define  DB_ID_KSAAM_EMERGENCY_DESTRUCTION              6081)
(define  DB_ID_KSAAM_EMERGENCY_DESTRUCTION_REQ          5814)
(define  DB_ID_KSAAM_FIRE_BT_CTRL                       5805)
(define  DB_ID_KSAAM_JET_VANES_REPORT                   5806)
(define  DB_ID_KSAAM_LAUNCH_STATUS                      5801)
(define  DB_ID_KSAAM_LOCAL_TGT_CMD                      6079)
(define  DB_ID_KSAAM_LOCAL_TGT_STATUS                   6077)
(define  DB_ID_KSAAM_MISSILE_TRAJECTORY_DATA            5810)
(define  DB_ID_KSAAM_REPEATBACK                         5802)
(define  DB_ID_KSAAM_STATUS                             5804)
(define  DB_ID_KSAAM_STATUS_REQ                         6078)
(define  DB_ID_KSSM_ENGAGEMENT_ORDER                    5743)
(define  DB_ID_KSSM_ENGAGEMENT_ORDER_REQ                5744)
(define  DB_ID_KSSM_ENGAGEMENT_PLAN                     5751)
(define  DB_ID_KSSM_ENGAGEMENT_STATUS                   5748)
(define  DB_ID_KSSM_EQUIPMENT_STATUS                    5749)
(define  DB_ID_KSSM_INTERFACE_CONTROL                   5753)
(define  DB_ID_KSSM_PLAN_APPROVAL                       5754)
(define  DB_ID_KSSM_PLAN_PROFILE                        5752)
(define  DB_ID_KSSM_STATUS_INFO_REQ                     5755)
(define  DB_ID_KSSM_TDA_DISPLAY                         5756)
(define  DB_ID_KSSM_TGT_INFO                            5745)
(define  DB_ID_KSSM_TGT_INFO_REQ                        5746)
(define  DB_ID_KSSM_TRACK_DATA_MSG                      5747)
(define  DB_ID_KSSM_TRACK_REQUEST                       5750)
(define  DB_ID_KTSLM_ENGAGEMENT_ORDER                   5761)
(define  DB_ID_KTSLM_ENGAGEMENT_ORDER_REQ               5777)
(define  DB_ID_KTSLM_ENGAGEMENT_PLAN                    5790)
(define  DB_ID_KTSLM_ENGAGEMENT_STATUS                  5778)
(define  DB_ID_KTSLM_EQUIPMENT_STATUS                   5779)
(define  DB_ID_KTSLM_INTERFACE_CONTROL                  5792)
(define  DB_ID_KTSLM_PLAN_APPROVAL                      5793)
(define  DB_ID_KTSLM_PLAN_PROFILE                       5791)
(define  DB_ID_KTSLM_STATUS_INFO_REQ                    5794)
(define  DB_ID_KTSLM_TDA_DISPLAY                        5795)
(define  DB_ID_KTSLM_TGT_INFO                           5762)
(define  DB_ID_KTSLM_TGT_INFO_REQ                       5780)
(define  DB_ID_KTSLM_TRACK_DATA_MSG                     5775)
(define  DB_ID_KTSLM_TRACK_REQUEST                      5781)
(define  DB_ID_KVLA_ENG_INFO_LIST                       5871)
(define  DB_ID_KVLA_ENG_PLAN_APPROVAL_CMD               5861)
(define  DB_ID_KVLA_ENG_PLAN_DISPLAY_INFO               6194)
(define  DB_ID_KVLA_ENG_PLAN_DISPLAY_ONFOFF             6195)
(define  DB_ID_KVLA_ENG_STATUS                          5862)
(define  DB_ID_KVLA_FIRE_PERMIT_CMD                     5863)
(define  DB_ID_KVLA_INHIBIT_REQ                         6211)
(define  DB_ID_KVLA_KVLS_STATUS                         6204)
(define  DB_ID_KVLA_SECTOR_TRACK_INFO                   6190)
(define  DB_ID_KVLA_STATUS_INFO                         5864)
(define  DB_ID_KVLA_TARGET_INDICATION                   5860)
(define  DB_ID_KVLA_TI_SET_REQ                          5865)
(define  DB_ID_KVLA_TORPEDO_SET_REQ                     5866)
(define  DB_ID_LINK11_ADMISSION                         6097)
(define  DB_ID_LINK11_ADMISSION_SETTING                 6091)
(define  DB_ID_LINK11_AIRCRAFT_CONTROL                  6098)
(define  DB_ID_LINK11_AIRCRAFT_CONTROL_ORDER_SETTING    6092)
(define  DB_ID_LINK11_AIRCRAFT_MISSION_STATUS           6103)
(define  DB_ID_LINK11_AIRCRAFT_MISSION_STATUS_SETTING   6093)
(define  DB_ID_LINK11_COMMAND_LINE                      6111)
(define  DB_ID_LINK11_COMMAND_ORDER                     6099)
(define  DB_ID_LINK11_COMMAND_ORDER_SETTING             6112)
(define  DB_ID_LINK11_CONFLICT                          6100)
(define  DB_ID_LINK11_DP_INPUT                          6226)
(define  DB_ID_LINK11_DTS_CONTROL_DATA                  6101)
(define  DB_ID_LINK11_DTS_CONTROL_DATA_SETTING          6094)
(define  DB_ID_LINK11_DTS_NDDSINTF                      6228)
(define  DB_ID_LINK11_IP_INPUT                          6227)
(define  DB_ID_LINK11_LOOPTEST_SETTING                  6095)
(define  DB_ID_LINK11_NETWORK_TRACK_ADD_INFO            6110)
(define  DB_ID_LINK11_OPNOTE_SETTING                    6096)
(define  DB_ID_LINK11_TDL_OPNOTE_INFO                   6104)
(define  DB_ID_LINK11_TEST_RESULT                       6102)
(define  DB_ID_LINKK_FREETEXT_LIST                      5636)
(define  DB_ID_LINK_COMMAND_RESPONSE                    6197)
(define  DB_ID_LYNXESM_HELI_INFO                        5737)
(define  DB_ID_LYNXESM_PRIMTRK_ADD_INFO                 5736)
(define  DB_ID_LYNXESM_STATUS                           5738)
(define  DB_ID_LYNXESM_TRK_INFO_REQ                     5739)
(define  DB_ID_LYNXESM_TRK_LIST                         5735)
(define  DB_ID_MASS_CLOUD_DATA                          5607)
(define  DB_ID_MASS_CRITERIA                            5614)
(define  DB_ID_MASS_CRITERIA_REQ                        5682)
(define  DB_ID_MASS_ENG_INFO_LIST                       2536)
(define  DB_ID_MASS_ENG_REPORT                          5608)
(define  DB_ID_MASS_ER_MSG                              5936)
(define  DB_ID_MASS_HK_STATUS                           5615)
(define  DB_ID_MASS_RESOURCE_STATUS                     5609)
(define  DB_ID_MASS_STATUS                              5610)
(define  DB_ID_MASS_TD_MSG                              5611)
(define  DB_ID_MASS_TI_LIST                             5612)
(define  DB_ID_MASS_TI_SET_REQ                          5618)
(define  DB_ID_MASS_TQ_LIST                             5613)
(define  DB_ID_MCS_GUN_FIRE_CMD                         1269)
(define  DB_ID_MCS_KSAAM_FIRE_CMD                       1271)
(define  DB_ID_MCS_RCWS_FIRE_CMD                        5663)
(define  DB_ID_MCS_ROCKET_FIRE_CMD                      5664)
(define  DB_ID_MCS_SIMROCKET_FIRE_CMD                   6246)
(define  DB_ID_MCS_SLTS_FIRE_CMD                        1270)
(define  DB_ID_MCS_TACM_FIRE_CMD                        1272)
(define  DB_ID_MD_COORD_CHANGE                          6209)
(define  DB_ID_MD_HIGH_MANEUVER_PHP_INFO                2607)
(define  DB_ID_MD_TDL_AIRCRAFT_CONTROL_INFO             2461)
(define  DB_ID_MD_TDL_POINTER                           1537)
(define  DB_ID_MD_TDL_TRAINING_TRACK_CONFIRM            2499)
(define  DB_ID_MD_TM_LINK_SEND_CANCEL                   1265)
(define  DB_ID_MD_TM_MANUAL_CANCEL                      2590)
(define  DB_ID_MD_TM_MANUAL_FUSION                      1262)
(define  DB_ID_MD_TM_SURF_TRACKING_INITIATION           2123)
(define  DB_ID_MD_TM_SURF_TRACKING_SELECTION            5922)
(define  DB_ID_MD_WF_ENG_CH_LIST_REQ                    1435)
(define  DB_ID_MFC_JTDLS_ADMISSION_SETTTING             5621)
(define  DB_ID_MFC_JTDLS_ALERT_RES                      6181)
(define  DB_ID_MFC_JTDLS_ASS_PAI                        6168)
(define  DB_ID_MFC_JTDLS_COMMAND                        6167)
(define  DB_ID_MFC_JTDLS_CONTROL_UNIT_CHANGE            6165)
(define  DB_ID_MFC_JTDLS_CORRELATION_REQ                5632)
(define  DB_ID_MFC_JTDLS_ENGAGEMENT                     6169)
(define  DB_ID_MFC_JTDLS_FILTER_SETTING                 5637)
(define  DB_ID_MFC_JTDLS_FREETEXT_TX                    5661)
(define  DB_ID_MFC_JTDLS_INFO_REQ                       5633)
(define  DB_ID_MFC_JTDLS_MISSION_ASSIGNMENT             6175)
(define  DB_ID_MFC_JTDLS_NTDB_CLEAR                     5630)
(define  DB_ID_MFC_JTDLS_SET_OWNSHIP_INFO               5634)
(define  DB_ID_MFC_JTDLS_SHAPE                          6171)
(define  DB_ID_MFC_JTDLS_TARGET_SORTING                 6166)
(define  DB_ID_MFC_JTDLS_THREAT_WARNING                 6172)
(define  DB_ID_MFC_JTDLS_TRACK_ADD_INFO                 6170)
(define  DB_ID_MFC_JTDLS_VECTOR                         6164)
(define  DB_ID_MFC_JTDL_HANDOVER                        6178)
(define  DB_ID_MFC_SIMKSAAM_FIRE_CMD                    6212)
(define  DB_ID_MFC_TM_MANUAL_TRACK_WIPE                 2022)
(define  DB_ID_MFC_TRN_IFF_STATUS_REQ                   2416)
(define  DB_ID_NAV_ANCH_RUN                             1258)
(define  DB_ID_NAV_ANCH_RUN_ACK                         1585)
(define  DB_ID_NAV_ARRIVE_RUN                           1254)
(define  DB_ID_NAV_ARRIVE_RUN_ACK                       1581)
(define  DB_ID_NAV_COASTSAIL_INFO                       1252)
(define  DB_ID_NAV_COASTSAIL_INFO_ACK                   1579)
(define  DB_ID_NAV_COLL_INFO                            1251)
(define  DB_ID_NAV_COLL_INFO_ACK                        1577)
(define  DB_ID_NAV_COLL_TRACK_INFO                      1578)
(define  DB_ID_NAV_CPA_INFO                             2550)
(define  DB_ID_NAV_CPA_REQ                              2551)
(define  DB_ID_NAV_DISPLAY_ANCH                         2653)
(define  DB_ID_NAV_DISPLAY_ANCH_COMPLETE                5681)
(define  DB_ID_NAV_DISPLAY_ARRIVE                       2654)
(define  DB_ID_NAV_DISPLAY_COLL                         5680)
(define  DB_ID_NAV_DISPLAY_CPA                          2655)
(define  DB_ID_NAV_DISPLAY_DIST                         2656)
(define  DB_ID_NAV_DISPLAY_LOWSAIL                      3240)
(define  DB_ID_NAV_DISPLAY_SAIL                         2657)
(define  DB_ID_NAV_DISPLAY_SCOUT                        2658)
(define  DB_ID_NAV_DISPLAY_STAT                         2659)
(define  DB_ID_NAV_DISPLAY_ZIG                          2660)
(define  DB_ID_NAV_DIST_RUN                             1255)
(define  DB_ID_NAV_DIST_RUN_ACK                         1582)
(define  DB_ID_NAV_KEEP_SAIL_RUN                        5676)
(define  DB_ID_NAV_KEEP_SAIL_RUN_ACK                    5679)
(define  DB_ID_NAV_RESCUE_RUN                           5677)
(define  DB_ID_NAV_RESCUE_RUN_ACK                       5678)
(define  DB_ID_NAV_SAIL_PLAN                            1249)
(define  DB_ID_NAV_SAIL_PLAN_ACK                        1575)
(define  DB_ID_NAV_SAIL_RUN                             1250)
(define  DB_ID_NAV_SAIL_RUN_ACK                         1576)
(define  DB_ID_NAV_SCOUT_RUN                            2120)
(define  DB_ID_NAV_SCOUT_RUN_ACK                        2121)
(define  DB_ID_NAV_STAT_RUN                             1253)
(define  DB_ID_NAV_STAT_RUN_ACK                         1580)
(define  DB_ID_NAV_ZIG_PLAN                             1256)
(define  DB_ID_NAV_ZIG_PLAN_ACK                         1583)
(define  DB_ID_NAV_ZIG_RUN                              1257)
(define  DB_ID_NAV_ZIG_RUN_ACK                          1584)
(define  DB_ID_NMM_AREA                                 5409)
(define  DB_ID_NMM_MGR                                  5410)
(define  DB_ID_NRS_TRACK_INFO                           5335)
(define  DB_ID_OBSERVER_POS_DISPLAY                     6109)
(define  DB_ID_OSD_ALTITUDE_WEATHER_INFO                1637)
(define  DB_ID_OSD_AUTOHISTORY_DATA_RESIL               5694)
(define  DB_ID_OSD_AUTOHISTORY_LIST_RESIL               5696)
(define  DB_ID_OSD_COMMON_DATA_RESIL                    5688)
(define  DB_ID_OSD_ENV_CTRL                             1485)
(define  DB_ID_OSD_ENV_INFO                             1636)
(define  DB_ID_OSD_HISTORY_CTRL                         1486)
(define  DB_ID_OSD_HISTORY_DATA_RESIL                   5693)
(define  DB_ID_OSD_HISTORY_INFO                         1633)
(define  DB_ID_OSD_HISTORY_LIST_INFO_RESIL              5692)
(define  DB_ID_OSD_HISTORY_LIST_RESIL                   5695)
(define  DB_ID_OSD_INFO                                 1634)
(define  DB_ID_OSD_NECODE_CHANGE                        5323)
(define  DB_ID_OSD_NECODE_CTRL                          2315)
(define  DB_ID_OSD_NECODE_INFO                          2316)
(define  DB_ID_OSD_NECODE_RESIL                         5691)
(define  DB_ID_OSD_OSD_CTRL                             1488)
(define  DB_ID_OSD_SAIL_DISPPLAY                        2588)
(define  DB_ID_OSD_STAB                                 2548)
(define  DB_ID_OSD_STAB_OSD                             2381)
(define  DB_ID_OSD_USE_FLAG_RESIL                       5690)
(define  DB_ID_OSD_WEATHER_CTRL                         1489)
(define  DB_ID_OSD_WEATHER_INFO_RESIL                   5689)
(define  DB_ID_RCWS_BREAK_ENG                           6203)
(define  DB_ID_RCWS_BREAK_ENG_COMPLETED                 6189)
(define  DB_ID_RCWS_ENG_CONTROL                         6192)
(define  DB_ID_RCWS_ENG_STATUS                          5671)
(define  DB_ID_RCWS_FIRE_BT_CTRL                        5675)
(define  DB_ID_RCWS_FIRING_CONTROL                      6191)
(define  DB_ID_RCWS_SECTOR_TRACK_INFO                   6193)
(define  DB_ID_RCWS_SECTOR_TRACK_REQ                    6202)
(define  DB_ID_RCWS_STATUS                              5670)
(define  DB_ID_RCWS_TD_LIST                             5672)
(define  DB_ID_RCWS_TD_MSG                              5669)
(define  DB_ID_RES_NAV_DIST                             5706)
(define  DB_ID_RES_NAV_PLAN                             5702)
(define  DB_ID_RES_NAV_SCOUT                            5704)
(define  DB_ID_RES_NAV_STAT                             5707)
(define  DB_ID_RES_NAV_ZIG_RUN                          5705)
(define  DB_ID_RM_ALL_TARGET_POSITION_INFO              5580)
(define  DB_ID_ROCKET_BREAK_ENG_COMPLETED               6129)
(define  DB_ID_ROCKET_DESIGNATION                       6116)
(define  DB_ID_ROCKET_DOCTRINE_SETTINGS                 6113)
(define  DB_ID_ROCKET_DOCTRINE_SETTINGS_REQ             6114)
(define  DB_ID_ROCKET_EMERGENCY_DESTRUCTION_REQ         6131)
(define  DB_ID_ROCKET_FIRE_BT_CTRL                      5674)
(define  DB_ID_ROCKET_REPEATBACK                        6128)
(define  DB_ID_ROCKET_STATUS                            6115)
(define  DB_ID_ROCKET_TRAJECTORY_DATA                   6130)
(define  DB_ID_RVDUTVD_SELECT_TV_VIDEO_ACK              2407)
(define  DB_ID_RVDUTVD_STATUS                           2534)
(define  DB_ID_RVDUTVD_TV_CONNECTION_STATUS             2025)
(define  DB_ID_RVP_FILE_DELETE_ACK                      2394)
(define  DB_ID_RVP_RNR_CMD_ACK                          2391)
(define  DB_ID_RVP_RVD_STATUS                           5719)
(define  DB_ID_RVP_RVR_STATUS                           2533)
(define  DB_ID_RVR_FILE_LIST_ACK                        2393)
(define  DB_ID_SD_HCISET_SAVE                           6118)
(define  DB_ID_SD_LOGOFF                                6210)
(define  DB_ID_SIMCIWS_STATUS                           5830)
(define  DB_ID_SIMCIWS_STATUS_REQ                       5831)
(define  DB_ID_SIMEOTS_STATUS                           2126)
(define  DB_ID_SIMEOTS_STATUS_REQ                       2132)
(define  DB_ID_SIMES_STATUS                             1791)
(define  DB_ID_SIMES_STATUS_REQ                         1459)
(define  DB_ID_SIMEW_STATUS                             6083)
(define  DB_ID_SIMEW_STATUS_REQ                         6084)
(define  DB_ID_SIMGUN127_TRN_RELOAD_AMMO                6073)
(define  DB_ID_SIMGUN127_TRN_STATUS                     6074)
(define  DB_ID_SIMGUN127_TRN_STATUS_REQ                 6106)
(define  DB_ID_SIMHMS_STATUS                            6085)
(define  DB_ID_SIMHMS_STATUS_REQ                        6087)
(define  DB_ID_SIMIRST_SECTOR_SURVEIL_CTRL              6241)
(define  DB_ID_SIMIRST_SECTOR_SURVEIL_REQ               6236)
(define  DB_ID_SIMIRST_SECTOR_SURVEIL_STATUS            6237)
(define  DB_ID_SIMIRST_STATUS                           5741)
(define  DB_ID_SIMIRST_STATUS_REQ                       5742)
(define  DB_ID_SIMIRST_TRN_SECTOR_SURVEIL_REQ           6235)
(define  DB_ID_SIMKSSM_STATUS                           6090)
(define  DB_ID_SIMKSSM_STATUS_REQ                       6089)
(define  DB_ID_SIMKTSLM_STATUS                          6133)
(define  DB_ID_SIMKTSLM_STATUS_REQ                      6134)
(define  DB_ID_SIMKTSLM_WAYPOINT_INFO                   6214)
(define  DB_ID_SIMKVLA_FIRE_PLAN_SET_INFO               6201)
(define  DB_ID_SIMKVLA_FIRE_PLAN_SET_INFO_ACK           6213)
(define  DB_ID_SIMKVLA_STATUS_INFO_REQ                  6198)
(define  DB_ID_SIMMASS_STATUS                           5619)
(define  DB_ID_SIMMASS_STATUS_REQ                       5620)
(define  DB_ID_SIMNRS_STATUS                            6076)
(define  DB_ID_SIMNRS_STATUS_REQ                        6105)
(define  DB_ID_SIMRCWS_FIRE_BT_INPUT                    6245)
(define  DB_ID_SIMRCWS_STATUS                           5687)
(define  DB_ID_SIMRCWS_STATUS_REQ                       5683)
(define  DB_ID_SIMROCKET_STATUS                         6243)
(define  DB_ID_SIMROCKET_STATUS_REQ                     6199)
(define  DB_ID_SIMROCKET_SWITCH_CMD                     6242)
(define  DB_ID_SIMROCKET_TD_LIST                        6244)
(define  DB_ID_SIMSLTS_STATUS                           1848)
(define  DB_ID_SIMSLTS_STATUS_REQ                       5832)
(define  DB_ID_SIMSRS_STATUS                            2124)
(define  DB_ID_SIMSRS_STATUS_REQ                        2130)
(define  DB_ID_SIMTASS_STATUS                           1795)
(define  DB_ID_SIMTASS_STATUS_REQ                       1460)
(define  DB_ID_SKP_COMMAND                              2591)
(define  DB_ID_SLTS_DOGBOX_DISPLAY_INFO                 5803)
(define  DB_ID_SLTS_ENG_INFO                            5796)
(define  DB_ID_SLTS_FIRE_BT_CTRL                        5782)
(define  DB_ID_SLTS_FIRE_DATA_SET_REQ                   5788)
(define  DB_ID_SLTS_LAUNCHER_TUBE_DATA_SET_REQ          5787)
(define  DB_ID_SLTS_STATUS_INFO                         5783)
(define  DB_ID_SLTS_STATUS_SET_REQ                      5786)
(define  DB_ID_SLTS_TORPEDO_INFO_SET_REQ                5789)
(define  DB_ID_SLTS_WF_DATA                             5784)
(define  DB_ID_SLTS_WF_LIST                             5797)
(define  DB_ID_SM_ALERT_RESULT                          1389)
(define  DB_ID_SM_ALLOC_STATUS_COMMAND                  6206)
(define  DB_ID_SM_ALLOC_STATUS_CONTROL                  6205)
(define  DB_ID_SM_ALLOC_STATUS_REPORT                   5684)
(define  DB_ID_SM_ALL_SYS_STATUS_INFO                   1591)
(define  DB_ID_SM_ASSIGNMENT_INFO                       2496)
(define  DB_ID_SM_AUTH_CHANGE_REQ                       2529)
(define  DB_ID_SM_DISP_ALERT                            6247)
(define  DB_ID_SM_HB_INFO                               5665)
(define  DB_ID_SM_HCISET_INFO                           6117)
(define  DB_ID_SM_INCORRECT_MSG                         1588)
(define  DB_ID_SM_INF_HISTORY_INFO                      2161)
(define  DB_ID_SM_INF_HISTORY_INFO_REQ                  6070)
(define  DB_ID_SM_LOGOUT_CMD                            2531)
(define  DB_ID_SM_LOG_CONTROL_CMD                       2541)
(define  DB_ID_SM_MODE_ALLOCATION_INFO                  5418)
(define  DB_ID_SM_MODE_CHANGE_CMD                       2139)
(define  DB_ID_SM_MODE_CHANGE_REQ                       2138)
(define  DB_ID_SM_MODE_CHANGE_STATUS                    5328)
(define  DB_ID_SM_MODE_ENV_SET_CMD                      6182)
(define  DB_ID_SM_MODE_FG_NODE_REL_INFO                 5419)
(define  DB_ID_SM_MODE_STATUS_INFO                      1586)
(define  DB_ID_SM_NET_POLL_TIME_AND_THRESHOLD_EDIT      1305)
(define  DB_ID_SM_NMS_INFO_REQ                          1287)
(define  DB_ID_SM_NMS_NET_PERFORM                       1710)
(define  DB_ID_SM_NMS_NET_POLL_TIME_AND_THRESHOLD       1714)
(define  DB_ID_SM_NMS_PORT_STATISTIC                    1713)
(define  DB_ID_SM_NMS_PORT_STATUS                       1712)
(define  DB_ID_SM_NMS_PORT_USAGE                        1711)
(define  DB_ID_SM_NMS_RESILIENCE                        5464)
(define  DB_ID_SM_NMS_SYSTEM_STATUS_INFO                1706)
(define  DB_ID_SM_NMS_SYS_INFO                          1707)
(define  DB_ID_SM_NMS_SYS_PERFORM                       1708)
(define  DB_ID_SM_NMS_SYS_POLL_TIME_AND_THRESHOLD       1715)
(define  DB_ID_SM_NMS_SYS_STATUS                        1709)
(define  DB_ID_SM_OPER_IDPW_CHANGE_REQ                  1281)
(define  DB_ID_SM_OPER_INFO                             2472)
(define  DB_ID_SM_OPER_INFO_EDIT                        5453)
(define  DB_ID_SM_OPER_LOGIN_INFO                       2493)
(define  DB_ID_SM_OPER_LOGIN_REQ                        1279)
(define  DB_ID_SM_OPER_ROLE_INFO                        1587)
(define  DB_ID_SM_PRE_CONDITION_INFO                    5698)
(define  DB_ID_SM_ROLE_INFO                             2467)
(define  DB_ID_SM_ROLE_INFO_EDIT                        5454)
(define  DB_ID_SM_ROLE_LOGIN_REQ                        2494)
(define  DB_ID_SM_ROLE_SERVICE_INFO                     1589)
(define  DB_ID_SM_SERVICE_GROUP_INFO                    2516)
(define  DB_ID_SM_SERVICE_INFO                          5451)
(define  DB_ID_SM_SUBSYSTEM_STATUS_INFO_REQ             2832)
(define  DB_ID_SM_SYSTEM_PERFORMANCE_INFO_REQ           5358)
(define  DB_ID_SM_SYS_DETAIL_INFO                       5322)
(define  DB_ID_SM_SYS_PARA_FILE_RESULT                  5685)
(define  DB_ID_SM_SYS_PARA_FILE_UPDATE                  5686)
(define  DB_ID_SM_SYS_PARA_VAL                          1592)
(define  DB_ID_SM_SYS_PARA_VAL_EDIT                     5461)
(define  DB_ID_SM_SYS_POLL_TIME_AND_THRESHOLD_EDIT      1306)
(define  DB_ID_SM_TIME_AND_DATE                         1593)
(define  DB_ID_SM_TIME_AND_DATE_EDIT                    5462)
(define  DB_ID_SM_UPS_TECH_STATUS_INFO                  5417)
(define  DB_ID_SM_USERMANAGER_INFO_EDIT_STATUS          5450)
(define  DB_ID_SRS_CLIMATE_STATE_REPORT                 1939)
(define  DB_ID_SRS_JAMMER_MAP                           3256)
(define  DB_ID_SRS_RADAR_STATUS                         1949)
(define  DB_ID_SRS_SLK500_CLIMATE_STATE_REPORT          5833)
(define  DB_ID_SRS_SLK500_CLUTTER_THRESHOLD_CTRL        5935)
(define  DB_ID_SRS_SLK500_CLUTTER_THRESHOLD_STATUS      5912)
(define  DB_ID_SRS_SLK500_EQUIP_CTRL                    5917)
(define  DB_ID_SRS_SLK500_EQUIP_STATUS                  5906)
(define  DB_ID_SRS_SLK500_JAMMER_MAP                    5834)
(define  DB_ID_SRS_SLK500_JAMMER_STROBE_REPORT          5920)
(define  DB_ID_SRS_SLK500_RADAR_VIDEO_STATUS            5908)
(define  DB_ID_SRS_SLK500_RF_CHANNEL_CTRL               5918)
(define  DB_ID_SRS_SLK500_RF_CHANNEL_STATUS             5909)
(define  DB_ID_SRS_SLK500_SECTOR_CTRL                   5919)
(define  DB_ID_SRS_SLK500_SECTOR_REPORT                 5910)
(define  DB_ID_SRS_SLK500_SRS_TRACK_INFO                5913)
(define  DB_ID_SRS_SLK500_TWS_B_SCOPE_REPORT            5911)
(define  DB_ID_SRS_SLK500_TWS_CALIBRATION               5914)
(define  DB_ID_SRS_SLK500_TWS_TRACK_INFO                5915)
(define  DB_ID_SRS_SLK500_VIDEO_CTRL                    5921)
(define  DB_ID_SRS_SRS_SHUTDOWN_ACK                     1942)
(define  DB_ID_SRS_TWS_CTRL_ACK                         1929)
(define  DB_ID_SRS_XSPS550K_EQUIP_CTRL                  1491)
(define  DB_ID_SRS_XSPS550K_EQUIP_STATUS                1738)
(define  DB_ID_SRS_XSPS550K_JAMMER_STROBE_REPORT        1932)
(define  DB_ID_SRS_XSPS550K_RADAR_VIDEO_STATUS          1950)
(define  DB_ID_SRS_XSPS550K_RF_CHANNEL_CTRL             1494)
(define  DB_ID_SRS_XSPS550K_RF_CHANNEL_STATUS           2309)
(define  DB_ID_SRS_XSPS550K_SECTOR_CTRL                 1495)
(define  DB_ID_SRS_XSPS550K_SECTOR_REPORT               1933)
(define  DB_ID_SRS_XSPS550K_SRS_TRACK_INFO              2574)
(define  DB_ID_SRS_XSPS550K_TWS_B_SCOPE_REPORT          1928)
(define  DB_ID_SRS_XSPS550K_TWS_CALIBRATION             1926)
(define  DB_ID_SRS_XSPS550K_TWS_TRACK_INFO              1927)
(define  DB_ID_SRS_XSPS550K_VIDEO_CTRL                  1498)
(define  DB_ID_SS_ALL_SELECT_TV_STATUS                  5367)
(define  DB_ID_SS_ALL_SELECT_TV_STATUS_INFO             5442)
(define  DB_ID_SS_ALL_SELECT_TV_STATUS_REQ              5368)
(define  DB_ID_SS_AUDIO_DISTRIBUTE_CMD                  5443)
(define  DB_ID_SS_AW_RESIL_INFO                         5420)
(define  DB_ID_SS_COA_OPERATION                         3232)
(define  DB_ID_SS_DISP_DISTRIBUTE_INFO                  2302)
(define  DB_ID_SS_DISP_UPDOWN_SELECT                    3254)
(define  DB_ID_SS_DRAW_SERVICE                          2819)
(define  DB_ID_SS_FOC_DATA_TB                           5503)
(define  DB_ID_SS_FOC_INFO                              1725)
(define  DB_ID_SS_FOC_REQ                               1388)
(define  DB_ID_SS_FOC_RESIL_INFO                        5528)
(define  DB_ID_SS_HINDRANCE_INFO                        3247)
(define  DB_ID_SS_HINDRANCE_REQ                         3246)
(define  DB_ID_SS_ICM_RECEIVE                           1724)
(define  DB_ID_SS_ICM_SEND                              1387)
(define  DB_ID_SS_MSG_RECEIVE                           1723)
(define  DB_ID_SS_MSG_SEND                              1386)
(define  DB_ID_SS_PLATFORMLIB_EQUIP_INFO                3248)
(define  DB_ID_SS_PLATFORMLIB_EQUIP_REQ                 3253)
(define  DB_ID_SS_PLATFORMLIB_LINK_INFO                 3249)
(define  DB_ID_SS_PLATFORMLIB_LINK_REQ                  3250)
(define  DB_ID_SS_PLATFORMLIB_TRACK_QUERY               2116)
(define  DB_ID_SS_PLATFORMLIB_UNIT_INFO                 3252)
(define  DB_ID_SS_PLATFORMLIB_UNIT_REQ                  3251)
(define  DB_ID_SS_RNR_SYNC                              2600)
(define  DB_ID_SS_RVP_FILE_DELETE_CMD                   2389)
(define  DB_ID_SS_RVP_PLAY_SPEED_CMD                    5927)
(define  DB_ID_SS_RVP_RNR_CMD                           2386)
(define  DB_ID_SS_RVP_RNR_STATUS                        3090)
(define  DB_ID_SS_RVR_FILE_LIST_REQ                     2388)
(define  DB_ID_SS_SELECT_TV_INFO                        5361)
(define  DB_ID_SS_STATUS_INFO                           1737)
(define  DB_ID_SS_SUB_PREDICTION_POS                    5413)
(define  DB_ID_SS_TACINFO_COMMAND                       2611)
(define  DB_ID_SS_TACINFO_COMMAND_ACK                   2612)
(define  DB_ID_SS_TAC_FILE_DELETE_ACK                   5930)
(define  DB_ID_SS_TAC_FILE_DELETE_CMD                   5926)
(define  DB_ID_SS_TAC_PLAY_SPEED_CMD                    5929)
(define  DB_ID_SS_TAC_RNR_CMD                           5925)
(define  DB_ID_SS_TAC_RNR_CMD_ACK                       5931)
(define  DB_ID_SS_TAC_RNR_STATUS                        6187)
(define  DB_ID_SS_TAC_STATUS                            5932)
(define  DB_ID_SS_TAC_SYNC_INFO                         5460)
(define  DB_ID_SS_TA_GROUP_INFO                         3241)
(define  DB_ID_SS_TA_GROUP_REQ                          3242)
(define  DB_ID_SS_TA_INITIALIZE                         3243)
(define  DB_ID_SS_TA_SHAPE_INFO                         3244)
(define  DB_ID_SS_TA_SHAPE_REQ                          3245)
(define  DB_ID_SS_TVD_SELECT_TV_VIDEO                   1730)
(define  DB_ID_SS_TVP_AUDIO_FILE_DELETE_CMD             6125)
(define  DB_ID_SS_TVP_AUDIO_RNR_CMD                     6126)
(define  DB_ID_SS_TVP_FILE_DELETE_CMD                   1729)
(define  DB_ID_SS_TVP_PLAY_SPEED_CMD                    5928)
(define  DB_ID_SS_TVP_RNR_CMD                           1726)
(define  DB_ID_SS_TVP_RNR_STATUS                        6186)
(define  DB_ID_SS_TVR_FILE_LIST_REQ                     1728)
(define  DB_ID_SS_TVR_STATUS_REQ                        1727)
(define  DB_ID_SS_TV_CONNECT_STATUS_CMD                 1731)
(define  DB_ID_SS_TV_CONNECT_STATUS_REQ                 5529)
(define  DB_ID_SS_TV_SELECT_VIDEO                       2210)
(define  DB_ID_SS_VIDEOFILE_DATA_LIST_INFO              5444)
(define  DB_ID_SS_VIDEO_DISTRIBUTE_CMD                  2303)
(define  DB_ID_SS_VIDEO_FILE_DELETE_ACK                 1722)
(define  DB_ID_SS_VIDEO_FILE_DELETE_CMD                 1385)
(define  DB_ID_SS_VIDEO_FILE_LIST_ACK                   1721)
(define  DB_ID_SS_VIDEO_FILE_LIST_CMD                   1384)
(define  DB_ID_SS_VIDEO_PLAY_SPEED_CMD                  5324)
(define  DB_ID_SS_VIDEO_RNR_CMD                         1382)
(define  DB_ID_SS_VIDEO_RNR_CMD_ACK                     1719)
(define  DB_ID_SS_VIDEO_STATUS                          1720)
(define  DB_ID_SS_VIDEO_STATUS_REQ                      1383)
(define  DB_ID_SS_VIDEO_TIME                            2663)
(define  DB_ID_SS_WARN_AREA_INFO                        1378)
(define  DB_ID_SS_WARN_AREA_INFO_ACK                    1735)
(define  DB_ID_SUBSYSTEM_HEARTBEAT                      6086)
(define  DB_ID_TACM_MAX_SENSE_RANGE                     5846)
(define  DB_ID_TACM_RANGE                               5940)
(define  DB_ID_TACTICAL_AREA                            2559)
(define  DB_ID_TASS_TACM_CONSOLE_INFO                   5842)
(define  DB_ID_TASS_TACM_DECOY_PATTERN                  5934)
(define  DB_ID_TASS_TACM_ENERGYSPECTRUM                 5844)
(define  DB_ID_TASS_TACM_FIRED_DECOY_INFO               5835)
(define  DB_ID_TASS_TACM_FIRE_BT_CTRL                   5836)
(define  DB_ID_TASS_TACM_FIRE_MODE_INFO                 5841)
(define  DB_ID_TASS_TACM_FIRE_PATTERN_SET_REQ           5839)
(define  DB_ID_TASS_TACM_LAUNCHER_INFO                  5843)
(define  DB_ID_TASS_TACM_LAUNCHER_INIT_VALUE            5845)
(define  DB_ID_TASS_TACM_PRIMTRK_ADD_INFO               6196)
(define  DB_ID_TASS_TACM_RESET_DCY_REQ                  6120)
(define  DB_ID_TASS_TACM_SURFACE_POINT_TRACK_INFO       6119)
(define  DB_ID_TASS_TACM_TI_ENG_CMD                     5938)
(define  DB_ID_TASS_TACM_TORPEDO_ALERT_LIST             5837)
(define  DB_ID_TASS_TACM_TORPEDO_DISCERN_DISP           5847)
(define  DB_ID_TASS_TACM_WF_DATA                        5840)
(define  DB_ID_TASS_TACM_WF_LIST                        5872)
(define  DB_ID_TDA_SELECT_INFO                          2558)
(define  DB_ID_TDL_ACIM_RESIL                           6207)
(define  DB_ID_TDL_AIRCRAFT_CONTROL_INFO                2462)
(define  DB_ID_TDL_FUEL_AND_TIME                        2637)
(define  DB_ID_TM_ACK_ID_CONFLICT                       3021)
(define  DB_ID_TM_ALERT_ID_CONFLICT                     3020)
(define  DB_ID_TM_BEARING_TRACK_CANCEL                  2490)
(define  DB_ID_TM_BEARING_TRACK_INFO                    2488)
(define  DB_ID_TM_BEARING_TRACK_INFO_RT_SUP             5404)
(define  DB_ID_TM_BEARING_TRACK_INFO_RT_TAC             5405)
(define  DB_ID_TM_CHANGE_TMSINDEX                       1611)
(define  DB_ID_TM_NOTIFY_NEW_DATUM                      2594)
(define  DB_ID_TM_NOTIFY_PT_DELETE                      2542)
(define  DB_ID_TM_NOTIFY_TRAINING_TRACK                 2535)
(define  DB_ID_TM_NSFS_TRACK_INFO                       1606)
(define  DB_ID_TM_NUMBER_OF_TRACK                       1602)
(define  DB_ID_TM_POINT_TRACK_CANCEL                    2487)
(define  DB_ID_TM_POINT_TRACK_INFO                      2486)
(define  DB_ID_TM_POINT_TRACK_INFO_RT_SUP               5406)
(define  DB_ID_TM_POINT_TRACK_INFO_RT_TAC               5403)
(define  DB_ID_TM_RESILIENCE_DATA                       5476)
(define  DB_ID_TM_SELECT_AUTO_ASSOCIATION_STATUS        2513)
(define  DB_ID_TM_SET_AUTO_ASSOCIATION_OPTION           1266)
(define  DB_ID_TM_WEAPON_CAP                            2818)
(define  DB_ID_TM_WEAPON_RESTRICTION_ORDER              1604)
(define  DB_ID_TM_WEAPON_RESTRICTION_SECTOR             1605)
(define  DB_ID_TRN_CSS_TRAIN_JOIN_REQ                   2348)
(define  DB_ID_TRN_CSS_TRAIN_STATUS                     2552)
(define  DB_ID_TRN_ENV_ENVIRONMENT_REQ                  5429)
(define  DB_ID_TRN_FILTER_CMD                           3235)
(define  DB_ID_TRN_LIB_AIRCLA_CONT                      5421)
(define  DB_ID_TRN_LIB_AIRCLA_CONT_REQ                  5430)
(define  DB_ID_TRN_LIB_MIS_CONT                         5422)
(define  DB_ID_TRN_LIB_MIS_CONT_REQ                     5431)
(define  DB_ID_TRN_LIB_SEN_CONT                         5423)
(define  DB_ID_TRN_LIB_SEN_CONT_REQ                     5432)
(define  DB_ID_TRN_LIB_SUBCLA_CONT                      5424)
(define  DB_ID_TRN_LIB_SUBCLA_CONT_REQ                  5433)
(define  DB_ID_TRN_LIB_SURCLA_CONT                      5425)
(define  DB_ID_TRN_LIB_SURCLA_CONT_REQ                  5434)
(define  DB_ID_TRN_PATH_DRAW                            3237)
(define  DB_ID_TRN_SCEXE_ENVIRONMENT                    5426)
(define  DB_ID_TRN_SCEXE_OBJECT_INFO                    5427)
(define  DB_ID_TRN_SCEXE_OP_EVENT                       2578)
(define  DB_ID_TRN_SCEXE_START_STOP_CONT                1646)
(define  DB_ID_TRN_SCEXE_START_STOP_CONT_REQ            5435)
(define  DB_ID_TRN_SCON_MIS_CONT                        2565)
(define  DB_ID_TRN_SCON_MIS_CONT_REQ                    5436)
(define  DB_ID_TRN_SCON_OBJECT_CONT                     2560)
(define  DB_ID_TRN_SCON_OBJECT_CONT_REQ                 5438)
(define  DB_ID_TRN_SCON_OBJ_INFO_EDT                    1644)
(define  DB_ID_TRN_SCON_OBJ_INFO_EDT_REQ                5437)
(define  DB_ID_TRN_SCON_SCN_CONT                        1639)
(define  DB_ID_TRN_SCON_SCN_CONT_REQ                    5439)
(define  DB_ID_TRN_SCON_SCN_REMOTE                      2602)
(define  DB_ID_TRN_SCON_SEN_CONT                        2567)
(define  DB_ID_TRN_SCON_SEN_CONT_REQ                    5440)
(define  DB_ID_TRN_SCON_SNAP_CONT                       1645)
(define  DB_ID_TRN_SCON_SNAP_CONT_REQ                   5441)
(define  DB_ID_TRN_SIMIRST_SECTOR_SURVEIL_ACK           6248)
(define  DB_ID_TRN_SIM_ONOFF                            1456)
(define  DB_ID_TRN_SLTS_STATUS_REQ                      1465)
(define  DB_ID_TRN_SYMBOL_DRAW                          3236)
(define  DB_ID_TRN_TRS_STATUS                           6069)
(define  DB_ID_TRN_TRS_STATUS_REQ                       2136)
(define  DB_ID_TRN_WAYPOINT_DRAW                        3238)
(define  DB_ID_TRN_WPSIM_ACK                            3273)
(define  DB_ID_TRN_WPSIM_REQ                            3274)
(define  DB_ID_TRS_ALERT_CTRL                           5886)
(define  DB_ID_TRS_ALERT_STATUS                         5873)
(define  DB_ID_TRS_EQUIP_CTRL                           5887)
(define  DB_ID_TRS_EQUIP_STATUS                         5874)
(define  DB_ID_TRS_JOYSTICK_DATA                        5888)
(define  DB_ID_TRS_OPERATE_CTRL                         5889)
(define  DB_ID_TRS_OPERATE_STATUS                       5875)
(define  DB_ID_TRS_RADAR_CTRL                           5890)
(define  DB_ID_TRS_RADAR_STATUS                         5876)
(define  DB_ID_TRS_RAW_DATA_ALL_OUTPUT                  5877)
(define  DB_ID_TRS_RAW_DATA_OUTPUT                      5878)
(define  DB_ID_TRS_SECONDARY_TARGET                     5879)
(define  DB_ID_TRS_SECTOR_SEARCH_CTRL                   5891)
(define  DB_ID_TRS_SECTOR_SEARCH_REPORT                 5880)
(define  DB_ID_TRS_STATUS                               5881)
(define  DB_ID_TRS_TRACKING_CTRL                        5892)
(define  DB_ID_TRS_TRACKING_STATUS                      5882)
(define  DB_ID_TRS_TRACK_INFO                           5883)
(define  DB_ID_TRS_TWO_TARGET_INFO                      5884)
(define  DB_ID_TRS_VIDEO_CTRL                           5893)
(define  DB_ID_TRS_VIDEO_STATUS                         5885)
(define  DB_ID_TVP_AUDIOD_STATUS                        6123)
(define  DB_ID_TVP_AUDIOR_STATUS                        6124)
(define  DB_ID_TVP_AUDIO_FILE_DELETE_ACK                6121)
(define  DB_ID_TVP_AUDIO_RNR_CMD_ACK                    6122)
(define  DB_ID_TVP_FILE_DELETE_ACK                      1981)
(define  DB_ID_TVP_RNR_CMD_ACK                          1978)
(define  DB_ID_TVP_TVD_STATUS                           5734)
(define  DB_ID_TVP_TVR_STATUS                           1980)
(define  DB_ID_TVR_FILE_LIST_ACK                        1979)
(define  DB_ID_WC_GUN_AMMUNITION_SELECT_ORDER           6071)
(define  DB_ID_WF_AIR_THREAT_LIST                       1542)
(define  DB_ID_WF_ASW_SENSOR_RANGE_REQ                  2291)
(define  DB_ID_WF_ENGAGED_TRACK_STATUS                  1553)
(define  DB_ID_WF_ENG_CH_LIST                           1547)
(define  DB_ID_WF_ENG_INFO_LIST                         1548)
(define  DB_ID_WF_EVERY_WF_RSC_STATUS                   2506)
(define  DB_ID_WF_FIRE_AUTHORIZE                        1549)
(define  DB_ID_WF_FIRE_AUTHORIZE_REQ                    1441)
(define  DB_ID_WF_NSFS_INFO                             1551)
(define  DB_ID_WF_NSFS_INFO_SET_REQ                     5658)
(define  DB_ID_WF_QR_THREAT_LIST                        2152)
(define  DB_ID_WF_RESET_TRACKING                        2156)
(define  DB_ID_WF_RESIL_COMM_DATA                       5448)
(define  DB_ID_WF_RESIL_GEN_ENG_INFO                    5526)
(define  DB_ID_WF_RESIL_GEN_PAC_INFO                    5524)
(define  DB_ID_WF_RESIL_GEN_RESERVED_EC                 5525)
(define  DB_ID_WF_RESIL_GEN_RSC_TIMER                   5523)
(define  DB_ID_WF_RESIL_RSC_ENGAGEABLE_STATUS           5527)
(define  DB_ID_WF_RSC_ALLOC_DEALLOC_ACK                 2507)
(define  DB_ID_WF_RSC_ALLOC_DEALLOC_REQ                 1554)
(define  DB_ID_WF_SUBSURFACE_THREAT_LIST                2151)
(define  DB_ID_WF_SURFACE_THREAT_LIST                   1543)
(define  DB_ID_WF_THREAT_SELECTION_FILTER_INFO          2150)
(define  DB_ID_WF_THREAT_SELECTION_FILTER_SET_REQ       2149)
(define  DB_ID_WF_TORP_THREAT_LIST                      1546)
(define  DB_ID_WF_TRACKING_INFO_LIST                    2569)
(define  DB_ID_WF_TRACK_MANUAL_SELECTION_INFO           2530)
(define  DB_ID_WF_USER_SET_INFO_REQ                     2137)
(define  DB_ID_WF_WASA_QR_MODE                          1550)
(define  DB_ID_WF_WASA_QR_MODE_SET_REQ                  1442)
(define  DB_ID_WF_WEAPON_CAP_SET_REQ                    2817)
(define  DB_ID_WF_WEAPON_RESTRICTION_ORDER_REQ          1444)
(define  DB_ID_WF_WEAPON_RESTRICTION_SECTOR_SET_REQ     1445)
(define  DB_ID__EMCON_REQ                               2400)
(define  DB_ID__EMCON_STATUS_REQ                        2414)
(define  DB_ID__GFE_BIT_INFO                            3271)
(define  DB_ID__GUN40_CORRECTION_DATA                   2200)
(define  DB_ID__INF_CTRL_ACK                            2118)
(define  DB_ID__RSC_FIRE_AUTHORIZE_REQ                  1802)
(define  DB_ID__SIM_ONOFF_ACK                           1748)
(define  DB_ID__TORPEDO_ALERT_INFO                      2555)
(define  DB_ID__TRACK_NUM_REQ                           2300)






(define 	SUBSYSTEM_ID_CFCS_START          0 )
(define 	SUBSYSTEM_ID_LANSWT1             1 )
(define 	SUBSYSTEM_ID_LANSWT2             2 )
(define 	SUBSYSTEM_ID_MFC_1_CONTAINER     3 )
(define 	SUBSYSTEM_ID_MFC_2_CONTAINER     4 )
(define 	SUBSYSTEM_ID_MFC_3_CONTAINER     5 )
(define 	SUBSYSTEM_ID_MFC_4_CONTAINER     6 )
(define 	SUBSYSTEM_ID_MFC_5_CONTAINER     7 )
(define 	SUBSYSTEM_ID_MFC_6_CONTAINER     8 )
(define 	SUBSYSTEM_ID_MFC_7_CONTAINER     9 )
(define 	SUBSYSTEM_ID_MFC_8_CONTAINER    10 )
(define 	SUBSYSTEM_ID_MFC_9_CONTAINER    11 )
(define 	SUBSYSTEM_ID_MFC_1              12 )
(define 	SUBSYSTEM_ID_MFC_2              13 )
(define 	SUBSYSTEM_ID_MFC_3              14 )
(define 	SUBSYSTEM_ID_MFC_4              15 )
(define 	SUBSYSTEM_ID_MFC_5              16 )
(define 	SUBSYSTEM_ID_MFC_6              17 )
(define 	SUBSYSTEM_ID_MFC_7              18 )
(define 	SUBSYSTEM_ID_MFC_8              19 )
(define 	SUBSYSTEM_ID_MFC_9              20 )
(define 	SUBSYSTEM_ID_IPN1               21 )
(define 	SUBSYSTEM_ID_IPN2               22 )
(define 	SUBSYSTEM_ID_IPN3               23 )
(define 	SUBSYSTEM_ID_IPN4               24 )
(define 	SUBSYSTEM_ID_IPN5               25 )
(define 	SUBSYSTEM_ID_IPN6               26 )
(define 	SUBSYSTEM_ID_IPN7               27 )
(define 	SUBSYSTEM_ID_IPN8               28 )
(define 	SUBSYSTEM_ID_IPN9               29 )
(define 	SUBSYSTEM_ID_IPN1_B1            30 )
(define 	SUBSYSTEM_ID_IPN1_B2            31 )
(define 	SUBSYSTEM_ID_IPN1_B3            32 )
(define 	SUBSYSTEM_ID_IPN2_B1            33 )
(define 	SUBSYSTEM_ID_IPN2_B2            34 )
(define 	SUBSYSTEM_ID_IPN2_B3            35 )
(define 	SUBSYSTEM_ID_IPN3_B1            36 )
(define 	SUBSYSTEM_ID_IPN3_B2            37 )
(define 	SUBSYSTEM_ID_IPN3_B3            38 )
(define 	SUBSYSTEM_ID_IPN4_B1            39 )
(define 	SUBSYSTEM_ID_IPN4_B2            40 )
(define 	SUBSYSTEM_ID_IPN4_B3            41 )
(define 	SUBSYSTEM_ID_IPN5_B1            42 )
(define 	SUBSYSTEM_ID_IPN5_B2            43 )
(define 	SUBSYSTEM_ID_IPN5_B3            44 )
(define 	SUBSYSTEM_ID_IPN6_B1            45 )
(define 	SUBSYSTEM_ID_IPN6_B2            46 )
(define 	SUBSYSTEM_ID_IPN6_B3            47 )
(define 	SUBSYSTEM_ID_IPN7_B1            48 )
(define 	SUBSYSTEM_ID_IPN7_B2            49 )
(define 	SUBSYSTEM_ID_IPN7_B3            50 )
(define 	SUBSYSTEM_ID_IPN8_B1            51 )
(define 	SUBSYSTEM_ID_IPN8_B2            52 )
(define 	SUBSYSTEM_ID_IPN8_B3            53 )
(define 	SUBSYSTEM_ID_IPN9_B1            54 )
(define 	SUBSYSTEM_ID_IPN9_B2            55 )
(define 	SUBSYSTEM_ID_IPN9_B3            56 )
(define 	SUBSYSTEM_ID_IPNTAC1            57 )
(define 	SUBSYSTEM_ID_IPNTAC2            58 )
(define 	SUBSYSTEM_ID_IPNSUP1            59 )
(define 	SUBSYSTEM_ID_IPNSUP2            60 )
(define 	SUBSYSTEM_ID_IPNTRN1            61 )
(define 	SUBSYSTEM_ID_IPNTRN2            62 )
(define 	SUBSYSTEM_ID_IPNTAC1_B1         63 )
(define 	SUBSYSTEM_ID_IPNTAC1_B2         64 )
(define 	SUBSYSTEM_ID_IPNTAC1_B3         65 )
(define 	SUBSYSTEM_ID_IPNTAC2_B1         66 )
(define 	SUBSYSTEM_ID_IPNTAC2_B2         67 )
(define 	SUBSYSTEM_ID_IPNTAC2_B3         68 )
(define 	SUBSYSTEM_ID_IPNSUP1_B1         69 )
(define 	SUBSYSTEM_ID_IPNSUP1_B2         70 )
(define 	SUBSYSTEM_ID_IPNSUP2_B1         71 )
(define 	SUBSYSTEM_ID_IPNSUP2_B2         72 )
(define 	SUBSYSTEM_ID_IPNTRN1_B1         73 )
(define 	SUBSYSTEM_ID_IPNTRN1_B2         74 )
(define 	SUBSYSTEM_ID_IPNTRN1_B3         75 )
(define 	SUBSYSTEM_ID_IPNTRN2_B1         76 )
(define 	SUBSYSTEM_ID_IPNTRN2_B2         77 )
(define 	SUBSYSTEM_ID_IPNTRN2_B3         78 )
(define 	SUBSYSTEM_ID_CABINET1_CONTAINER 79 )
(define 	SUBSYSTEM_ID_CABINET2_CONTAINER 80 )
(define 	SUBSYSTEM_ID_CABINET3_CONTAINER 81 )
(define 	SUBSYSTEM_ID_CABINET4_CONTAINER 82 )
(define 	SUBSYSTEM_ID_CABINET5_CONTAINER 83 )
(define 	SUBSYSTEM_ID_CABINET1           84 )
(define 	SUBSYSTEM_ID_CABINET2           85 )
(define 	SUBSYSTEM_ID_CABINET3           86 )
(define 	SUBSYSTEM_ID_CABINET4           87 )
(define 	SUBSYSTEM_ID_CABINET5           88 )
(define 	SUBSYSTEM_ID_IICU_CONTAINER     89 )
(define 	SUBSYSTEM_ID_IICU1              90 )
(define 	SUBSYSTEM_ID_IICU2              91 )
(define 	SUBSYSTEM_ID_IICU3              92 )
(define 	SUBSYSTEM_ID_IICU4              93 )
(define 	SUBSYSTEM_ID_RVDU1              94 )
(define 	SUBSYSTEM_ID_RVDU2              95 )
(define 	SUBSYSTEM_ID_TVR                96 )
(define 	SUBSYSTEM_ID_RVR                97 )
(define 	SUBSYSTEM_ID_RTVDRU1            98 )
(define 	SUBSYSTEM_ID_RTVDRU2            99 )
(define 	NOT_USE8                       100 )
(define 	NOT_USE9                       101 )
(define 	NOT_USE10                      102 )
(define 	NOT_USE11                      103 )
(define 	SUBSYSTEM_ID_PRINTER           104 )
(define 	SUBSYSTEM_ID_VIDEO_SWT         105 )
(define 	NOT_USE1                       106 )
(define 	NOT_USE2                       107 )
(define 	SUBSYSTEM_ID_LINK11            108 )
(define 	SUBSYSTEM_ID_DLP_LINK11        109 )
(define 	SUBSYSTEM_ID_LINKK             110 )
(define 	SUBSYSTEM_ID_DLP_LINKK         111 )
(define 	SUBSYSTEM_ID_ISDL              112 )
(define 	SUBSYSTEM_ID_DLP_ISDL          113 )
(define 	SUBSYSTEM_ID_KNCCS             114 )
(define 	SUBSYSTEM_ID_ICU_KNCCS         115 )
(define 	SUBSYSTEM_ID_JTDLS             116 )
(define 	SUBSYSTEM_ID_ICU_JTDLS         117 )
(define 	NOT_USE3                       118 )
(define 	NOT_USE4                       119 )
(define 	SUBSYSTEM_ID_GYRO              120 )
(define 	SUBSYSTEM_ID_LOG               121 )
(define 	SUBSYSTEM_ID_GPS               122 )
(define 	SUBSYSTEM_ID_WIND              123 )
(define 	SUBSYSTEM_ID_TEMP              124 )
(define 	SUBSYSTEM_ID_ICU_OSD1          125 )
(define 	SUBSYSTEM_ID_ICU_OSD2          126 )
(define 	SUBSYSTEM_ID_SRS               127 )
(define 	SUBSYSTEM_ID_ICU_SRS           128 )
(define 	SUBSYSTEM_ID_TRS               129 )
(define 	SUBSYSTEM_ID_ICU_TRS           130 )
(define 	SUBSYSTEM_ID_EOTS              131 )
(define 	SUBSYSTEM_ID_ICU_EOTS          132 )
(define 	SUBSYSTEM_ID_IFF               133 )
(define 	SUBSYSTEM_ID_ICU_IFF           134 )
(define 	SUBSYSTEM_ID_HMS               135 )
(define 	SUBSYSTEM_ID_ICU_HMS           136 )
(define 	SUBSYSTEM_ID_EW                137 )
(define 	SUBSYSTEM_ID_ICU_EW            138 )
(define 	SUBSYSTEM_ID_AIS               139 )
(define 	SUBSYSTEM_ID_ICU_AIS           140 )
(define 	SUBSYSTEM_ID_ES                141 )
(define 	SUBSYSTEM_ID_ICU_ES            142 )
(define 	SUBSYSTEM_ID_NRS               143 )
(define 	SUBSYSTEM_ID_ICU_NRS           144 )
(define 	SUBSYSTEM_ID_LYNXESM           145 )
(define 	SUBSYSTEM_ID_ICU_LYNXESM       146 )
(define 	SUBSYSTEM_ID_IRST              147 )
(define 	SUBSYSTEM_ID_ICU_IRST          148 )
(define 	SUBSYSTEM_ID_TAS               149 )
(define 	SUBSYSTEM_ID_ICU_TAS           150 )
(define 	NOT_USE5                       151 )
(define 	NOT_USE6                       152 )
(define 	SUBSYSTEM_ID_TACM              153 )
(define 	SUBSYSTEM_ID_FCU_TACM          154 )
(define 	SUBSYSTEM_ID_TACM_PORT         155 )
(define 	SUBSYSTEM_ID_TACM_STAR         156 )
(define 	SUBSYSTEM_ID_TACM_CONSOL       157 )
(define 	SUBSYSTEM_ID_SAAM              158 )
(define 	SUBSYSTEM_ID_ICU_SAAM          159 )
(define 	SUBSYSTEM_ID_CIWS              160 )
(define 	SUBSYSTEM_ID_ICU_CIWS          161 )
(define 	SUBSYSTEM_ID_KSSM              162 )
(define 	SUBSYSTEM_ID_ICU_KSSM          163 )
(define 	SUBSYSTEM_ID_KTSLM             164 )
(define 	SUBSYSTEM_ID_ICU_KTSLM         165 )
(define 	SUBSYSTEM_ID_DCY               166 )
(define 	SUBSYSTEM_ID_ICU_DCY           167 )
(define 	SUBSYSTEM_ID_GUN               168 )
(define 	SUBSYSTEM_ID_BCU_GUN           169 )
(define 	SUBSYSTEM_ID_SLTS              170 )
(define 	SUBSYSTEM_ID_FCU_SLTS          171 )
(define 	SUBSYSTEM_ID_RCWS1             172 )
(define 	SUBSYSTEM_ID_ICU_RCWS1         173 )
(define 	SUBSYSTEM_ID_RCWS2             174 )
(define 	SUBSYSTEM_ID_ICU_RCWS2         175 )
(define 	SUBSYSTEM_ID_ROCKET            176 )
(define 	SUBSYSTEM_ID_ICU_ROCKET        177 )
(define 	SUBSYSTEM_ID_MASS              178 )
(define 	SUBSYSTEM_ID_ICU_MASS          179 )
(define 	SUBSYSTEM_ID_KVLA              180 )
(define 	SUBSYSTEM_ID_ICU_KVLA          181 )
(define 	NOT_USE7                       182 )
(define 	SUBSYSTEM_ID_RTVDRU1_B1        183 )
(define 	SUBSYSTEM_ID_RTVDRU1_B2        184 )
(define 	SUBSYSTEM_ID_RTVDRU1_B3        185 )
(define 	SUBSYSTEM_ID_RTVDRU1_B4        186 )
(define 	SUBSYSTEM_ID_RTVDRU1_B5        187 )
(define 	SUBSYSTEM_ID_RTVDRU2_B1        188 )
(define 	SUBSYSTEM_ID_RTVDRU2_B2        189 )
(define 	SUBSYSTEM_ID_RTVDRU2_B3        190 )
(define 	SUBSYSTEM_ID_RTVDRU2_B4        191 )
(define 	SUBSYSTEM_ID_RTVDRU2_B5        192 )
(define 	SUBSYSTEM_ID_ISN1              193 )
(define 	SUBSYSTEM_ID_ISN2              194 )
(define 	SUBSYSTEM_ID_ISN1_B1           195 )
(define 	SUBSYSTEM_ID_ISN1_B2           196 )
(define 	SUBSYSTEM_ID_ISN1_B3           197 )
(define 	SUBSYSTEM_ID_ISN2_B1           198 )
(define 	SUBSYSTEM_ID_ISN2_B2           199 )
(define 	SUBSYSTEM_ID_ISN2_B3           200 )
(define 	SUBSYSTEM_ID_LANSWT3           201 )
(define 	SUBSYSTEM_ID_LANSWT4           202 )
(define 	SUBSYSTEM_ID_DTS               203 )
