(define ew_intelligence_types-A1 47 ) ; 0x2f
(define ew_intelligence_types-A37 48 ) ; 0x30
(define ew_intelligence_types-A4 43 ) ; 0x2b
(define ew_intelligence_types-A7 40 ) ; 0x28
(define ew_intelligence_types-AAA_site_general 30 ) ; 0x1e
(define ew_intelligence_types-AAA_site_land_general 2 ) ; 0x2
(define ew_intelligence_types-AACU_surf_current_activity 22 ) ; 0x16
(define ew_intelligence_types-ACP 7 ) ; 0x7
(define ew_intelligence_types-ACU_subsurf_current_activity 20 ) ; 0x14
(define ew_intelligence_types-ACU_surf_current_activity 21 ) ; 0x15
(define ew_intelligence_types-AEW_1 1 ) ; 0x1
(define ew_intelligence_types-AEW_10 10 ) ; 0xa
(define ew_intelligence_types-AEW_11 11 ) ; 0xb
(define ew_intelligence_types-AEW_12 12 ) ; 0xc
(define ew_intelligence_types-AEW_13 13 ) ; 0xd
(define ew_intelligence_types-AEW_14 14 ) ; 0xe
(define ew_intelligence_types-AEW_15 15 ) ; 0xf
(define ew_intelligence_types-AEW_16 16 ) ; 0x10
(define ew_intelligence_types-AEW_17 17 ) ; 0x11
(define ew_intelligence_types-AEW_18 18 ) ; 0x12
(define ew_intelligence_types-AEW_19 19 ) ; 0x13
(define ew_intelligence_types-AEW_2 2 ) ; 0x2
(define ew_intelligence_types-AEW_20 20 ) ; 0x14
(define ew_intelligence_types-AEW_21 21 ) ; 0x15
(define ew_intelligence_types-AEW_22 22 ) ; 0x16
(define ew_intelligence_types-AEW_23 23 ) ; 0x17
(define ew_intelligence_types-AEW_24 24 ) ; 0x18
(define ew_intelligence_types-AEW_25 25 ) ; 0x19
(define ew_intelligence_types-AEW_26 26 ) ; 0x1a
(define ew_intelligence_types-AEW_27 27 ) ; 0x1b
(define ew_intelligence_types-AEW_28 28 ) ; 0x1c
(define ew_intelligence_types-AEW_29 29 ) ; 0x1d
(define ew_intelligence_types-AEW_3 3 ) ; 0x3
(define ew_intelligence_types-AEW_30 30 ) ; 0x1e
(define ew_intelligence_types-AEW_31 31 ) ; 0x1f
(define ew_intelligence_types-AEW_4 4 ) ; 0x4
(define ew_intelligence_types-AEW_5 5 ) ; 0x5
(define ew_intelligence_types-AEW_6 6 ) ; 0x6
(define ew_intelligence_types-AEW_7 7 ) ; 0x7
(define ew_intelligence_types-AEW_8 8 ) ; 0x8
(define ew_intelligence_types-AEW_9 9 ) ; 0x9
(define ew_intelligence_types-AEW_air_general 10 ) ; 0xa
(define ew_intelligence_types-AEW_air_mission 8 ) ; 0x8
(define ew_intelligence_types-AEW_general 13 ) ; 0xd
(define ew_intelligence_types-AH_1 1 ) ; 0x1
(define ew_intelligence_types-AH_10 10 ) ; 0xa
(define ew_intelligence_types-AH_11 11 ) ; 0xb
(define ew_intelligence_types-AH_12 12 ) ; 0xc
(define ew_intelligence_types-AH_13 13 ) ; 0xd
(define ew_intelligence_types-AH_14 14 ) ; 0xe
(define ew_intelligence_types-AH_15 15 ) ; 0xf
(define ew_intelligence_types-AH_16 16 ) ; 0x10
(define ew_intelligence_types-AH_17 17 ) ; 0x11
(define ew_intelligence_types-AH_18 18 ) ; 0x12
(define ew_intelligence_types-AH_19 19 ) ; 0x13
(define ew_intelligence_types-AH_1_1 34 ) ; 0x22
(define ew_intelligence_types-AH_2 2 ) ; 0x2
(define ew_intelligence_types-AH_20 20 ) ; 0x14
(define ew_intelligence_types-AH_21 21 ) ; 0x15
(define ew_intelligence_types-AH_22 22 ) ; 0x16
(define ew_intelligence_types-AH_23 23 ) ; 0x17
(define ew_intelligence_types-AH_24 24 ) ; 0x18
(define ew_intelligence_types-AH_25 25 ) ; 0x19
(define ew_intelligence_types-AH_26 26 ) ; 0x1a
(define ew_intelligence_types-AH_27 27 ) ; 0x1b
(define ew_intelligence_types-AH_28 28 ) ; 0x1c
(define ew_intelligence_types-AH_29 29 ) ; 0x1d
(define ew_intelligence_types-AH_3 3 ) ; 0x3
(define ew_intelligence_types-AH_30 30 ) ; 0x1e
(define ew_intelligence_types-AH_31 31 ) ; 0x1f
(define ew_intelligence_types-AH_4 4 ) ; 0x4
(define ew_intelligence_types-AH_5 5 ) ; 0x5
(define ew_intelligence_types-AH_6 6 ) ; 0x6
(define ew_intelligence_types-AH_7 7 ) ; 0x7
(define ew_intelligence_types-AH_8 8 ) ; 0x8
(define ew_intelligence_types-AH_9 9 ) ; 0x9
(define ew_intelligence_types-AIR_TBD10_air_current_activity 61 ) ; 0x3d
(define ew_intelligence_types-AIR_TBD11_air_current_activity 62 ) ; 0x3e
(define ew_intelligence_types-AIR_TBD1_air_current_activity 52 ) ; 0x34
(define ew_intelligence_types-AIR_TBD2_air_current_activity 53 ) ; 0x35
(define ew_intelligence_types-AIR_TBD3_air_current_activity 54 ) ; 0x36
(define ew_intelligence_types-AIR_TBD4_air_current_activity 55 ) ; 0x37
(define ew_intelligence_types-AIR_TBD5_air_current_activity 56 ) ; 0x38
(define ew_intelligence_types-AIR_TBD6_air_current_activity 57 ) ; 0x39
(define ew_intelligence_types-AIR_TBD7_air_current_activity 58 ) ; 0x3a
(define ew_intelligence_types-AIR_TBD8_air_current_activity 59 ) ; 0x3b
(define ew_intelligence_types-AIR_TBD9_air_current_activity 60 ) ; 0x3c
(define ew_intelligence_types-AIR_TBD_air_current_activity 51 ) ; 0x33
(define ew_intelligence_types-AMX_1 1 ) ; 0x1
(define ew_intelligence_types-AMX_10 10 ) ; 0xa
(define ew_intelligence_types-AMX_11 11 ) ; 0xb
(define ew_intelligence_types-AMX_12 12 ) ; 0xc
(define ew_intelligence_types-AMX_13 13 ) ; 0xd
(define ew_intelligence_types-AMX_14 14 ) ; 0xe
(define ew_intelligence_types-AMX_15 15 ) ; 0xf
(define ew_intelligence_types-AMX_16 16 ) ; 0x10
(define ew_intelligence_types-AMX_17 17 ) ; 0x11
(define ew_intelligence_types-AMX_18 18 ) ; 0x12
(define ew_intelligence_types-AMX_19 19 ) ; 0x13
(define ew_intelligence_types-AMX_2 2 ) ; 0x2
(define ew_intelligence_types-AMX_20 20 ) ; 0x14
(define ew_intelligence_types-AMX_21 21 ) ; 0x15
(define ew_intelligence_types-AMX_22 22 ) ; 0x16
(define ew_intelligence_types-AMX_23 23 ) ; 0x17
(define ew_intelligence_types-AMX_24 24 ) ; 0x18
(define ew_intelligence_types-AMX_25 25 ) ; 0x19
(define ew_intelligence_types-AMX_26 26 ) ; 0x1a
(define ew_intelligence_types-AMX_27 27 ) ; 0x1b
(define ew_intelligence_types-AMX_28 28 ) ; 0x1c
(define ew_intelligence_types-AMX_29 29 ) ; 0x1d
(define ew_intelligence_types-AMX_3 3 ) ; 0x3
(define ew_intelligence_types-AMX_30 30 ) ; 0x1e
(define ew_intelligence_types-AMX_31 31 ) ; 0x1f
(define ew_intelligence_types-AMX_4 4 ) ; 0x4
(define ew_intelligence_types-AMX_5 5 ) ; 0x5
(define ew_intelligence_types-AMX_6 6 ) ; 0x6
(define ew_intelligence_types-AMX_7 7 ) ; 0x7
(define ew_intelligence_types-AMX_8 8 ) ; 0x8
(define ew_intelligence_types-AMX_9 9 ) ; 0x9
(define ew_intelligence_types-AN_12 33 ) ; 0x21
(define ew_intelligence_types-AOX_1 1 ) ; 0x1
(define ew_intelligence_types-AOX_10 10 ) ; 0xa
(define ew_intelligence_types-AOX_11 11 ) ; 0xb
(define ew_intelligence_types-AOX_12 12 ) ; 0xc
(define ew_intelligence_types-AOX_13 13 ) ; 0xd
(define ew_intelligence_types-AOX_14 14 ) ; 0xe
(define ew_intelligence_types-AOX_15 15 ) ; 0xf
(define ew_intelligence_types-AOX_16 16 ) ; 0x10
(define ew_intelligence_types-AOX_17 17 ) ; 0x11
(define ew_intelligence_types-AOX_18 18 ) ; 0x12
(define ew_intelligence_types-AOX_19 19 ) ; 0x13
(define ew_intelligence_types-AOX_2 2 ) ; 0x2
(define ew_intelligence_types-AOX_20 20 ) ; 0x14
(define ew_intelligence_types-AOX_21 21 ) ; 0x15
(define ew_intelligence_types-AOX_22 22 ) ; 0x16
(define ew_intelligence_types-AOX_23 23 ) ; 0x17
(define ew_intelligence_types-AOX_24 24 ) ; 0x18
(define ew_intelligence_types-AOX_25 25 ) ; 0x19
(define ew_intelligence_types-AOX_26 26 ) ; 0x1a
(define ew_intelligence_types-AOX_27 27 ) ; 0x1b
(define ew_intelligence_types-AOX_28 28 ) ; 0x1c
(define ew_intelligence_types-AOX_29 29 ) ; 0x1d
(define ew_intelligence_types-AOX_3 3 ) ; 0x3
(define ew_intelligence_types-AOX_30 30 ) ; 0x1e
(define ew_intelligence_types-AOX_31 31 ) ; 0x1f
(define ew_intelligence_types-AOX_4 4 ) ; 0x4
(define ew_intelligence_types-AOX_5 5 ) ; 0x5
(define ew_intelligence_types-AOX_6 6 ) ; 0x6
(define ew_intelligence_types-AOX_7 7 ) ; 0x7
(define ew_intelligence_types-AOX_8 8 ) ; 0x8
(define ew_intelligence_types-AOX_9 9 ) ; 0x9
(define ew_intelligence_types-ASWACU_surf_current_activity 23 ) ; 0x17
(define ew_intelligence_types-ASW_Search_air_current_activity 26 ) ; 0x1a
(define ew_intelligence_types-ASW_air_mission 15 ) ; 0xf
(define ew_intelligence_types-ASW_missile_mission 3 ) ; 0x3
(define ew_intelligence_types-ASW_subsurface_mission 2 ) ; 0x2
(define ew_intelligence_types-ASW_surface_mission 4 ) ; 0x4
(define ew_intelligence_types-AUX_1 1 ) ; 0x1
(define ew_intelligence_types-AUX_10 10 ) ; 0xa
(define ew_intelligence_types-AUX_11 11 ) ; 0xb
(define ew_intelligence_types-AUX_12 12 ) ; 0xc
(define ew_intelligence_types-AUX_13 13 ) ; 0xd
(define ew_intelligence_types-AUX_14 14 ) ; 0xe
(define ew_intelligence_types-AUX_15 15 ) ; 0xf
(define ew_intelligence_types-AUX_16 16 ) ; 0x10
(define ew_intelligence_types-AUX_17 17 ) ; 0x11
(define ew_intelligence_types-AUX_18 18 ) ; 0x12
(define ew_intelligence_types-AUX_19 19 ) ; 0x13
(define ew_intelligence_types-AUX_2 2 ) ; 0x2
(define ew_intelligence_types-AUX_20 20 ) ; 0x14
(define ew_intelligence_types-AUX_21 21 ) ; 0x15
(define ew_intelligence_types-AUX_22 22 ) ; 0x16
(define ew_intelligence_types-AUX_23 23 ) ; 0x17
(define ew_intelligence_types-AUX_24 24 ) ; 0x18
(define ew_intelligence_types-AUX_25 25 ) ; 0x19
(define ew_intelligence_types-AUX_26 26 ) ; 0x1a
(define ew_intelligence_types-AUX_27 27 ) ; 0x1b
(define ew_intelligence_types-AUX_28 28 ) ; 0x1c
(define ew_intelligence_types-AUX_29 29 ) ; 0x1d
(define ew_intelligence_types-AUX_3 3 ) ; 0x3
(define ew_intelligence_types-AUX_30 30 ) ; 0x1e
(define ew_intelligence_types-AUX_31 31 ) ; 0x1f
(define ew_intelligence_types-AUX_4 4 ) ; 0x4
(define ew_intelligence_types-AUX_5 5 ) ; 0x5
(define ew_intelligence_types-AUX_6 6 ) ; 0x6
(define ew_intelligence_types-AUX_7 7 ) ; 0x7
(define ew_intelligence_types-AUX_8 8 ) ; 0x8
(define ew_intelligence_types-AUX_9 9 ) ; 0x9
(define ew_intelligence_types-Air_Assault 14 ) ; 0xe
(define ew_intelligence_types-Air_Ops_surf_current_activity 7 ) ; 0x7
(define ew_intelligence_types-Air_TDB_51 51 ) ; 0x33
(define ew_intelligence_types-Air_TDB_52 52 ) ; 0x34
(define ew_intelligence_types-Air_TDB_53 53 ) ; 0x35
(define ew_intelligence_types-Air_TDB_54 54 ) ; 0x36
(define ew_intelligence_types-Air_TDB_55 55 ) ; 0x37
(define ew_intelligence_types-Air_TDB_56 56 ) ; 0x38
(define ew_intelligence_types-Air_TDB_57 57 ) ; 0x39
(define ew_intelligence_types-Air_TDB_58 58 ) ; 0x3a
(define ew_intelligence_types-Air_TDB_59 59 ) ; 0x3b
(define ew_intelligence_types-Air_TDB_60 60 ) ; 0x3c
(define ew_intelligence_types-Air_TDB_61 61 ) ; 0x3d
(define ew_intelligence_types-Air_TDB_62 62 ) ; 0x3e
(define ew_intelligence_types-Airborne 12 ) ; 0xc
(define ew_intelligence_types-Airlift 5 ) ; 0x5
(define ew_intelligence_types-Albania 50 ) ; 0x32
(define ew_intelligence_types-Algeria 69 ) ; 0x45
(define ew_intelligence_types-Amphibious_subsurface_mission 4 ) ; 0x4
(define ew_intelligence_types-Amphibious_surface_mission 6 ) ; 0x6
(define ew_intelligence_types-Anti_Air_missile_mission 1 ) ; 0x1
(define ew_intelligence_types-Anti_Air_surface_mission 1 ) ; 0x1
(define ew_intelligence_types-Anti_Ship 20 ) ; 0x14
(define ew_intelligence_types-Anti_Surface_missile_mission 2 ) ; 0x2
(define ew_intelligence_types-Anti_Surface_subsurface_mission 3 ) ; 0x3
(define ew_intelligence_types-Anti_Surface_surface_mission 3 ) ; 0x3
(define ew_intelligence_types-Anti_Warfare_surface_mission 2 ) ; 0x2
(define ew_intelligence_types-Argentina 88 ) ; 0x58
(define ew_intelligence_types-Armed_air_current_activity 3 ) ; 0x3
(define ew_intelligence_types-Assault 13 ) ; 0xd
(define ew_intelligence_types-Assigned_Destroy_air_current_activity 2 ) ; 0x2
(define ew_intelligence_types-Assigned_Destroy_land_current_activity 2 ) ; 0x2
(define ew_intelligence_types-Assigned_surf_current_activity 6 ) ; 0x6
(define ew_intelligence_types-Attacking_surf_current_activity 1 ) ; 0x1
(define ew_intelligence_types-Australia 86 ) ; 0x56
(define ew_intelligence_types-Austria 51 ) ; 0x33
(define ew_intelligence_types-BACK_FIRE 38 ) ; 0x26
(define ew_intelligence_types-BE_12 36 ) ; 0x24
(define ew_intelligence_types-BE_6 38 ) ; 0x26
(define ew_intelligence_types-BMB_1 1 ) ; 0x1
(define ew_intelligence_types-BMB_10 10 ) ; 0xa
(define ew_intelligence_types-BMB_11 11 ) ; 0xb
(define ew_intelligence_types-BMB_12 12 ) ; 0xc
(define ew_intelligence_types-BMB_13 13 ) ; 0xd
(define ew_intelligence_types-BMB_14 14 ) ; 0xe
(define ew_intelligence_types-BMB_15 15 ) ; 0xf
(define ew_intelligence_types-BMB_16 16 ) ; 0x10
(define ew_intelligence_types-BMB_17 17 ) ; 0x11
(define ew_intelligence_types-BMB_18 18 ) ; 0x12
(define ew_intelligence_types-BMB_19 19 ) ; 0x13
(define ew_intelligence_types-BMB_2 2 ) ; 0x2
(define ew_intelligence_types-BMB_20 20 ) ; 0x14
(define ew_intelligence_types-BMB_21 21 ) ; 0x15
(define ew_intelligence_types-BMB_22 22 ) ; 0x16
(define ew_intelligence_types-BMB_23 23 ) ; 0x17
(define ew_intelligence_types-BMB_24 24 ) ; 0x18
(define ew_intelligence_types-BMB_25 25 ) ; 0x19
(define ew_intelligence_types-BMB_26 26 ) ; 0x1a
(define ew_intelligence_types-BMB_27 27 ) ; 0x1b
(define ew_intelligence_types-BMB_28 28 ) ; 0x1c
(define ew_intelligence_types-BMB_29 29 ) ; 0x1d
(define ew_intelligence_types-BMB_3 3 ) ; 0x3
(define ew_intelligence_types-BMB_30 30 ) ; 0x1e
(define ew_intelligence_types-BMB_31 31 ) ; 0x1f
(define ew_intelligence_types-BMB_4 4 ) ; 0x4
(define ew_intelligence_types-BMB_5 5 ) ; 0x5
(define ew_intelligence_types-BMB_6 6 ) ; 0x6
(define ew_intelligence_types-BMB_7 7 ) ; 0x7
(define ew_intelligence_types-BMB_8 8 ) ; 0x8
(define ew_intelligence_types-BMB_9 9 ) ; 0x9
(define ew_intelligence_types-B_52 39 ) ; 0x27
(define ew_intelligence_types-B_707_air_support_specific 37 ) ; 0x25
(define ew_intelligence_types-B_707_civil_specific 37 ) ; 0x25
(define ew_intelligence_types-B_727 38 ) ; 0x26
(define ew_intelligence_types-B_737 39 ) ; 0x27
(define ew_intelligence_types-B_747 40 ) ; 0x28
(define ew_intelligence_types-Belgium 32 ) ; 0x20
(define ew_intelligence_types-Brazil 89 ) ; 0x59
(define ew_intelligence_types-Broken_air_current_activity 10 ) ; 0xa
(define ew_intelligence_types-Broken_land_current_activity 10 ) ; 0xa
(define ew_intelligence_types-Broken_surf_current_activity 10 ) ; 0xa
(define ew_intelligence_types-Bulgaria 52 ) ; 0x34
(define ew_intelligence_types-CAP 1 ) ; 0x1
(define ew_intelligence_types-CAS 2 ) ; 0x2
(define ew_intelligence_types-CGX_1 1 ) ; 0x1
(define ew_intelligence_types-CGX_10 10 ) ; 0xa
(define ew_intelligence_types-CGX_11 11 ) ; 0xb
(define ew_intelligence_types-CGX_12 12 ) ; 0xc
(define ew_intelligence_types-CGX_13 13 ) ; 0xd
(define ew_intelligence_types-CGX_14 14 ) ; 0xe
(define ew_intelligence_types-CGX_15 15 ) ; 0xf
(define ew_intelligence_types-CGX_16 16 ) ; 0x10
(define ew_intelligence_types-CGX_17 17 ) ; 0x11
(define ew_intelligence_types-CGX_18 18 ) ; 0x12
(define ew_intelligence_types-CGX_19 19 ) ; 0x13
(define ew_intelligence_types-CGX_2 2 ) ; 0x2
(define ew_intelligence_types-CGX_20 20 ) ; 0x14
(define ew_intelligence_types-CGX_21 21 ) ; 0x15
(define ew_intelligence_types-CGX_22 22 ) ; 0x16
(define ew_intelligence_types-CGX_23 23 ) ; 0x17
(define ew_intelligence_types-CGX_24 24 ) ; 0x18
(define ew_intelligence_types-CGX_25 25 ) ; 0x19
(define ew_intelligence_types-CGX_26 26 ) ; 0x1a
(define ew_intelligence_types-CGX_27 27 ) ; 0x1b
(define ew_intelligence_types-CGX_28 28 ) ; 0x1c
(define ew_intelligence_types-CGX_29 29 ) ; 0x1d
(define ew_intelligence_types-CGX_3 3 ) ; 0x3
(define ew_intelligence_types-CGX_30 30 ) ; 0x1e
(define ew_intelligence_types-CGX_31 31 ) ; 0x1f
(define ew_intelligence_types-CGX_4 4 ) ; 0x4
(define ew_intelligence_types-CGX_5 5 ) ; 0x5
(define ew_intelligence_types-CGX_6 6 ) ; 0x6
(define ew_intelligence_types-CGX_7 7 ) ; 0x7
(define ew_intelligence_types-CGX_8 8 ) ; 0x8
(define ew_intelligence_types-CGX_9 9 ) ; 0x9
(define ew_intelligence_types-CIV_1 1 ) ; 0x1
(define ew_intelligence_types-CIV_10 10 ) ; 0xa
(define ew_intelligence_types-CIV_11 11 ) ; 0xb
(define ew_intelligence_types-CIV_12 12 ) ; 0xc
(define ew_intelligence_types-CIV_13 13 ) ; 0xd
(define ew_intelligence_types-CIV_14 14 ) ; 0xe
(define ew_intelligence_types-CIV_15 15 ) ; 0xf
(define ew_intelligence_types-CIV_16 16 ) ; 0x10
(define ew_intelligence_types-CIV_17 17 ) ; 0x11
(define ew_intelligence_types-CIV_18 18 ) ; 0x12
(define ew_intelligence_types-CIV_19 19 ) ; 0x13
(define ew_intelligence_types-CIV_2 2 ) ; 0x2
(define ew_intelligence_types-CIV_20 20 ) ; 0x14
(define ew_intelligence_types-CIV_21 21 ) ; 0x15
(define ew_intelligence_types-CIV_22 22 ) ; 0x16
(define ew_intelligence_types-CIV_23 23 ) ; 0x17
(define ew_intelligence_types-CIV_24 24 ) ; 0x18
(define ew_intelligence_types-CIV_25 25 ) ; 0x19
(define ew_intelligence_types-CIV_26 26 ) ; 0x1a
(define ew_intelligence_types-CIV_27 27 ) ; 0x1b
(define ew_intelligence_types-CIV_28 28 ) ; 0x1c
(define ew_intelligence_types-CIV_29 29 ) ; 0x1d
(define ew_intelligence_types-CIV_3 3 ) ; 0x3
(define ew_intelligence_types-CIV_30 30 ) ; 0x1e
(define ew_intelligence_types-CIV_31 31 ) ; 0x1f
(define ew_intelligence_types-CIV_4 4 ) ; 0x4
(define ew_intelligence_types-CIV_5 5 ) ; 0x5
(define ew_intelligence_types-CIV_6 6 ) ; 0x6
(define ew_intelligence_types-CIV_7 7 ) ; 0x7
(define ew_intelligence_types-CIV_8 8 ) ; 0x8
(define ew_intelligence_types-CIV_9 9 ) ; 0x9
(define ew_intelligence_types-CONCORDE 44 ) ; 0x2c
(define ew_intelligence_types-CVX_1 1 ) ; 0x1
(define ew_intelligence_types-CVX_10 10 ) ; 0xa
(define ew_intelligence_types-CVX_11 11 ) ; 0xb
(define ew_intelligence_types-CVX_12 12 ) ; 0xc
(define ew_intelligence_types-CVX_13 13 ) ; 0xd
(define ew_intelligence_types-CVX_14 14 ) ; 0xe
(define ew_intelligence_types-CVX_15 15 ) ; 0xf
(define ew_intelligence_types-CVX_16 16 ) ; 0x10
(define ew_intelligence_types-CVX_17 17 ) ; 0x11
(define ew_intelligence_types-CVX_18 18 ) ; 0x12
(define ew_intelligence_types-CVX_19 19 ) ; 0x13
(define ew_intelligence_types-CVX_2 2 ) ; 0x2
(define ew_intelligence_types-CVX_20 20 ) ; 0x14
(define ew_intelligence_types-CVX_21 21 ) ; 0x15
(define ew_intelligence_types-CVX_22 22 ) ; 0x16
(define ew_intelligence_types-CVX_23 23 ) ; 0x17
(define ew_intelligence_types-CVX_24 24 ) ; 0x18
(define ew_intelligence_types-CVX_25 25 ) ; 0x19
(define ew_intelligence_types-CVX_26 26 ) ; 0x1a
(define ew_intelligence_types-CVX_27 27 ) ; 0x1b
(define ew_intelligence_types-CVX_28 28 ) ; 0x1c
(define ew_intelligence_types-CVX_29 29 ) ; 0x1d
(define ew_intelligence_types-CVX_3 3 ) ; 0x3
(define ew_intelligence_types-CVX_30 30 ) ; 0x1e
(define ew_intelligence_types-CVX_31 31 ) ; 0x1f
(define ew_intelligence_types-CVX_4 4 ) ; 0x4
(define ew_intelligence_types-CVX_5 5 ) ; 0x5
(define ew_intelligence_types-CVX_6 6 ) ; 0x6
(define ew_intelligence_types-CVX_7 7 ) ; 0x7
(define ew_intelligence_types-CVX_8 8 ) ; 0x8
(define ew_intelligence_types-CVX_9 9 ) ; 0x9
(define ew_intelligence_types-C_119 44 ) ; 0x2c
(define ew_intelligence_types-C_123 45 ) ; 0x2d
(define ew_intelligence_types-C_130 46 ) ; 0x2e
(define ew_intelligence_types-C_7 42 ) ; 0x2a
(define ew_intelligence_types-C_9 43 ) ; 0x2b
(define ew_intelligence_types-Cambodia 76 ) ; 0x4c
(define ew_intelligence_types-Canada 59 ) ; 0x3b
(define ew_intelligence_types-Chaff_Drop_air_current_activity 23 ) ; 0x17
(define ew_intelligence_types-Chile 90 ) ; 0x5a
(define ew_intelligence_types-China_People_Republic 80 ) ; 0x50
(define ew_intelligence_types-China_Republic 81 ) ; 0x51
(define ew_intelligence_types-Columbia 91 ) ; 0x5b
(define ew_intelligence_types-Command_surf_current_activity 13 ) ; 0xd
(define ew_intelligence_types-Convoy_surf_current_activity 14 ) ; 0xe
(define ew_intelligence_types-Cuba 96 ) ; 0x60
(define ew_intelligence_types-Cyprus 33 ) ; 0x21
(define ew_intelligence_types-Czechoslovakia 53 ) ; 0x35
(define ew_intelligence_types-DC_10 42 ) ; 0x2a
(define ew_intelligence_types-DC_8 41 ) ; 0x29
(define ew_intelligence_types-DDX_1 1 ) ; 0x1
(define ew_intelligence_types-DDX_10 10 ) ; 0xa
(define ew_intelligence_types-DDX_11 11 ) ; 0xb
(define ew_intelligence_types-DDX_12 12 ) ; 0xc
(define ew_intelligence_types-DDX_13 13 ) ; 0xd
(define ew_intelligence_types-DDX_14 14 ) ; 0xe
(define ew_intelligence_types-DDX_15 15 ) ; 0xf
(define ew_intelligence_types-DDX_16 16 ) ; 0x10
(define ew_intelligence_types-DDX_17 17 ) ; 0x11
(define ew_intelligence_types-DDX_18 18 ) ; 0x12
(define ew_intelligence_types-DDX_19 19 ) ; 0x13
(define ew_intelligence_types-DDX_2 2 ) ; 0x2
(define ew_intelligence_types-DDX_20 20 ) ; 0x14
(define ew_intelligence_types-DDX_21 21 ) ; 0x15
(define ew_intelligence_types-DDX_22 22 ) ; 0x16
(define ew_intelligence_types-DDX_23 23 ) ; 0x17
(define ew_intelligence_types-DDX_24 24 ) ; 0x18
(define ew_intelligence_types-DDX_25 25 ) ; 0x19
(define ew_intelligence_types-DDX_26 26 ) ; 0x1a
(define ew_intelligence_types-DDX_27 27 ) ; 0x1b
(define ew_intelligence_types-DDX_28 28 ) ; 0x1c
(define ew_intelligence_types-DDX_29 29 ) ; 0x1d
(define ew_intelligence_types-DDX_3 3 ) ; 0x3
(define ew_intelligence_types-DDX_30 30 ) ; 0x1e
(define ew_intelligence_types-DDX_31 31 ) ; 0x1f
(define ew_intelligence_types-DDX_4 4 ) ; 0x4
(define ew_intelligence_types-DDX_5 5 ) ; 0x5
(define ew_intelligence_types-DDX_6 6 ) ; 0x6
(define ew_intelligence_types-DDX_7 7 ) ; 0x7
(define ew_intelligence_types-DDX_8 8 ) ; 0x8
(define ew_intelligence_types-DDX_9 9 ) ; 0x9
(define ew_intelligence_types-DM 2 ) ; 0x2
(define ew_intelligence_types-D_R_1 1 ) ; 0x1
(define ew_intelligence_types-D_R_10 10 ) ; 0xa
(define ew_intelligence_types-D_R_11 11 ) ; 0xb
(define ew_intelligence_types-D_R_12 12 ) ; 0xc
(define ew_intelligence_types-D_R_13 13 ) ; 0xd
(define ew_intelligence_types-D_R_14 14 ) ; 0xe
(define ew_intelligence_types-D_R_15 15 ) ; 0xf
(define ew_intelligence_types-D_R_16 16 ) ; 0x10
(define ew_intelligence_types-D_R_17 17 ) ; 0x11
(define ew_intelligence_types-D_R_18 18 ) ; 0x12
(define ew_intelligence_types-D_R_19 19 ) ; 0x13
(define ew_intelligence_types-D_R_2 2 ) ; 0x2
(define ew_intelligence_types-D_R_20 20 ) ; 0x14
(define ew_intelligence_types-D_R_21 21 ) ; 0x15
(define ew_intelligence_types-D_R_22 22 ) ; 0x16
(define ew_intelligence_types-D_R_23 23 ) ; 0x17
(define ew_intelligence_types-D_R_24 24 ) ; 0x18
(define ew_intelligence_types-D_R_25 25 ) ; 0x19
(define ew_intelligence_types-D_R_26 26 ) ; 0x1a
(define ew_intelligence_types-D_R_27 27 ) ; 0x1b
(define ew_intelligence_types-D_R_28 28 ) ; 0x1c
(define ew_intelligence_types-D_R_29 29 ) ; 0x1d
(define ew_intelligence_types-D_R_3 3 ) ; 0x3
(define ew_intelligence_types-D_R_30 30 ) ; 0x1e
(define ew_intelligence_types-D_R_31 31 ) ; 0x1f
(define ew_intelligence_types-D_R_4 4 ) ; 0x4
(define ew_intelligence_types-D_R_5 5 ) ; 0x5
(define ew_intelligence_types-D_R_6 6 ) ; 0x6
(define ew_intelligence_types-D_R_7 7 ) ; 0x7
(define ew_intelligence_types-D_R_8 8 ) ; 0x8
(define ew_intelligence_types-D_R_9 9 ) ; 0x9
(define ew_intelligence_types-Dead_in_Water_Subm_subsurf_current_activity 16 ) ; 0x10
(define ew_intelligence_types-Dead_in_Water_Surf_subsurf_current_activity 15 ) ; 0xf
(define ew_intelligence_types-Dead_in_Water_surf_current_activity 15 ) ; 0xf
(define ew_intelligence_types-Decoy_surf_current_activity 16 ) ; 0x10
(define ew_intelligence_types-Denmark 34 ) ; 0x22
(define ew_intelligence_types-Departing_subsurf_current_activity 17 ) ; 0x11
(define ew_intelligence_types-Departing_surf_current_activity 17 ) ; 0x11
(define ew_intelligence_types-Dispersal_air_current_activity 24 ) ; 0x18
(define ew_intelligence_types-Dominican_Republic 97 ) ; 0x61
(define ew_intelligence_types-ECCM_air_current_activity 27 ) ; 0x1b
(define ew_intelligence_types-ECCM_surf_current_activity 18 ) ; 0x12
(define ew_intelligence_types-ECM 9 ) ; 0x9
(define ew_intelligence_types-ECM_site_general 32 ) ; 0x20
(define ew_intelligence_types-ECM_site_land_general 4 ) ; 0x4
(define ew_intelligence_types-ECM_surf_current_activity 8 ) ; 0x8
(define ew_intelligence_types-ESM 10 ) ; 0xa
(define ew_intelligence_types-ESM_SIGINT_surf_current_activity 20 ) ; 0x14
(define ew_intelligence_types-ESM_subsurf_current_activity 19 ) ; 0x13
(define ew_intelligence_types-Egypt 61 ) ; 0x3d
(define ew_intelligence_types-Electronic_subsurface_mission 7 ) ; 0x7
(define ew_intelligence_types-Electronic_surface_mission 8 ) ; 0x8
(define ew_intelligence_types-En_Route_air_current_activity 12 ) ; 0xc
(define ew_intelligence_types-En_Route_land_current_activity 12 ) ; 0xc
(define ew_intelligence_types-En_Route_subsurf_current_activity 18 ) ; 0x12
(define ew_intelligence_types-En_Route_surf_current_activity 19 ) ; 0x13
(define ew_intelligence_types-Ethiopia 70 ) ; 0x46
(define ew_intelligence_types-Evasion_subsurf_current_activity 14 ) ; 0xe
(define ew_intelligence_types-Evasion_surf_current_activity 9 ) ; 0x9
(define ew_intelligence_types-F104_bomber_attack_specific 46 ) ; 0x2e
(define ew_intelligence_types-F104_interceptor_specific 46 ) ; 0x2e
(define ew_intelligence_types-F14 43 ) ; 0x2b
(define ew_intelligence_types-F15 44 ) ; 0x2c
(define ew_intelligence_types-F16_bomber_attack_specific 45 ) ; 0x2d
(define ew_intelligence_types-F16_interceptor_specific 45 ) ; 0x2d
(define ew_intelligence_types-F4_bomber_attack_specific 41 ) ; 0x29
(define ew_intelligence_types-F4_interceptor_specific 41 ) ; 0x29
(define ew_intelligence_types-F5_bomber_attack_specific 42 ) ; 0x2a
(define ew_intelligence_types-F5_interceptor_specific 42 ) ; 0x2a
(define ew_intelligence_types-FB_111 40 ) ; 0x28
(define ew_intelligence_types-FFX_1 1 ) ; 0x1
(define ew_intelligence_types-FFX_10 10 ) ; 0xa
(define ew_intelligence_types-FFX_11 11 ) ; 0xb
(define ew_intelligence_types-FFX_12 12 ) ; 0xc
(define ew_intelligence_types-FFX_13 13 ) ; 0xd
(define ew_intelligence_types-FFX_14 14 ) ; 0xe
(define ew_intelligence_types-FFX_15 15 ) ; 0xf
(define ew_intelligence_types-FFX_16 16 ) ; 0x10
(define ew_intelligence_types-FFX_17 17 ) ; 0x11
(define ew_intelligence_types-FFX_18 18 ) ; 0x12
(define ew_intelligence_types-FFX_19 19 ) ; 0x13
(define ew_intelligence_types-FFX_2 2 ) ; 0x2
(define ew_intelligence_types-FFX_20 20 ) ; 0x14
(define ew_intelligence_types-FFX_21 21 ) ; 0x15
(define ew_intelligence_types-FFX_22 22 ) ; 0x16
(define ew_intelligence_types-FFX_23 23 ) ; 0x17
(define ew_intelligence_types-FFX_24 24 ) ; 0x18
(define ew_intelligence_types-FFX_25 25 ) ; 0x19
(define ew_intelligence_types-FFX_26 26 ) ; 0x1a
(define ew_intelligence_types-FFX_27 27 ) ; 0x1b
(define ew_intelligence_types-FFX_28 28 ) ; 0x1c
(define ew_intelligence_types-FFX_29 29 ) ; 0x1d
(define ew_intelligence_types-FFX_3 3 ) ; 0x3
(define ew_intelligence_types-FFX_30 30 ) ; 0x1e
(define ew_intelligence_types-FFX_31 31 ) ; 0x1f
(define ew_intelligence_types-FFX_4 4 ) ; 0x4
(define ew_intelligence_types-FFX_5 5 ) ; 0x5
(define ew_intelligence_types-FFX_6 6 ) ; 0x6
(define ew_intelligence_types-FFX_7 7 ) ; 0x7
(define ew_intelligence_types-FFX_8 8 ) ; 0x8
(define ew_intelligence_types-FFX_9 9 ) ; 0x9
(define ew_intelligence_types-FRG 36 ) ; 0x24
(define ew_intelligence_types-FSH_1 1 ) ; 0x1
(define ew_intelligence_types-FSH_10 10 ) ; 0xa
(define ew_intelligence_types-FSH_11 11 ) ; 0xb
(define ew_intelligence_types-FSH_12 12 ) ; 0xc
(define ew_intelligence_types-FSH_13 13 ) ; 0xd
(define ew_intelligence_types-FSH_14 14 ) ; 0xe
(define ew_intelligence_types-FSH_15 15 ) ; 0xf
(define ew_intelligence_types-FSH_16 16 ) ; 0x10
(define ew_intelligence_types-FSH_17 17 ) ; 0x11
(define ew_intelligence_types-FSH_18 18 ) ; 0x12
(define ew_intelligence_types-FSH_19 19 ) ; 0x13
(define ew_intelligence_types-FSH_2 2 ) ; 0x2
(define ew_intelligence_types-FSH_20 20 ) ; 0x14
(define ew_intelligence_types-FSH_21 21 ) ; 0x15
(define ew_intelligence_types-FSH_22 22 ) ; 0x16
(define ew_intelligence_types-FSH_23 23 ) ; 0x17
(define ew_intelligence_types-FSH_24 24 ) ; 0x18
(define ew_intelligence_types-FSH_25 25 ) ; 0x19
(define ew_intelligence_types-FSH_26 26 ) ; 0x1a
(define ew_intelligence_types-FSH_27 27 ) ; 0x1b
(define ew_intelligence_types-FSH_28 28 ) ; 0x1c
(define ew_intelligence_types-FSH_29 29 ) ; 0x1d
(define ew_intelligence_types-FSH_3 3 ) ; 0x3
(define ew_intelligence_types-FSH_30 30 ) ; 0x1e
(define ew_intelligence_types-FSH_31 31 ) ; 0x1f
(define ew_intelligence_types-FSH_4 4 ) ; 0x4
(define ew_intelligence_types-FSH_5 5 ) ; 0x5
(define ew_intelligence_types-FSH_6 6 ) ; 0x6
(define ew_intelligence_types-FSH_7 7 ) ; 0x7
(define ew_intelligence_types-FSH_8 8 ) ; 0x8
(define ew_intelligence_types-FSH_9 9 ) ; 0x9
(define ew_intelligence_types-FTR_BA_1 1 ) ; 0x1
(define ew_intelligence_types-FTR_BA_10 10 ) ; 0xa
(define ew_intelligence_types-FTR_BA_11 11 ) ; 0xb
(define ew_intelligence_types-FTR_BA_12 12 ) ; 0xc
(define ew_intelligence_types-FTR_BA_13 13 ) ; 0xd
(define ew_intelligence_types-FTR_BA_14 14 ) ; 0xe
(define ew_intelligence_types-FTR_BA_15 15 ) ; 0xf
(define ew_intelligence_types-FTR_BA_16 16 ) ; 0x10
(define ew_intelligence_types-FTR_BA_17 17 ) ; 0x11
(define ew_intelligence_types-FTR_BA_18 18 ) ; 0x12
(define ew_intelligence_types-FTR_BA_19 19 ) ; 0x13
(define ew_intelligence_types-FTR_BA_2 2 ) ; 0x2
(define ew_intelligence_types-FTR_BA_20 20 ) ; 0x14
(define ew_intelligence_types-FTR_BA_21 21 ) ; 0x15
(define ew_intelligence_types-FTR_BA_22 22 ) ; 0x16
(define ew_intelligence_types-FTR_BA_23 23 ) ; 0x17
(define ew_intelligence_types-FTR_BA_24 24 ) ; 0x18
(define ew_intelligence_types-FTR_BA_25 25 ) ; 0x19
(define ew_intelligence_types-FTR_BA_26 26 ) ; 0x1a
(define ew_intelligence_types-FTR_BA_27 27 ) ; 0x1b
(define ew_intelligence_types-FTR_BA_28 28 ) ; 0x1c
(define ew_intelligence_types-FTR_BA_29 29 ) ; 0x1d
(define ew_intelligence_types-FTR_BA_3 3 ) ; 0x3
(define ew_intelligence_types-FTR_BA_30 30 ) ; 0x1e
(define ew_intelligence_types-FTR_BA_31 31 ) ; 0x1f
(define ew_intelligence_types-FTR_BA_4 4 ) ; 0x4
(define ew_intelligence_types-FTR_BA_5 5 ) ; 0x5
(define ew_intelligence_types-FTR_BA_6 6 ) ; 0x6
(define ew_intelligence_types-FTR_BA_7 7 ) ; 0x7
(define ew_intelligence_types-FTR_BA_8 8 ) ; 0x8
(define ew_intelligence_types-FTR_BA_9 9 ) ; 0x9
(define ew_intelligence_types-Finland 37 ) ; 0x25
(define ew_intelligence_types-Fire_B_subsurf_current_activity 7 ) ; 0x7
(define ew_intelligence_types-Fire_control_track_surf_current_activity 5 ) ; 0x5
(define ew_intelligence_types-Fire_subsurf_current_activity 5 ) ; 0x5
(define ew_intelligence_types-Fishing_surf_current_activity 25 ) ; 0x19
(define ew_intelligence_types-Flush_air_current_activity 25 ) ; 0x19
(define ew_intelligence_types-France 35 ) ; 0x23
(define ew_intelligence_types-GCI_site_general 31 ) ; 0x1f
(define ew_intelligence_types-GCI_site_land_general 3 ) ; 0x3
(define ew_intelligence_types-GDR 54 ) ; 0x36
(define ew_intelligence_types-Greece 38 ) ; 0x26
(define ew_intelligence_types-Gun_firing_surf_current_activity 3 ) ; 0x3
(define ew_intelligence_types-HH_3 36 ) ; 0x24
(define ew_intelligence_types-HH_53 35 ) ; 0x23
(define ew_intelligence_types-HL_1 1 ) ; 0x1
(define ew_intelligence_types-HL_10 10 ) ; 0xa
(define ew_intelligence_types-HL_11 11 ) ; 0xb
(define ew_intelligence_types-HL_12 12 ) ; 0xc
(define ew_intelligence_types-HL_13 13 ) ; 0xd
(define ew_intelligence_types-HL_14 14 ) ; 0xe
(define ew_intelligence_types-HL_15 15 ) ; 0xf
(define ew_intelligence_types-HL_16 16 ) ; 0x10
(define ew_intelligence_types-HL_17 17 ) ; 0x11
(define ew_intelligence_types-HL_18 18 ) ; 0x12
(define ew_intelligence_types-HL_19 19 ) ; 0x13
(define ew_intelligence_types-HL_2 2 ) ; 0x2
(define ew_intelligence_types-HL_20 20 ) ; 0x14
(define ew_intelligence_types-HL_21 21 ) ; 0x15
(define ew_intelligence_types-HL_22 22 ) ; 0x16
(define ew_intelligence_types-HL_23 23 ) ; 0x17
(define ew_intelligence_types-HL_24 24 ) ; 0x18
(define ew_intelligence_types-HL_25 25 ) ; 0x19
(define ew_intelligence_types-HL_26 26 ) ; 0x1a
(define ew_intelligence_types-HL_27 27 ) ; 0x1b
(define ew_intelligence_types-HL_28 28 ) ; 0x1c
(define ew_intelligence_types-HL_29 29 ) ; 0x1d
(define ew_intelligence_types-HL_3 3 ) ; 0x3
(define ew_intelligence_types-HL_30 30 ) ; 0x1e
(define ew_intelligence_types-HL_31 31 ) ; 0x1f
(define ew_intelligence_types-HL_4 4 ) ; 0x4
(define ew_intelligence_types-HL_5 5 ) ; 0x5
(define ew_intelligence_types-HL_6 6 ) ; 0x6
(define ew_intelligence_types-HL_7 7 ) ; 0x7
(define ew_intelligence_types-HL_8 8 ) ; 0x8
(define ew_intelligence_types-HL_9 9 ) ; 0x9
(define ew_intelligence_types-H_1B 35 ) ; 0x23
(define ew_intelligence_types-Harassing_surf_current_activity 26 ) ; 0x1a
(define ew_intelligence_types-Hungary 55 ) ; 0x37
(define ew_intelligence_types-IL_18 35 ) ; 0x23
(define ew_intelligence_types-IL_28 36 ) ; 0x24
(define ew_intelligence_types-IL_38 47 ) ; 0x2f
(define ew_intelligence_types-INT_FTR_1 1 ) ; 0x1
(define ew_intelligence_types-INT_FTR_10 10 ) ; 0xa
(define ew_intelligence_types-INT_FTR_11 11 ) ; 0xb
(define ew_intelligence_types-INT_FTR_12 12 ) ; 0xc
(define ew_intelligence_types-INT_FTR_13 13 ) ; 0xd
(define ew_intelligence_types-INT_FTR_14 14 ) ; 0xe
(define ew_intelligence_types-INT_FTR_15 15 ) ; 0xf
(define ew_intelligence_types-INT_FTR_16 16 ) ; 0x10
(define ew_intelligence_types-INT_FTR_17 17 ) ; 0x11
(define ew_intelligence_types-INT_FTR_18 18 ) ; 0x12
(define ew_intelligence_types-INT_FTR_19 19 ) ; 0x13
(define ew_intelligence_types-INT_FTR_2 2 ) ; 0x2
(define ew_intelligence_types-INT_FTR_20 20 ) ; 0x14
(define ew_intelligence_types-INT_FTR_21 21 ) ; 0x15
(define ew_intelligence_types-INT_FTR_22 22 ) ; 0x16
(define ew_intelligence_types-INT_FTR_23 23 ) ; 0x17
(define ew_intelligence_types-INT_FTR_24 24 ) ; 0x18
(define ew_intelligence_types-INT_FTR_25 25 ) ; 0x19
(define ew_intelligence_types-INT_FTR_26 26 ) ; 0x1a
(define ew_intelligence_types-INT_FTR_27 27 ) ; 0x1b
(define ew_intelligence_types-INT_FTR_28 28 ) ; 0x1c
(define ew_intelligence_types-INT_FTR_29 29 ) ; 0x1d
(define ew_intelligence_types-INT_FTR_3 3 ) ; 0x3
(define ew_intelligence_types-INT_FTR_30 30 ) ; 0x1e
(define ew_intelligence_types-INT_FTR_31 31 ) ; 0x1f
(define ew_intelligence_types-INT_FTR_4 4 ) ; 0x4
(define ew_intelligence_types-INT_FTR_5 5 ) ; 0x5
(define ew_intelligence_types-INT_FTR_6 6 ) ; 0x6
(define ew_intelligence_types-INT_FTR_7 7 ) ; 0x7
(define ew_intelligence_types-INT_FTR_8 8 ) ; 0x8
(define ew_intelligence_types-INT_FTR_9 9 ) ; 0x9
(define ew_intelligence_types-Icebreaking_surf_current_activity 28 ) ; 0x1c
(define ew_intelligence_types-Iceland 39 ) ; 0x27
(define ew_intelligence_types-India 74 ) ; 0x4a
(define ew_intelligence_types-Intel_Collection_surf_current_activity 29 ) ; 0x1d
(define ew_intelligence_types-Interdiction 3 ) ; 0x3
(define ew_intelligence_types-Intruder_surf_current_activity 30 ) ; 0x1e
(define ew_intelligence_types-Investigating_air_current_activity 1 ) ; 0x1
(define ew_intelligence_types-Investigating_land_current_activity 1 ) ; 0x1
(define ew_intelligence_types-Iran 62 ) ; 0x3e
(define ew_intelligence_types-Iraq 63 ) ; 0x3f
(define ew_intelligence_types-Ireland 40 ) ; 0x28
(define ew_intelligence_types-Israel 64 ) ; 0x40
(define ew_intelligence_types-Italy 41 ) ; 0x29
(define ew_intelligence_types-Jamming_Acoustic_surf_current_activity 11 ) ; 0xb
(define ew_intelligence_types-Jamming_Comm_air_current_activity 22 ) ; 0x16
(define ew_intelligence_types-Jamming_Comm_land_current_activity 22 ) ; 0x16
(define ew_intelligence_types-Jamming_FSC_AI_air_current_activity 20 ) ; 0x14
(define ew_intelligence_types-Jamming_FSC_AI_land_current_activity 20 ) ; 0x14
(define ew_intelligence_types-Jamming_Gen_air_current_activity 18 ) ; 0x12
(define ew_intelligence_types-Jamming_Gen_land_current_activity 18 ) ; 0x12
(define ew_intelligence_types-Jamming_IFF_SIF_air_current_activity 21 ) ; 0x15
(define ew_intelligence_types-Jamming_IFF_SIF_land_current_activity 21 ) ; 0x15
(define ew_intelligence_types-Jamming_Radar_air_current_activity 19 ) ; 0x13
(define ew_intelligence_types-Jamming_Radar_land_current_activity 19 ) ; 0x13
(define ew_intelligence_types-Japan 84 ) ; 0x54
(define ew_intelligence_types-Jordan 65 ) ; 0x41
(define ew_intelligence_types-KA_25 32 ) ; 0x20
(define ew_intelligence_types-KFIR 36 ) ; 0x24
(define ew_intelligence_types-Korea_North 82 ) ; 0x52
(define ew_intelligence_types-Korea_South 83 ) ; 0x53
(define ew_intelligence_types-LAND_TBD10_land_current_activity 61 ) ; 0x3d
(define ew_intelligence_types-LAND_TBD11_land_current_activity 62 ) ; 0x3e
(define ew_intelligence_types-LAND_TBD1_land_current_activity 52 ) ; 0x34
(define ew_intelligence_types-LAND_TBD2_land_current_activity 53 ) ; 0x35
(define ew_intelligence_types-LAND_TBD3_land_current_activity 54 ) ; 0x36
(define ew_intelligence_types-LAND_TBD4_land_current_activity 55 ) ; 0x37
(define ew_intelligence_types-LAND_TBD5_land_current_activity 56 ) ; 0x38
(define ew_intelligence_types-LAND_TBD6_land_current_activity 57 ) ; 0x39
(define ew_intelligence_types-LAND_TBD7_land_current_activity 58 ) ; 0x3a
(define ew_intelligence_types-LAND_TBD8_land_current_activity 59 ) ; 0x3b
(define ew_intelligence_types-LAND_TBD9_land_current_activity 60 ) ; 0x3c
(define ew_intelligence_types-LAND_TBD_land_current_activity 51 ) ; 0x33
(define ew_intelligence_types-L_1011 43 ) ; 0x2b
(define ew_intelligence_types-Laos 77 ) ; 0x4d
(define ew_intelligence_types-Lebanon 66 ) ; 0x42
(define ew_intelligence_types-Liberia 71 ) ; 0x47
(define ew_intelligence_types-Libya 72 ) ; 0x48
(define ew_intelligence_types-MBCA 34 ) ; 0x22
(define ew_intelligence_types-MEDEVAC 17 ) ; 0x11
(define ew_intelligence_types-MER_1 1 ) ; 0x1
(define ew_intelligence_types-MER_10 10 ) ; 0xa
(define ew_intelligence_types-MER_11 11 ) ; 0xb
(define ew_intelligence_types-MER_12 12 ) ; 0xc
(define ew_intelligence_types-MER_13 13 ) ; 0xd
(define ew_intelligence_types-MER_14 14 ) ; 0xe
(define ew_intelligence_types-MER_15 15 ) ; 0xf
(define ew_intelligence_types-MER_16 16 ) ; 0x10
(define ew_intelligence_types-MER_17 17 ) ; 0x11
(define ew_intelligence_types-MER_18 18 ) ; 0x12
(define ew_intelligence_types-MER_19 19 ) ; 0x13
(define ew_intelligence_types-MER_2 2 ) ; 0x2
(define ew_intelligence_types-MER_20 20 ) ; 0x14
(define ew_intelligence_types-MER_21 21 ) ; 0x15
(define ew_intelligence_types-MER_22 22 ) ; 0x16
(define ew_intelligence_types-MER_23 23 ) ; 0x17
(define ew_intelligence_types-MER_24 24 ) ; 0x18
(define ew_intelligence_types-MER_25 25 ) ; 0x19
(define ew_intelligence_types-MER_26 26 ) ; 0x1a
(define ew_intelligence_types-MER_27 27 ) ; 0x1b
(define ew_intelligence_types-MER_28 28 ) ; 0x1c
(define ew_intelligence_types-MER_29 29 ) ; 0x1d
(define ew_intelligence_types-MER_3 3 ) ; 0x3
(define ew_intelligence_types-MER_30 30 ) ; 0x1e
(define ew_intelligence_types-MER_31 31 ) ; 0x1f
(define ew_intelligence_types-MER_4 4 ) ; 0x4
(define ew_intelligence_types-MER_5 5 ) ; 0x5
(define ew_intelligence_types-MER_6 6 ) ; 0x6
(define ew_intelligence_types-MER_7 7 ) ; 0x7
(define ew_intelligence_types-MER_8 8 ) ; 0x8
(define ew_intelligence_types-MER_9 9 ) ; 0x9
(define ew_intelligence_types-MH_4 32 ) ; 0x20
(define ew_intelligence_types-MIG_15_17_bomber_attack_specific 32 ) ; 0x20
(define ew_intelligence_types-MIG_15_17_interceptor_specific 32 ) ; 0x20
(define ew_intelligence_types-MIG_19_bomber_attack_specific 33 ) ; 0x21
(define ew_intelligence_types-MIG_19_interceptor_specific 33 ) ; 0x21
(define ew_intelligence_types-MIG_21 34 ) ; 0x22
(define ew_intelligence_types-MIG_23_bomber_attack_specific 35 ) ; 0x23
(define ew_intelligence_types-MIG_23_interceptor_specific 35 ) ; 0x23
(define ew_intelligence_types-MIG_25 36 ) ; 0x24
(define ew_intelligence_types-MIRAGE_III 47 ) ; 0x2f
(define ew_intelligence_types-MIRAGE_IV 48 ) ; 0x30
(define ew_intelligence_types-MI_10 34 ) ; 0x22
(define ew_intelligence_types-MI_24 33 ) ; 0x21
(define ew_intelligence_types-MI_6 33 ) ; 0x21
(define ew_intelligence_types-MOSS 41 ) ; 0x29
(define ew_intelligence_types-MWX_1 1 ) ; 0x1
(define ew_intelligence_types-MWX_10 10 ) ; 0xa
(define ew_intelligence_types-MWX_11 11 ) ; 0xb
(define ew_intelligence_types-MWX_12 12 ) ; 0xc
(define ew_intelligence_types-MWX_13 13 ) ; 0xd
(define ew_intelligence_types-MWX_14 14 ) ; 0xe
(define ew_intelligence_types-MWX_15 15 ) ; 0xf
(define ew_intelligence_types-MWX_16 16 ) ; 0x10
(define ew_intelligence_types-MWX_17 17 ) ; 0x11
(define ew_intelligence_types-MWX_18 18 ) ; 0x12
(define ew_intelligence_types-MWX_19 19 ) ; 0x13
(define ew_intelligence_types-MWX_2 2 ) ; 0x2
(define ew_intelligence_types-MWX_20 20 ) ; 0x14
(define ew_intelligence_types-MWX_21 21 ) ; 0x15
(define ew_intelligence_types-MWX_22 22 ) ; 0x16
(define ew_intelligence_types-MWX_23 23 ) ; 0x17
(define ew_intelligence_types-MWX_24 24 ) ; 0x18
(define ew_intelligence_types-MWX_25 25 ) ; 0x19
(define ew_intelligence_types-MWX_26 26 ) ; 0x1a
(define ew_intelligence_types-MWX_27 27 ) ; 0x1b
(define ew_intelligence_types-MWX_28 28 ) ; 0x1c
(define ew_intelligence_types-MWX_29 29 ) ; 0x1d
(define ew_intelligence_types-MWX_3 3 ) ; 0x3
(define ew_intelligence_types-MWX_30 30 ) ; 0x1e
(define ew_intelligence_types-MWX_31 31 ) ; 0x1f
(define ew_intelligence_types-MWX_4 4 ) ; 0x4
(define ew_intelligence_types-MWX_5 5 ) ; 0x5
(define ew_intelligence_types-MWX_6 6 ) ; 0x6
(define ew_intelligence_types-MWX_7 7 ) ; 0x7
(define ew_intelligence_types-MWX_8 8 ) ; 0x8
(define ew_intelligence_types-MWX_9 9 ) ; 0x9
(define ew_intelligence_types-M_4 33 ) ; 0x21
(define ew_intelligence_types-Marshalling_air_current_activity 15 ) ; 0xf
(define ew_intelligence_types-Mexico 92 ) ; 0x5c
(define ew_intelligence_types-Mine_Hunting_surf_current_activity 31 ) ; 0x1f
(define ew_intelligence_types-Mine_Laying 18 ) ; 0x12
(define ew_intelligence_types-Mine_Laying_subsurf_current_activity 13 ) ; 0xd
(define ew_intelligence_types-Mine_Laying_surf_current_activity 4 ) ; 0x4
(define ew_intelligence_types-Mine_Sweep_surf_current_activity 32 ) ; 0x20
(define ew_intelligence_types-Mine_Sweeping 19 ) ; 0x13
(define ew_intelligence_types-Mine_subsurface_mission 5 ) ; 0x5
(define ew_intelligence_types-Mine_surface_mission 7 ) ; 0x7
(define ew_intelligence_types-Missile_Ops_Live_B_subsurf_current_activity 12 ) ; 0xc
(define ew_intelligence_types-Missile_Ops_Live_subsurf_current_activity 6 ) ; 0x6
(define ew_intelligence_types-Missile_Ops_Simul_subsurf_current_activity 4 ) ; 0x4
(define ew_intelligence_types-Missile_Ops_subsurf_current_activity 2 ) ; 0x2
(define ew_intelligence_types-Missile_TDB_51 51 ) ; 0x33
(define ew_intelligence_types-Missile_TDB_52 52 ) ; 0x34
(define ew_intelligence_types-Missile_TDB_53 53 ) ; 0x35
(define ew_intelligence_types-Missile_TDB_54 54 ) ; 0x36
(define ew_intelligence_types-Missile_TDB_55 55 ) ; 0x37
(define ew_intelligence_types-Missile_TDB_56 56 ) ; 0x38
(define ew_intelligence_types-Missile_TDB_57 57 ) ; 0x39
(define ew_intelligence_types-Missile_TDB_58 58 ) ; 0x3a
(define ew_intelligence_types-Missile_TDB_59 59 ) ; 0x3b
(define ew_intelligence_types-Missile_TDB_60 60 ) ; 0x3c
(define ew_intelligence_types-Missile_TDB_61 61 ) ; 0x3d
(define ew_intelligence_types-Missile_TDB_62 62 ) ; 0x3e
(define ew_intelligence_types-Missile_surf_current_activity 2 ) ; 0x2
(define ew_intelligence_types-NATO 31 ) ; 0x1f
(define ew_intelligence_types-NGFS_surf_current_activity 33 ) ; 0x21
(define ew_intelligence_types-NP 1 ) ; 0x1
(define ew_intelligence_types-NT 1 ) ; 0x1
(define ew_intelligence_types-Near_Weapon_Release_air_current_activity 6 ) ; 0x6
(define ew_intelligence_types-Near_Weapons_Release_land_current_activity 6 ) ; 0x6
(define ew_intelligence_types-Netherlands 42 ) ; 0x2a
(define ew_intelligence_types-Neutral_Observer_subsurf_current_activity 21 ) ; 0x15
(define ew_intelligence_types-Neutral_Observer_surf_current_activity 34 ) ; 0x22
(define ew_intelligence_types-New_Zealand 87 ) ; 0x57
(define ew_intelligence_types-Non_Combatant 5 ) ; 0x5
(define ew_intelligence_types-Non_Combatant_subsurface_mission 8 ) ; 0x8
(define ew_intelligence_types-Non_Combatant_surface_mission 9 ) ; 0x9
(define ew_intelligence_types-Norway 43 ) ; 0x2b
(define ew_intelligence_types-OH_58 38 ) ; 0x26
(define ew_intelligence_types-OTH_1 1 ) ; 0x1
(define ew_intelligence_types-OTH_10 10 ) ; 0xa
(define ew_intelligence_types-OTH_11 11 ) ; 0xb
(define ew_intelligence_types-OTH_12 12 ) ; 0xc
(define ew_intelligence_types-OTH_13 13 ) ; 0xd
(define ew_intelligence_types-OTH_14 14 ) ; 0xe
(define ew_intelligence_types-OTH_15 15 ) ; 0xf
(define ew_intelligence_types-OTH_16 16 ) ; 0x10
(define ew_intelligence_types-OTH_17 17 ) ; 0x11
(define ew_intelligence_types-OTH_18 18 ) ; 0x12
(define ew_intelligence_types-OTH_19 19 ) ; 0x13
(define ew_intelligence_types-OTH_2 2 ) ; 0x2
(define ew_intelligence_types-OTH_20 20 ) ; 0x14
(define ew_intelligence_types-OTH_21 21 ) ; 0x15
(define ew_intelligence_types-OTH_22 22 ) ; 0x16
(define ew_intelligence_types-OTH_23 23 ) ; 0x17
(define ew_intelligence_types-OTH_24 24 ) ; 0x18
(define ew_intelligence_types-OTH_25 25 ) ; 0x19
(define ew_intelligence_types-OTH_26 26 ) ; 0x1a
(define ew_intelligence_types-OTH_27 27 ) ; 0x1b
(define ew_intelligence_types-OTH_28 28 ) ; 0x1c
(define ew_intelligence_types-OTH_29 29 ) ; 0x1d
(define ew_intelligence_types-OTH_3 3 ) ; 0x3
(define ew_intelligence_types-OTH_30 30 ) ; 0x1e
(define ew_intelligence_types-OTH_31 31 ) ; 0x1f
(define ew_intelligence_types-OTH_4 4 ) ; 0x4
(define ew_intelligence_types-OTH_5 5 ) ; 0x5
(define ew_intelligence_types-OTH_6 6 ) ; 0x6
(define ew_intelligence_types-OTH_7 7 ) ; 0x7
(define ew_intelligence_types-OTH_8 8 ) ; 0x8
(define ew_intelligence_types-OTH_9 9 ) ; 0x9
(define ew_intelligence_types-Ocean_Patrol 6 ) ; 0x6
(define ew_intelligence_types-Oceonographic_surf_current_activity 27 ) ; 0x1b
(define ew_intelligence_types-On_Station_air_current_activity 13 ) ; 0xd
(define ew_intelligence_types-On_Station_subsurf_current_activity 22 ) ; 0x16
(define ew_intelligence_types-On_Station_surf_current_activity 35 ) ; 0x23
(define ew_intelligence_types-P 0 ) ; 0x0
(define ew_intelligence_types-PIRAZ_Unit_surf_current_activity 37 ) ; 0x25
(define ew_intelligence_types-PPX_1 1 ) ; 0x1
(define ew_intelligence_types-PPX_10 10 ) ; 0xa
(define ew_intelligence_types-PPX_11 11 ) ; 0xb
(define ew_intelligence_types-PPX_12 12 ) ; 0xc
(define ew_intelligence_types-PPX_13 13 ) ; 0xd
(define ew_intelligence_types-PPX_14 14 ) ; 0xe
(define ew_intelligence_types-PPX_15 15 ) ; 0xf
(define ew_intelligence_types-PPX_16 16 ) ; 0x10
(define ew_intelligence_types-PPX_17 17 ) ; 0x11
(define ew_intelligence_types-PPX_18 18 ) ; 0x12
(define ew_intelligence_types-PPX_19 19 ) ; 0x13
(define ew_intelligence_types-PPX_2 2 ) ; 0x2
(define ew_intelligence_types-PPX_20 20 ) ; 0x14
(define ew_intelligence_types-PPX_21 21 ) ; 0x15
(define ew_intelligence_types-PPX_22 22 ) ; 0x16
(define ew_intelligence_types-PPX_23 23 ) ; 0x17
(define ew_intelligence_types-PPX_24 24 ) ; 0x18
(define ew_intelligence_types-PPX_25 25 ) ; 0x19
(define ew_intelligence_types-PPX_26 26 ) ; 0x1a
(define ew_intelligence_types-PPX_27 27 ) ; 0x1b
(define ew_intelligence_types-PPX_28 28 ) ; 0x1c
(define ew_intelligence_types-PPX_29 29 ) ; 0x1d
(define ew_intelligence_types-PPX_3 3 ) ; 0x3
(define ew_intelligence_types-PPX_30 30 ) ; 0x1e
(define ew_intelligence_types-PPX_31 31 ) ; 0x1f
(define ew_intelligence_types-PPX_4 4 ) ; 0x4
(define ew_intelligence_types-PPX_5 5 ) ; 0x5
(define ew_intelligence_types-PPX_6 6 ) ; 0x6
(define ew_intelligence_types-PPX_7 7 ) ; 0x7
(define ew_intelligence_types-PPX_8 8 ) ; 0x8
(define ew_intelligence_types-PPX_9 9 ) ; 0x9
(define ew_intelligence_types-PTRL_1 1 ) ; 0x1
(define ew_intelligence_types-PTRL_10 10 ) ; 0xa
(define ew_intelligence_types-PTRL_11 11 ) ; 0xb
(define ew_intelligence_types-PTRL_12 12 ) ; 0xc
(define ew_intelligence_types-PTRL_13 13 ) ; 0xd
(define ew_intelligence_types-PTRL_14 14 ) ; 0xe
(define ew_intelligence_types-PTRL_15 15 ) ; 0xf
(define ew_intelligence_types-PTRL_16 16 ) ; 0x10
(define ew_intelligence_types-PTRL_17 17 ) ; 0x11
(define ew_intelligence_types-PTRL_18 18 ) ; 0x12
(define ew_intelligence_types-PTRL_19 19 ) ; 0x13
(define ew_intelligence_types-PTRL_2 2 ) ; 0x2
(define ew_intelligence_types-PTRL_20 20 ) ; 0x14
(define ew_intelligence_types-PTRL_21 21 ) ; 0x15
(define ew_intelligence_types-PTRL_22 22 ) ; 0x16
(define ew_intelligence_types-PTRL_23 23 ) ; 0x17
(define ew_intelligence_types-PTRL_24 24 ) ; 0x18
(define ew_intelligence_types-PTRL_25 25 ) ; 0x19
(define ew_intelligence_types-PTRL_26 26 ) ; 0x1a
(define ew_intelligence_types-PTRL_27 27 ) ; 0x1b
(define ew_intelligence_types-PTRL_28 28 ) ; 0x1c
(define ew_intelligence_types-PTRL_29 29 ) ; 0x1d
(define ew_intelligence_types-PTRL_3 3 ) ; 0x3
(define ew_intelligence_types-PTRL_30 30 ) ; 0x1e
(define ew_intelligence_types-PTRL_31 31 ) ; 0x1f
(define ew_intelligence_types-PTRL_4 4 ) ; 0x4
(define ew_intelligence_types-PTRL_5 5 ) ; 0x5
(define ew_intelligence_types-PTRL_6 6 ) ; 0x6
(define ew_intelligence_types-PTRL_7 7 ) ; 0x7
(define ew_intelligence_types-PTRL_8 8 ) ; 0x8
(define ew_intelligence_types-PTRL_9 9 ) ; 0x9
(define ew_intelligence_types-Pakistan 75 ) ; 0x4b
(define ew_intelligence_types-Panama 93 ) ; 0x5d
(define ew_intelligence_types-Patrol_subsurf_current_activity 23 ) ; 0x17
(define ew_intelligence_types-Patrol_surf_current_activity 36 ) ; 0x24
(define ew_intelligence_types-Peru 94 ) ; 0x5e
(define ew_intelligence_types-Philippines 85 ) ; 0x55
(define ew_intelligence_types-Poland 56 ) ; 0x38
(define ew_intelligence_types-Portugal 44 ) ; 0x2c
(define ew_intelligence_types-RECCE 4 ) ; 0x4
(define ew_intelligence_types-RTB_air_current_activity 16 ) ; 0x10
(define ew_intelligence_types-R_R_surf_current_activity 24 ) ; 0x18
(define ew_intelligence_types-Radar_IR_Lock_air_current_activity 5 ) ; 0x5
(define ew_intelligence_types-Radar_Lock_land_current_activity 5 ) ; 0x5
(define ew_intelligence_types-Refuel 11 ) ; 0xb
(define ew_intelligence_types-Refueling_air_current_activity 17 ) ; 0x11
(define ew_intelligence_types-Relief_subsurf_current_activity 24 ) ; 0x18
(define ew_intelligence_types-Relieving_surf_current_activity 39 ) ; 0x27
(define ew_intelligence_types-Rendezvous_air_current_activity 14 ) ; 0xe
(define ew_intelligence_types-Rendezvous_surf_current_activity 12 ) ; 0xc
(define ew_intelligence_types-Repairing_surf_current_activity 38 ) ; 0x26
(define ew_intelligence_types-Replenish_Screen_subsurf_current_activity 25 ) ; 0x19
(define ew_intelligence_types-Replenishing_surf_current_activity 40 ) ; 0x28
(define ew_intelligence_types-Romania 57 ) ; 0x39
(define ew_intelligence_types-SAM_site_general 29 ) ; 0x1d
(define ew_intelligence_types-SAM_site_land_general 1 ) ; 0x1
(define ew_intelligence_types-SAR 16 ) ; 0x10
(define ew_intelligence_types-SSBX_1 1 ) ; 0x1
(define ew_intelligence_types-SSBX_10 10 ) ; 0xa
(define ew_intelligence_types-SSBX_11 11 ) ; 0xb
(define ew_intelligence_types-SSBX_12 12 ) ; 0xc
(define ew_intelligence_types-SSBX_13 13 ) ; 0xd
(define ew_intelligence_types-SSBX_14 14 ) ; 0xe
(define ew_intelligence_types-SSBX_15 15 ) ; 0xf
(define ew_intelligence_types-SSBX_16 16 ) ; 0x10
(define ew_intelligence_types-SSBX_17 17 ) ; 0x11
(define ew_intelligence_types-SSBX_18 18 ) ; 0x12
(define ew_intelligence_types-SSBX_19 19 ) ; 0x13
(define ew_intelligence_types-SSBX_2 2 ) ; 0x2
(define ew_intelligence_types-SSBX_20 20 ) ; 0x14
(define ew_intelligence_types-SSBX_21 21 ) ; 0x15
(define ew_intelligence_types-SSBX_22 22 ) ; 0x16
(define ew_intelligence_types-SSBX_23 23 ) ; 0x17
(define ew_intelligence_types-SSBX_24 24 ) ; 0x18
(define ew_intelligence_types-SSBX_25 25 ) ; 0x19
(define ew_intelligence_types-SSBX_26 26 ) ; 0x1a
(define ew_intelligence_types-SSBX_27 27 ) ; 0x1b
(define ew_intelligence_types-SSBX_28 28 ) ; 0x1c
(define ew_intelligence_types-SSBX_29 29 ) ; 0x1d
(define ew_intelligence_types-SSBX_3 3 ) ; 0x3
(define ew_intelligence_types-SSBX_30 30 ) ; 0x1e
(define ew_intelligence_types-SSBX_31 31 ) ; 0x1f
(define ew_intelligence_types-SSBX_4 4 ) ; 0x4
(define ew_intelligence_types-SSBX_5 5 ) ; 0x5
(define ew_intelligence_types-SSBX_6 6 ) ; 0x6
(define ew_intelligence_types-SSBX_7 7 ) ; 0x7
(define ew_intelligence_types-SSBX_8 8 ) ; 0x8
(define ew_intelligence_types-SSBX_9 9 ) ; 0x9
(define ew_intelligence_types-SSGX_1 1 ) ; 0x1
(define ew_intelligence_types-SSGX_10 10 ) ; 0xa
(define ew_intelligence_types-SSGX_11 11 ) ; 0xb
(define ew_intelligence_types-SSGX_12 12 ) ; 0xc
(define ew_intelligence_types-SSGX_13 13 ) ; 0xd
(define ew_intelligence_types-SSGX_14 14 ) ; 0xe
(define ew_intelligence_types-SSGX_15 15 ) ; 0xf
(define ew_intelligence_types-SSGX_16 16 ) ; 0x10
(define ew_intelligence_types-SSGX_17 17 ) ; 0x11
(define ew_intelligence_types-SSGX_18 18 ) ; 0x12
(define ew_intelligence_types-SSGX_19 19 ) ; 0x13
(define ew_intelligence_types-SSGX_2 2 ) ; 0x2
(define ew_intelligence_types-SSGX_20 20 ) ; 0x14
(define ew_intelligence_types-SSGX_21 21 ) ; 0x15
(define ew_intelligence_types-SSGX_22 22 ) ; 0x16
(define ew_intelligence_types-SSGX_23 23 ) ; 0x17
(define ew_intelligence_types-SSGX_24 24 ) ; 0x18
(define ew_intelligence_types-SSGX_25 25 ) ; 0x19
(define ew_intelligence_types-SSGX_26 26 ) ; 0x1a
(define ew_intelligence_types-SSGX_27 27 ) ; 0x1b
(define ew_intelligence_types-SSGX_28 28 ) ; 0x1c
(define ew_intelligence_types-SSGX_29 29 ) ; 0x1d
(define ew_intelligence_types-SSGX_3 3 ) ; 0x3
(define ew_intelligence_types-SSGX_30 30 ) ; 0x1e
(define ew_intelligence_types-SSGX_31 31 ) ; 0x1f
(define ew_intelligence_types-SSGX_4 4 ) ; 0x4
(define ew_intelligence_types-SSGX_5 5 ) ; 0x5
(define ew_intelligence_types-SSGX_6 6 ) ; 0x6
(define ew_intelligence_types-SSGX_7 7 ) ; 0x7
(define ew_intelligence_types-SSGX_8 8 ) ; 0x8
(define ew_intelligence_types-SSGX_9 9 ) ; 0x9
(define ew_intelligence_types-SSM_site_general 37 ) ; 0x25
(define ew_intelligence_types-SSM_site_land_general 9 ) ; 0x9
(define ew_intelligence_types-SSX_1 1 ) ; 0x1
(define ew_intelligence_types-SSX_10 10 ) ; 0xa
(define ew_intelligence_types-SSX_11 11 ) ; 0xb
(define ew_intelligence_types-SSX_12 12 ) ; 0xc
(define ew_intelligence_types-SSX_13 13 ) ; 0xd
(define ew_intelligence_types-SSX_14 14 ) ; 0xe
(define ew_intelligence_types-SSX_15 15 ) ; 0xf
(define ew_intelligence_types-SSX_16 16 ) ; 0x10
(define ew_intelligence_types-SSX_17 17 ) ; 0x11
(define ew_intelligence_types-SSX_18 18 ) ; 0x12
(define ew_intelligence_types-SSX_19 19 ) ; 0x13
(define ew_intelligence_types-SSX_2 2 ) ; 0x2
(define ew_intelligence_types-SSX_20 20 ) ; 0x14
(define ew_intelligence_types-SSX_21 21 ) ; 0x15
(define ew_intelligence_types-SSX_22 22 ) ; 0x16
(define ew_intelligence_types-SSX_23 23 ) ; 0x17
(define ew_intelligence_types-SSX_24 24 ) ; 0x18
(define ew_intelligence_types-SSX_25 25 ) ; 0x19
(define ew_intelligence_types-SSX_26 26 ) ; 0x1a
(define ew_intelligence_types-SSX_27 27 ) ; 0x1b
(define ew_intelligence_types-SSX_28 28 ) ; 0x1c
(define ew_intelligence_types-SSX_29 29 ) ; 0x1d
(define ew_intelligence_types-SSX_3 3 ) ; 0x3
(define ew_intelligence_types-SSX_30 30 ) ; 0x1e
(define ew_intelligence_types-SSX_31 31 ) ; 0x1f
(define ew_intelligence_types-SSX_4 4 ) ; 0x4
(define ew_intelligence_types-SSX_5 5 ) ; 0x5
(define ew_intelligence_types-SSX_6 6 ) ; 0x6
(define ew_intelligence_types-SSX_7 7 ) ; 0x7
(define ew_intelligence_types-SSX_8 8 ) ; 0x8
(define ew_intelligence_types-SSX_9 9 ) ; 0x9
(define ew_intelligence_types-SUB_SURF_TBD10_subsurf_current_activity 61 ) ; 0x3d
(define ew_intelligence_types-SUB_SURF_TBD11_subsurf_current_activity 62 ) ; 0x3e
(define ew_intelligence_types-SUB_SURF_TBD1_subsurf_current_activity 52 ) ; 0x34
(define ew_intelligence_types-SUB_SURF_TBD2_subsurf_current_activity 53 ) ; 0x35
(define ew_intelligence_types-SUB_SURF_TBD3_subsurf_current_activity 54 ) ; 0x36
(define ew_intelligence_types-SUB_SURF_TBD4_subsurf_current_activity 55 ) ; 0x37
(define ew_intelligence_types-SUB_SURF_TBD5_subsurf_current_activity 56 ) ; 0x38
(define ew_intelligence_types-SUB_SURF_TBD6_subsurf_current_activity 57 ) ; 0x39
(define ew_intelligence_types-SUB_SURF_TBD7_subsurf_current_activity 58 ) ; 0x3a
(define ew_intelligence_types-SUB_SURF_TBD8_subsurf_current_activity 59 ) ; 0x3b
(define ew_intelligence_types-SUB_SURF_TBD9_subsurf_current_activity 60 ) ; 0x3c
(define ew_intelligence_types-SUB_SURF_TBD_subsurf_current_activity 51 ) ; 0x33
(define ew_intelligence_types-SUP_1 1 ) ; 0x1
(define ew_intelligence_types-SUP_10 10 ) ; 0xa
(define ew_intelligence_types-SUP_11 11 ) ; 0xb
(define ew_intelligence_types-SUP_12 12 ) ; 0xc
(define ew_intelligence_types-SUP_13 13 ) ; 0xd
(define ew_intelligence_types-SUP_14 14 ) ; 0xe
(define ew_intelligence_types-SUP_15 15 ) ; 0xf
(define ew_intelligence_types-SUP_16 16 ) ; 0x10
(define ew_intelligence_types-SUP_17 17 ) ; 0x11
(define ew_intelligence_types-SUP_18 18 ) ; 0x12
(define ew_intelligence_types-SUP_19 19 ) ; 0x13
(define ew_intelligence_types-SUP_2 2 ) ; 0x2
(define ew_intelligence_types-SUP_20 20 ) ; 0x14
(define ew_intelligence_types-SUP_21 21 ) ; 0x15
(define ew_intelligence_types-SUP_22 22 ) ; 0x16
(define ew_intelligence_types-SUP_23 23 ) ; 0x17
(define ew_intelligence_types-SUP_24 24 ) ; 0x18
(define ew_intelligence_types-SUP_25 25 ) ; 0x19
(define ew_intelligence_types-SUP_26 26 ) ; 0x1a
(define ew_intelligence_types-SUP_27 27 ) ; 0x1b
(define ew_intelligence_types-SUP_28 28 ) ; 0x1c
(define ew_intelligence_types-SUP_29 29 ) ; 0x1d
(define ew_intelligence_types-SUP_3 3 ) ; 0x3
(define ew_intelligence_types-SUP_30 30 ) ; 0x1e
(define ew_intelligence_types-SUP_31 31 ) ; 0x1f
(define ew_intelligence_types-SUP_4 4 ) ; 0x4
(define ew_intelligence_types-SUP_5 5 ) ; 0x5
(define ew_intelligence_types-SUP_6 6 ) ; 0x6
(define ew_intelligence_types-SUP_7 7 ) ; 0x7
(define ew_intelligence_types-SUP_8 8 ) ; 0x8
(define ew_intelligence_types-SUP_9 9 ) ; 0x9
(define ew_intelligence_types-SURFACE_TBD10_surf_current_activity 61 ) ; 0x3d
(define ew_intelligence_types-SURFACE_TBD11_surf_current_activity 62 ) ; 0x3e
(define ew_intelligence_types-SURFACE_TBD1_surf_current_activity 52 ) ; 0x34
(define ew_intelligence_types-SURFACE_TBD2_surf_current_activity 53 ) ; 0x35
(define ew_intelligence_types-SURFACE_TBD3_surf_current_activity 54 ) ; 0x36
(define ew_intelligence_types-SURFACE_TBD4_surf_current_activity 55 ) ; 0x37
(define ew_intelligence_types-SURFACE_TBD5_surf_current_activity 56 ) ; 0x38
(define ew_intelligence_types-SURFACE_TBD6_surf_current_activity 57 ) ; 0x39
(define ew_intelligence_types-SURFACE_TBD7_surf_current_activity 58 ) ; 0x3a
(define ew_intelligence_types-SURFACE_TBD8_surf_current_activity 59 ) ; 0x3b
(define ew_intelligence_types-SURFACE_TBD9_surf_current_activity 60 ) ; 0x3c
(define ew_intelligence_types-SURFACE_TBD_surf_current_activity 51 ) ; 0x33
(define ew_intelligence_types-SU_15 38 ) ; 0x26
(define ew_intelligence_types-SU_17 38 ) ; 0x26
(define ew_intelligence_types-SU_19 39 ) ; 0x27
(define ew_intelligence_types-SU_7_bomber_attack_specific 37 ) ; 0x25
(define ew_intelligence_types-SU_7_interceptor_specific 37 ) ; 0x25
(define ew_intelligence_types-Saudi_Arabia 67 ) ; 0x43
(define ew_intelligence_types-Scramble_air_current_activity 11 ) ; 0xb
(define ew_intelligence_types-Screen_surf_current_activity 42 ) ; 0x2a
(define ew_intelligence_types-Search_Attack_surf_current_activity 41 ) ; 0x29
(define ew_intelligence_types-Shadow_subsurf_current_activity 27 ) ; 0x1b
(define ew_intelligence_types-Shadow_surf_current_activity 44 ) ; 0x2c
(define ew_intelligence_types-Simul_subsurf_current_activity 11 ) ; 0xb
(define ew_intelligence_types-Sincking_surf_current_activity 43 ) ; 0x2b
(define ew_intelligence_types-Sinking_subsurf_current_activity 26 ) ; 0x1a
(define ew_intelligence_types-South_Africa 73 ) ; 0x49
(define ew_intelligence_types-Spain 45 ) ; 0x2d
(define ew_intelligence_types-Special_subsurface_mission 6 ) ; 0x6
(define ew_intelligence_types-Special_surface_mission 10 ) ; 0xa
(define ew_intelligence_types-Strike_missile_mission 4 ) ; 0x4
(define ew_intelligence_types-Strike_subsurface_mission 1 ) ; 0x1
(define ew_intelligence_types-Strike_surface_mission 5 ) ; 0x5
(define ew_intelligence_types-Subsurface_TDB_51 51 ) ; 0x33
(define ew_intelligence_types-Subsurface_TDB_52 52 ) ; 0x34
(define ew_intelligence_types-Subsurface_TDB_53 53 ) ; 0x35
(define ew_intelligence_types-Subsurface_TDB_54 54 ) ; 0x36
(define ew_intelligence_types-Subsurface_TDB_55 55 ) ; 0x37
(define ew_intelligence_types-Subsurface_TDB_56 56 ) ; 0x38
(define ew_intelligence_types-Subsurface_TDB_57 57 ) ; 0x39
(define ew_intelligence_types-Subsurface_TDB_58 58 ) ; 0x3a
(define ew_intelligence_types-Subsurface_TDB_59 59 ) ; 0x3b
(define ew_intelligence_types-Subsurface_TDB_60 60 ) ; 0x3c
(define ew_intelligence_types-Subsurface_TDB_61 61 ) ; 0x3d
(define ew_intelligence_types-Subsurface_TDB_62 62 ) ; 0x3e
(define ew_intelligence_types-Successful_air_current_activity 8 ) ; 0x8
(define ew_intelligence_types-Successful_land_current_activity 8 ) ; 0x8
(define ew_intelligence_types-Surface_TDB_51 51 ) ; 0x33
(define ew_intelligence_types-Surface_TDB_52 52 ) ; 0x34
(define ew_intelligence_types-Surface_TDB_53 53 ) ; 0x35
(define ew_intelligence_types-Surface_TDB_54 54 ) ; 0x36
(define ew_intelligence_types-Surface_TDB_55 55 ) ; 0x37
(define ew_intelligence_types-Surface_TDB_56 56 ) ; 0x38
(define ew_intelligence_types-Surface_TDB_57 57 ) ; 0x39
(define ew_intelligence_types-Surface_TDB_58 58 ) ; 0x3a
(define ew_intelligence_types-Surface_TDB_59 59 ) ; 0x3b
(define ew_intelligence_types-Surface_TDB_60 60 ) ; 0x3c
(define ew_intelligence_types-Surface_TDB_61 61 ) ; 0x3d
(define ew_intelligence_types-Surface_TDB_62 62 ) ; 0x3e
(define ew_intelligence_types-Sweden 46 ) ; 0x2e
(define ew_intelligence_types-Switzerland 47 ) ; 0x2f
(define ew_intelligence_types-Syria 68 ) ; 0x44
(define ew_intelligence_types-T 0 ) ; 0x0
(define ew_intelligence_types-TA_28 44 ) ; 0x2c
(define ew_intelligence_types-TORPEDO 3 ) ; 0x3
(define ew_intelligence_types-TRAINER 48 ) ; 0x30
(define ew_intelligence_types-TRIDENT 36 ) ; 0x24
(define ew_intelligence_types-TU_104 33 ) ; 0x21
(define ew_intelligence_types-TU_128 40 ) ; 0x28
(define ew_intelligence_types-TU_144 34 ) ; 0x22
(define ew_intelligence_types-TU_16_air_support_specific 34 ) ; 0x22
(define ew_intelligence_types-TU_16_bomber_specific 34 ) ; 0x22
(define ew_intelligence_types-TU_22 35 ) ; 0x23
(define ew_intelligence_types-TU_28 40 ) ; 0x28
(define ew_intelligence_types-TU_40 32 ) ; 0x20
(define ew_intelligence_types-TU_95_air_support_specific 32 ) ; 0x20
(define ew_intelligence_types-TU_95_bomber_specific 32 ) ; 0x20
(define ew_intelligence_types-Targetting_subsurf_current_activity 1 ) ; 0x1
(define ew_intelligence_types-Thailand 78 ) ; 0x4e
(define ew_intelligence_types-Torpedo_Ops_B_subsurf_current_activity 10 ) ; 0xa
(define ew_intelligence_types-Torpedo_Ops_subsurf_current_activity 8 ) ; 0x8
(define ew_intelligence_types-Towing_subsurf_current_activity 29 ) ; 0x1d
(define ew_intelligence_types-Towing_surf_current_activity 46 ) ; 0x2e
(define ew_intelligence_types-Troop_Ops_subsurf_current_activity 28 ) ; 0x1c
(define ew_intelligence_types-Troop_Ops_surf_current_activity 45 ) ; 0x2d
(define ew_intelligence_types-Turkey 48 ) ; 0x30
(define ew_intelligence_types-UH_1 37 ) ; 0x25
(define ew_intelligence_types-UK 49 ) ; 0x31
(define ew_intelligence_types-USA 60 ) ; 0x3c
(define ew_intelligence_types-USSR 30 ) ; 0x1e
(define ew_intelligence_types-Under_Tow_subsurf_current_activity 30 ) ; 0x1e
(define ew_intelligence_types-Under_tow_surf_current_activity 47 ) ; 0x2f
(define ew_intelligence_types-United_Nations 98 ) ; 0x62
(define ew_intelligence_types-Unspec_1_subsurf_current_activity 9 ) ; 0x9
(define ew_intelligence_types-Unspec_subsurf_current_activity 3 ) ; 0x3
(define ew_intelligence_types-Unsuccessful_air_current_activity 9 ) ; 0x9
(define ew_intelligence_types-Unsuccessful_land_current_activity 9 ) ; 0x9
(define ew_intelligence_types-Venezuela 95 ) ; 0x5f
(define ew_intelligence_types-Vietnam 79 ) ; 0x4f
(define ew_intelligence_types-Visual_Contact_land_current_activity 4 ) ; 0x4
(define ew_intelligence_types-Visual_contact_air_current_activity 4 ) ; 0x4
(define ew_intelligence_types-Warsaw_Pact 29 ) ; 0x1d
(define ew_intelligence_types-Weapon_Release_air_current_activity 7 ) ; 0x7
(define ew_intelligence_types-Weapon_Release_land_current_activity 7 ) ; 0x7
(define ew_intelligence_types-Weapons_Armed_land_current_activity 3 ) ; 0x3
(define ew_intelligence_types-YAK_27 39 ) ; 0x27
(define ew_intelligence_types-YAK_28 37 ) ; 0x25
(define ew_intelligence_types-YAK_28P 39 ) ; 0x27
(define ew_intelligence_types-Yugoslavia 58 ) ; 0x3a
(define ew_intelligence_types-able_to_perform_mission_operational_status 1 ) ; 0x1
(define ew_intelligence_types-air_base_general 33 ) ; 0x21
(define ew_intelligence_types-air_base_land_general 5 ) ; 0x5
(define ew_intelligence_types-air_category 1 ) ; 0x1
(define ew_intelligence_types-aircraft_sec_surf_ampl_carrier_general 14 ) ; 0xe
(define ew_intelligence_types-aircraft_sec_surf_ampl_carrier_surf_general 1 ) ; 0x1
(define ew_intelligence_types-anti_air_general 42 ) ; 0x2a
(define ew_intelligence_types-anti_air_missile_general 1 ) ; 0x1
(define ew_intelligence_types-anti_sub_general 44 ) ; 0x2c
(define ew_intelligence_types-anti_sub_missile_general 3 ) ; 0x3
(define ew_intelligence_types-anti_surf_general 43 ) ; 0x2b
(define ew_intelligence_types-anti_surf_missile_general 2 ) ; 0x2
(define ew_intelligence_types-attack_general 23 ) ; 0x17
(define ew_intelligence_types-attack_helo_air_general 5 ) ; 0x5
(define ew_intelligence_types-attack_helo_general 8 ) ; 0x8
(define ew_intelligence_types-attack_sub_general 1 ) ; 0x1
(define ew_intelligence_types-ballistic_missile_launcher_sub_general 3 ) ; 0x3
(define ew_intelligence_types-ballistic_msl_general 25 ) ; 0x19
(define ew_intelligence_types-bomber_air_general 3 ) ; 0x3
(define ew_intelligence_types-bomber_attack_air_general 2 ) ; 0x2
(define ew_intelligence_types-bomber_attack_general 5 ) ; 0x5
(define ew_intelligence_types-bomber_general 6 ) ; 0x6
(define ew_intelligence_types-civil_air_general 8 ) ; 0x8
(define ew_intelligence_types-civil_general 11 ) ; 0xb
(define ew_intelligence_types-command_center_general 36 ) ; 0x24
(define ew_intelligence_types-command_center_land_general 8 ) ; 0x8
(define ew_intelligence_types-convoy_general 41 ) ; 0x29
(define ew_intelligence_types-convoy_land_general 13 ) ; 0xd
(define ew_intelligence_types-cruise_missile_launcher_sub_general 2 ) ; 0x2
(define ew_intelligence_types-cruise_msl_general 24 ) ; 0x18
(define ew_intelligence_types-cruiser_general 16 ) ; 0x10
(define ew_intelligence_types-cruiser_surf_general 3 ) ; 0x3
(define ew_intelligence_types-decoy 4 ) ; 0x4
(define ew_intelligence_types-diesel_sub_general 27 ) ; 0x1b
(define ew_intelligence_types-diesel_sub_sub_general 5 ) ; 0x5
(define ew_intelligence_types-diesel_submarine 1 ) ; 0x1
(define ew_intelligence_types-diesel_submarine_1 2 ) ; 0x2
(define ew_intelligence_types-diesel_submarine_2 3 ) ; 0x3
(define ew_intelligence_types-diesel_submarine_3 4 ) ; 0x4
(define ew_intelligence_types-drone_air_general 6 ) ; 0x6
(define ew_intelligence_types-drone_general 9 ) ; 0x9
(define ew_intelligence_types-dummy_general 35 ) ; 0x23
(define ew_intelligence_types-dummy_land_general 7 ) ; 0x7
(define ew_intelligence_types-field_artillery_site_general 39 ) ; 0x27
(define ew_intelligence_types-field_artillery_site_land_general 11 ) ; 0xb
(define ew_intelligence_types-fighters_have_scrambled_operational_status 3 ) ; 0x3
(define ew_intelligence_types-fish_group 6 ) ; 0x6
(define ew_intelligence_types-frigate_general 17 ) ; 0x11
(define ew_intelligence_types-frigate_surf_general 4 ) ; 0x4
(define ew_intelligence_types-helo_air_general 4 ) ; 0x4
(define ew_intelligence_types-helo_general 7 ) ; 0x7
(define ew_intelligence_types-illegal_100 100 ) ; 0x64
(define ew_intelligence_types-illegal_101 101 ) ; 0x65
(define ew_intelligence_types-illegal_102 102 ) ; 0x66
(define ew_intelligence_types-illegal_103 103 ) ; 0x67
(define ew_intelligence_types-illegal_104 104 ) ; 0x68
(define ew_intelligence_types-illegal_105 105 ) ; 0x69
(define ew_intelligence_types-illegal_106 106 ) ; 0x6a
(define ew_intelligence_types-illegal_107 107 ) ; 0x6b
(define ew_intelligence_types-illegal_108 108 ) ; 0x6c
(define ew_intelligence_types-illegal_109 109 ) ; 0x6d
(define ew_intelligence_types-illegal_110 110 ) ; 0x6e
(define ew_intelligence_types-illegal_111 111 ) ; 0x6f
(define ew_intelligence_types-illegal_112 112 ) ; 0x70
(define ew_intelligence_types-illegal_113 113 ) ; 0x71
(define ew_intelligence_types-illegal_114 114 ) ; 0x72
(define ew_intelligence_types-illegal_115 115 ) ; 0x73
(define ew_intelligence_types-illegal_116 116 ) ; 0x74
(define ew_intelligence_types-illegal_117 117 ) ; 0x75
(define ew_intelligence_types-illegal_118 118 ) ; 0x76
(define ew_intelligence_types-illegal_119 119 ) ; 0x77
(define ew_intelligence_types-illegal_120 120 ) ; 0x78
(define ew_intelligence_types-illegal_121 121 ) ; 0x79
(define ew_intelligence_types-illegal_122 122 ) ; 0x7a
(define ew_intelligence_types-illegal_123 123 ) ; 0x7b
(define ew_intelligence_types-illegal_124 124 ) ; 0x7c
(define ew_intelligence_types-illegal_125 125 ) ; 0x7d
(define ew_intelligence_types-illegal_126 126 ) ; 0x7e
(define ew_intelligence_types-illegal_127 127 ) ; 0x7f
(define ew_intelligence_types-interceptor_air_general 1 ) ; 0x1
(define ew_intelligence_types-interceptor_general 4 ) ; 0x4
(define ew_intelligence_types-knuckle 7 ) ; 0x7
(define ew_intelligence_types-land_category 4 ) ; 0x4
(define ew_intelligence_types-low_fuel_state_operational_status 9 ) ; 0x9
(define ew_intelligence_types-mine_other_korea_sub_specific 5 ) ; 0x5
(define ew_intelligence_types-mine_warfare_general 18 ) ; 0x12
(define ew_intelligence_types-mine_warfare_surf_general 6 ) ; 0x6
(define ew_intelligence_types-missile_category 5 ) ; 0x5
(define ew_intelligence_types-no_stat_99 99 ) ; 0x63
(define ew_intelligence_types-no_statement_AEW_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_air_current_activity 0 ) ; 0x0
(define ew_intelligence_types-no_statement_air_general 0 ) ; 0x0
(define ew_intelligence_types-no_statement_air_mission 0 ) ; 0x0
(define ew_intelligence_types-no_statement_air_patrol_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_air_support_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_aircraft_sec_surf_ampl_carrier_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_attack_helo_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_attack_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_ballistic_msl_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_bomber_attack_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_bomber_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_category 0 ) ; 0x0
(define ew_intelligence_types-no_statement_civil_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_cruise_msl_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_cruiser_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_diesel_sub_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_drone_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_frigate_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_general 3 ) ; 0x3
(define ew_intelligence_types-no_statement_helo_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_interceptor_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_land_current_activity 0 ) ; 0x0
(define ew_intelligence_types-no_statement_land_general 0 ) ; 0x0
(define ew_intelligence_types-no_statement_land_mission 0 ) ; 0x0
(define ew_intelligence_types-no_statement_mine_warfare_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_missile_general 0 ) ; 0x0
(define ew_intelligence_types-no_statement_missile_mission 0 ) ; 0x0
(define ew_intelligence_types-no_statement_nationallity_alliance 0 ) ; 0x0
(define ew_intelligence_types-no_statement_nuclear_sub_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_operational_status 0 ) ; 0x0
(define ew_intelligence_types-no_statement_other_korea_sub_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_other_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_pri_surf_ampl_amphibious_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_sec_surf_ampl_destroyer_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_sec_surf_ampl_fishing_boat_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_sec_surf_ampl_merchant_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_sub_general 0 ) ; 0x0
(define ew_intelligence_types-no_statement_subsurf_current_activity 0 ) ; 0x0
(define ew_intelligence_types-no_statement_subsurface_mission 0 ) ; 0x0
(define ew_intelligence_types-no_statement_surf_current_activity 0 ) ; 0x0
(define ew_intelligence_types-no_statement_surf_general 0 ) ; 0x0
(define ew_intelligence_types-no_statement_surface_mission 0 ) ; 0x0
(define ew_intelligence_types-no_statement_surface_patrol_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_surface_support_specific 0 ) ; 0x0
(define ew_intelligence_types-no_statement_tanker_specific 0 ) ; 0x0
(define ew_intelligence_types-ns_1 0 ) ; 0x0
(define ew_intelligence_types-ns_10 9 ) ; 0x9
(define ew_intelligence_types-ns_11 10 ) ; 0xa
(define ew_intelligence_types-ns_12 11 ) ; 0xb
(define ew_intelligence_types-ns_13 12 ) ; 0xc
(define ew_intelligence_types-ns_14 13 ) ; 0xd
(define ew_intelligence_types-ns_15 14 ) ; 0xe
(define ew_intelligence_types-ns_16 15 ) ; 0xf
(define ew_intelligence_types-ns_17 16 ) ; 0x10
(define ew_intelligence_types-ns_18 17 ) ; 0x11
(define ew_intelligence_types-ns_19 18 ) ; 0x12
(define ew_intelligence_types-ns_2 1 ) ; 0x1
(define ew_intelligence_types-ns_20 19 ) ; 0x13
(define ew_intelligence_types-ns_21 20 ) ; 0x14
(define ew_intelligence_types-ns_22 21 ) ; 0x15
(define ew_intelligence_types-ns_23 22 ) ; 0x16
(define ew_intelligence_types-ns_24 23 ) ; 0x17
(define ew_intelligence_types-ns_25 24 ) ; 0x18
(define ew_intelligence_types-ns_26 25 ) ; 0x19
(define ew_intelligence_types-ns_27 26 ) ; 0x1a
(define ew_intelligence_types-ns_28 27 ) ; 0x1b
(define ew_intelligence_types-ns_29 28 ) ; 0x1c
(define ew_intelligence_types-ns_3 2 ) ; 0x2
(define ew_intelligence_types-ns_30 29 ) ; 0x1d
(define ew_intelligence_types-ns_31 30 ) ; 0x1e
(define ew_intelligence_types-ns_32 31 ) ; 0x1f
(define ew_intelligence_types-ns_33 32 ) ; 0x20
(define ew_intelligence_types-ns_34 33 ) ; 0x21
(define ew_intelligence_types-ns_35 34 ) ; 0x22
(define ew_intelligence_types-ns_36 35 ) ; 0x23
(define ew_intelligence_types-ns_37 36 ) ; 0x24
(define ew_intelligence_types-ns_38 37 ) ; 0x25
(define ew_intelligence_types-ns_39 38 ) ; 0x26
(define ew_intelligence_types-ns_4 3 ) ; 0x3
(define ew_intelligence_types-ns_40 39 ) ; 0x27
(define ew_intelligence_types-ns_41 40 ) ; 0x28
(define ew_intelligence_types-ns_42 41 ) ; 0x29
(define ew_intelligence_types-ns_43 42 ) ; 0x2a
(define ew_intelligence_types-ns_44 43 ) ; 0x2b
(define ew_intelligence_types-ns_45 44 ) ; 0x2c
(define ew_intelligence_types-ns_46 45 ) ; 0x2d
(define ew_intelligence_types-ns_47 46 ) ; 0x2e
(define ew_intelligence_types-ns_48 47 ) ; 0x2f
(define ew_intelligence_types-ns_49 48 ) ; 0x30
(define ew_intelligence_types-ns_5 4 ) ; 0x4
(define ew_intelligence_types-ns_50 49 ) ; 0x31
(define ew_intelligence_types-ns_51 50 ) ; 0x32
(define ew_intelligence_types-ns_52 51 ) ; 0x33
(define ew_intelligence_types-ns_53 52 ) ; 0x34
(define ew_intelligence_types-ns_54 53 ) ; 0x35
(define ew_intelligence_types-ns_55 54 ) ; 0x36
(define ew_intelligence_types-ns_56 55 ) ; 0x37
(define ew_intelligence_types-ns_57 56 ) ; 0x38
(define ew_intelligence_types-ns_58 57 ) ; 0x39
(define ew_intelligence_types-ns_59 58 ) ; 0x3a
(define ew_intelligence_types-ns_6 5 ) ; 0x5
(define ew_intelligence_types-ns_60 59 ) ; 0x3b
(define ew_intelligence_types-ns_61 60 ) ; 0x3c
(define ew_intelligence_types-ns_62 61 ) ; 0x3d
(define ew_intelligence_types-ns_63 62 ) ; 0x3e
(define ew_intelligence_types-ns_7 6 ) ; 0x6
(define ew_intelligence_types-ns_8 7 ) ; 0x7
(define ew_intelligence_types-ns_9 8 ) ; 0x8
(define ew_intelligence_types-nuclear_sub_general 26 ) ; 0x1a
(define ew_intelligence_types-nuclear_sub_sub_general 4 ) ; 0x4
(define ew_intelligence_types-nuclear_submarine 1 ) ; 0x1
(define ew_intelligence_types-nuclear_submarine_1 2 ) ; 0x2
(define ew_intelligence_types-nuclear_submarine_2 3 ) ; 0x3
(define ew_intelligence_types-nuclear_submarine_3 4 ) ; 0x4
(define ew_intelligence_types-nuclear_submarine_4 5 ) ; 0x5
(define ew_intelligence_types-nuclear_submarine_5 6 ) ; 0x6
(define ew_intelligence_types-nuclear_submarine_6 7 ) ; 0x7
(define ew_intelligence_types-nuclear_submarine_7 8 ) ; 0x8
(define ew_intelligence_types-other_AEW_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_air_general 14 ) ; 0xe
(define ew_intelligence_types-other_air_patrol_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_air_support_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_aircraft_sec_surf_ampl_carrier_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_attack_helo_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_attack_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_ballistic_msl_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_bomber_attack_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_bomber_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_civil_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_cruise_msl_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_cruiser_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_diesel_sub_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_drone_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_frigate_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_general 2 ) ; 0x2
(define ew_intelligence_types-other_helo_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_interceptor_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_korea_sub_general 28 ) ; 0x1c
(define ew_intelligence_types-other_korea_sub_sub_general 6 ) ; 0x6
(define ew_intelligence_types-other_land_general 14 ) ; 0xe
(define ew_intelligence_types-other_mine_warfare_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_missile_general 14 ) ; 0xe
(define ew_intelligence_types-other_nuclear_sub_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_other_korea_sub_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_other_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_pri_surf_ampl_amphibious_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_sec_surf_ampl_destroyer_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_sec_surf_ampl_fishing_boat_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_sec_surf_ampl_merchant_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_sub_general 14 ) ; 0xe
(define ew_intelligence_types-other_surf_general 14 ) ; 0xe
(define ew_intelligence_types-other_surface_patrol_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_surface_support_specific 62 ) ; 0x3e
(define ew_intelligence_types-other_tanker_specific 62 ) ; 0x3e
(define ew_intelligence_types-patrol_air_general 9 ) ; 0x9
(define ew_intelligence_types-patrol_general 12 ) ; 0xc
(define ew_intelligence_types-patrol_surface_general_surf_general 5 ) ; 0x5
(define ew_intelligence_types-point_target_general 38 ) ; 0x26
(define ew_intelligence_types-point_target_land_general 10 ) ; 0xa
(define ew_intelligence_types-pri_surf_ampl_amphibious_general 19 ) ; 0x13
(define ew_intelligence_types-pri_surf_ampl_amphibious_surf_general 7 ) ; 0x7
(define ew_intelligence_types-propulsion_unknown_submarine 1 ) ; 0x1
(define ew_intelligence_types-reset_to_no_statement_AEW_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement__air_current_activity 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_air_general 15 ) ; 0xf
(define ew_intelligence_types-reset_to_no_statement_air_mission 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_air_patrol_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_air_support_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_aircraft_sec_surf_ampl_carrier_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_attack_helo_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_attack_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_ballistic_msl_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_bomber_attack_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_bomber_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_category 7 ) ; 0x7
(define ew_intelligence_types-reset_to_no_statement_civil_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_cruise_msl_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_cruiser_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_diesel_sub_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_drone_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_frigate_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_general 1 ) ; 0x1
(define ew_intelligence_types-reset_to_no_statement_helo_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_interceptor_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_land_current_activity 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_land_general 15 ) ; 0xf
(define ew_intelligence_types-reset_to_no_statement_land_mission 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_mine_warfare_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_missile_general 15 ) ; 0xf
(define ew_intelligence_types-reset_to_no_statement_missile_mission 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_nuclear_sub_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_operational_status 15 ) ; 0xf
(define ew_intelligence_types-reset_to_no_statement_other_korea_sub_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_other_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_pri_surf_ampl_amphibious_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_sec_surf_ampl_destroyer_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_sec_surf_ampl_fishing_boat_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_sec_surf_ampl_merchant_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_sub_general 15 ) ; 0xf
(define ew_intelligence_types-reset_to_no_statement_subsurf_current_activity 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_subsurface_mission 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_surf_current_activity 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_surf_general 15 ) ; 0xf
(define ew_intelligence_types-reset_to_no_statement_surface_mission 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_surface_patrol_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_surface_support_specific 63 ) ; 0x3f
(define ew_intelligence_types-reset_to_no_statement_tanker_specific 63 ) ; 0x3f
(define ew_intelligence_types-sec_surf_ampl_destroyer_general 15 ) ; 0xf
(define ew_intelligence_types-sec_surf_ampl_destroyer_surf_general 2 ) ; 0x2
(define ew_intelligence_types-sec_surf_ampl_fishing_boat_general 21 ) ; 0x15
(define ew_intelligence_types-sec_surf_ampl_fishing_boat_surf_general 10 ) ; 0xa
(define ew_intelligence_types-sec_surf_ampl_merchant_general 22 ) ; 0x16
(define ew_intelligence_types-sec_surf_ampl_merchant_surf_general 11 ) ; 0xb
(define ew_intelligence_types-sec_surf_ampl_surfaced_submarine 2 ) ; 0x2
(define ew_intelligence_types-spare_10_air_current_activity 38 ) ; 0x26
(define ew_intelligence_types-spare_10_land_current_activity 27 ) ; 0x1b
(define ew_intelligence_types-spare_10_subsurf_current_activity 41 ) ; 0x29
(define ew_intelligence_types-spare_11_air_current_activity 39 ) ; 0x27
(define ew_intelligence_types-spare_11_land_current_activity 28 ) ; 0x1c
(define ew_intelligence_types-spare_11_subsurf_current_activity 42 ) ; 0x2a
(define ew_intelligence_types-spare_12_air_current_activity 40 ) ; 0x28
(define ew_intelligence_types-spare_12_land_current_activity 29 ) ; 0x1d
(define ew_intelligence_types-spare_12_subsurf_current_activity 43 ) ; 0x2b
(define ew_intelligence_types-spare_13_air_current_activity 41 ) ; 0x29
(define ew_intelligence_types-spare_13_land_current_activity 30 ) ; 0x1e
(define ew_intelligence_types-spare_13_subsurf_current_activity 44 ) ; 0x2c
(define ew_intelligence_types-spare_14_air_current_activity 42 ) ; 0x2a
(define ew_intelligence_types-spare_14_land_current_activity 31 ) ; 0x1f
(define ew_intelligence_types-spare_14_subsurf_current_activity 45 ) ; 0x2d
(define ew_intelligence_types-spare_15_air_current_activity 43 ) ; 0x2b
(define ew_intelligence_types-spare_15_land_current_activity 32 ) ; 0x20
(define ew_intelligence_types-spare_15_subsurf_current_activity 46 ) ; 0x2e
(define ew_intelligence_types-spare_16_air_current_activity 44 ) ; 0x2c
(define ew_intelligence_types-spare_16_land_current_activity 33 ) ; 0x21
(define ew_intelligence_types-spare_16_subsurf_current_activity 47 ) ; 0x2f
(define ew_intelligence_types-spare_17_air_current_activity 45 ) ; 0x2d
(define ew_intelligence_types-spare_17_land_current_activity 34 ) ; 0x22
(define ew_intelligence_types-spare_17_subsurf_current_activity 48 ) ; 0x30
(define ew_intelligence_types-spare_18_air_current_activity 46 ) ; 0x2e
(define ew_intelligence_types-spare_18_land_current_activity 35 ) ; 0x23
(define ew_intelligence_types-spare_18_subsurf_current_activity 49 ) ; 0x31
(define ew_intelligence_types-spare_19_air_current_activity 47 ) ; 0x2f
(define ew_intelligence_types-spare_19_land_current_activity 36 ) ; 0x24
(define ew_intelligence_types-spare_19_subsurf_current_activity 50 ) ; 0x32
(define ew_intelligence_types-spare_1_air_current_activity 29 ) ; 0x1d
(define ew_intelligence_types-spare_1_land_current_activity 13 ) ; 0xd
(define ew_intelligence_types-spare_1_operational_status 11 ) ; 0xb
(define ew_intelligence_types-spare_1_subsurf_current_activity 32 ) ; 0x20
(define ew_intelligence_types-spare_1_surf_current_activity 49 ) ; 0x31
(define ew_intelligence_types-spare_20_air_current_activity 48 ) ; 0x30
(define ew_intelligence_types-spare_20_land_current_activity 37 ) ; 0x25
(define ew_intelligence_types-spare_21_air_current_activity 49 ) ; 0x31
(define ew_intelligence_types-spare_21_land_current_activity 38 ) ; 0x26
(define ew_intelligence_types-spare_22_air_current_activity 50 ) ; 0x32
(define ew_intelligence_types-spare_22_land_current_activity 39 ) ; 0x27
(define ew_intelligence_types-spare_23_land_current_activity 40 ) ; 0x28
(define ew_intelligence_types-spare_24_land_current_activity 41 ) ; 0x29
(define ew_intelligence_types-spare_25_land_current_activity 42 ) ; 0x2a
(define ew_intelligence_types-spare_26_land_current_activity 43 ) ; 0x2b
(define ew_intelligence_types-spare_27_land_current_activity 44 ) ; 0x2c
(define ew_intelligence_types-spare_28_land_current_activity 45 ) ; 0x2d
(define ew_intelligence_types-spare_29_land_current_activity 46 ) ; 0x2e
(define ew_intelligence_types-spare_2_air_current_activity 30 ) ; 0x1e
(define ew_intelligence_types-spare_2_land_current_activity 14 ) ; 0xe
(define ew_intelligence_types-spare_2_operational_status 12 ) ; 0xc
(define ew_intelligence_types-spare_2_subsurf_current_activity 33 ) ; 0x21
(define ew_intelligence_types-spare_2_surf_current_activity 50 ) ; 0x32
(define ew_intelligence_types-spare_30_land_current_activity 47 ) ; 0x2f
(define ew_intelligence_types-spare_31_land_current_activity 48 ) ; 0x30
(define ew_intelligence_types-spare_32_land_current_activity 49 ) ; 0x31
(define ew_intelligence_types-spare_33_land_current_activity 50 ) ; 0x32
(define ew_intelligence_types-spare_3_air_current_activity 31 ) ; 0x1f
(define ew_intelligence_types-spare_3_land_current_activity 15 ) ; 0xf
(define ew_intelligence_types-spare_3_operational_status 13 ) ; 0xd
(define ew_intelligence_types-spare_3_subsurf_current_activity 34 ) ; 0x22
(define ew_intelligence_types-spare_4_air_current_activity 32 ) ; 0x20
(define ew_intelligence_types-spare_4_land_current_activity 16 ) ; 0x10
(define ew_intelligence_types-spare_4_operational_status 14 ) ; 0xe
(define ew_intelligence_types-spare_4_subsurf_current_activity 35 ) ; 0x23
(define ew_intelligence_types-spare_5_air_current_activity 33 ) ; 0x21
(define ew_intelligence_types-spare_5_land_current_activity 17 ) ; 0x11
(define ew_intelligence_types-spare_5_subsurf_current_activity 36 ) ; 0x24
(define ew_intelligence_types-spare_6_air_current_activity 34 ) ; 0x22
(define ew_intelligence_types-spare_6_land_current_activity 23 ) ; 0x17
(define ew_intelligence_types-spare_6_subsurf_current_activity 37 ) ; 0x25
(define ew_intelligence_types-spare_7_air_current_activity 35 ) ; 0x23
(define ew_intelligence_types-spare_7_land_current_activity 24 ) ; 0x18
(define ew_intelligence_types-spare_7_subsurf_current_activity 38 ) ; 0x26
(define ew_intelligence_types-spare_8_air_current_activity 36 ) ; 0x24
(define ew_intelligence_types-spare_8_land_current_activity 25 ) ; 0x19
(define ew_intelligence_types-spare_8_subsurf_current_activity 39 ) ; 0x27
(define ew_intelligence_types-spare_9_air_current_activity 37 ) ; 0x25
(define ew_intelligence_types-spare_9_land_current_activity 26 ) ; 0x1a
(define ew_intelligence_types-spare_9_subsurf_current_activity 40 ) ; 0x28
(define ew_intelligence_types-spare_air_current_activity 28 ) ; 0x1c
(define ew_intelligence_types-spare_land_current_activity 11 ) ; 0xb
(define ew_intelligence_types-spare_operational_status 10 ) ; 0xa
(define ew_intelligence_types-spare_subsurf_current_activity 31 ) ; 0x1f
(define ew_intelligence_types-spare_surf_current_activity 48 ) ; 0x30
(define ew_intelligence_types-subsurface_category 3 ) ; 0x3
(define ew_intelligence_types-support_air_general 7 ) ; 0x7
(define ew_intelligence_types-support_general 10 ) ; 0xa
(define ew_intelligence_types-support_surf_general 8 ) ; 0x8
(define ew_intelligence_types-surface_category 2 ) ; 0x2
(define ew_intelligence_types-tanker_general 20 ) ; 0x14
(define ew_intelligence_types-tanker_surf_general 9 ) ; 0x9
(define ew_intelligence_types-trap_general 34 ) ; 0x22
(define ew_intelligence_types-trap_land_general 6 ) ; 0x6
(define ew_intelligence_types-troop_concentration_general 40 ) ; 0x28
(define ew_intelligence_types-troop_concentration_land_general 12 ) ; 0xc
(define ew_intelligence_types-unable_perform_mission_due_battle_damage_operational_status 6 ) ; 0x6
(define ew_intelligence_types-unable_perform_mission_due_fuel_depletion_operational_status 7 ) ; 0x7
(define ew_intelligence_types-unable_perform_mission_due_weather_operational_status 5 ) ; 0x5
(define ew_intelligence_types-unable_perform_mission_operational_status 4 ) ; 0x4
(define ew_intelligence_types-unable_perform_mission_ordnance_depletion_operational_status 8 ) ; 0x8
(define ew_intelligence_types-undef_11_air_general_type 11 ) ; 0xb
(define ew_intelligence_types-undef_12_air_general_type 12 ) ; 0xc
(define ew_intelligence_types-undef_12_surf_general_type 12 ) ; 0xc
(define ew_intelligence_types-undef_13_air_general_type 13 ) ; 0xd
(define ew_intelligence_types-undef_13_surf_general_type 13 ) ; 0xd
(define ew_intelligence_types-undef_category 6 ) ; 0x6
(define ew_intelligence_types-undef_general 0 ) ; 0x0
(define ew_intelligence_types-weapon_system_on_alert_operational_status 2 ) ; 0x2
(define ew_intelligence_types-wreck 8 ) ; 0x8
(define system_types-ew_intelligence 34 ) ; 0x22
(define system_types-ew_intelligence_ampl 35 ) ; 0x23
