
(define  EMERGENCY      0)
(define  STOP_EMERGENCY 1)
(define  FORCETELL      2)
(define  STOP_FORCETELL 3)

(define clear_request     0)
(define difference_report 1)

(define AIRCRAFT_STATUS_KIND_AIR_GENERAL 0) 
(define AIRCRAFT_STATUE_KIND_ASW         1) 
(define AIRCRAFT_STATUE_KIND_NONE        2) 

(define ew_cancel_transmission_ew_compliance     0)
(define machine_receipt_for_order_ew_compliance  1)
(define machine_receipt_for_ackn_ew_compliance   2)
(define no_compliance_ew_compliance              3) 




(define ID_RESULT_A 0)
(define ID_RESULT_C 1) 
(define ID_RESULT_D 2) 
(define ID_RESULT_V 3) 

(define CONFLICT_REPORT_IDENTITY_AIR        0 )
(define CONFLICT_REPORT_IDENTITY_SURF       1 )
(define CONFLICT_REPORT_ENVIRONMENT         2 )
(define CONFLICT_REPORT_POSITION            3 )
(define CONFLICT_REPORT_TRACK_NUMBER        4 )
(define CONFLICT_REPORT_IFF_MODE1           5 )
(define CONFLICT_REPORT_IFF_MODE2           6 )
(define CONFLICT_REPORT_IFF_MODE3           7 )
(define CONFLICT_REPORT_IFF_MODE4_DOWNGRADE 8 )
(define CONFLICT_REPORT_IFF_MODE4_CONFLICT  9 )          

(define DIFFERENCE_REPORT_IDENTITY_AIR     0 )
(define DIFFERENCE_REPORT_IDENTITY_SURF    1 )
(define DIFFERENCE_REPORT_ENVIRONMENT      2 )
(define DIFFERENCE_REPORT_IFF_SIF          3 ) 
(define DIFFERENCE_REPORT_NONE             4 ) 

(define AUTHORIZED                 0 )
(define NOT_AUTHORIZED             1 )
(define NO_STATEMENT_AUTHORIZATION 2 )

(define AUTOMATIC_CORRELATION 0)

(define ASSIGNMENT_AUTOMATIC 0)
(define ASSIGNMENT_MANUAL    1)


(define ADMISSION_TRANSMISSION_INTERVAL_IN_SEC 1 )
(define ALL_PUS #x0007F0 )
(define AMP_SUB_NUM 5 )
(define ARCMINUTE_TO_RADIAN 2.9088820866572159615394846141477e-4)
(define ARCSECOND_TO_RADIAN 4.8481368110953599359e-6 )
(define ASW_POINT_ACOUSTIC_FIX 10)
(define ASW_POINT_NOTACK_AREA 12 )
(define CANCEL_ORDER 1 )
(define CANCEL_WATCH #x000003 )
(define CANTCO 6 )
(define CANTPRO 7 )
(define CCV_Request_Periodic_Report 0 )
(define CCV_Request_Update_And_Watch 3 )
(define CFCS_MODE_ID_TACTICAL 1 )
(define CFCS_MODE_ID_TRAIN1 2 )
(define CFCS_MODE_ID_TRAIN2 3 )
(define CHANGE_DATA_ORDER 2 )
(define CLASS_AMPL_TORPEDOCOMM_ALERT 2)
(define CLEAN_ADDRESSEE #x01FFFF )
(define CLEAN_RC #xCFFFFF )
(define CLEAN_RC_ADDRESSEE #x1FF80F )
(define CLEAN_TN2 #x000FFF )
(define COM_NOT_ALLOWED_FAILURE 1 )
(define CONFLICT 1 )
(define CONVENTIONAL_CONST #x0C0000 )
(define CU_REPORT 6 )
(define DATA_FROM_DEVICE_BYTES 20480 )
(define DATA_UPDATE_REQUEST 3 )
(define DEFAULT_AMPL 0 )
(define DLRP_60_DEGREE_LATITUDE (degree-to-radian 60))
(define DMASKM4 #x00003F )
(define DMASKM5 #x0000FF )
(define DROP_TRACK 4 )
(define DROP_TRACK_COUNT 2 )
(define DTSCTRL_BUFF_LENGTH 1024 )
(define DTSCTRL_EOM #x03 )
(define DTSCTRL_EXTRA #xFF )
(define DTSCTRL_SOM #x02 )
(define DTS_ERROR_BIT_MASK #x30000000 )
(define DTS_NOT_RESPONSE 2 )
(define DURATION_FOR_PERIODIC_PROCESSING 2000 )
(define EARTH_RADIUS 6378122.88 )
(define ECM_AMP_CLASS_SIZE 8 )
(define ECM_BROAD_CLASS_SIZE 8 )
(define EI_MASK #x00000007 )
(define EMCON_ENABLED 0 )
(define EMCON_INDEX 0 )
(define EMCON_RADIO_SILENCE 1 )
(define ESM_AMP_CLASS_SIZE 8 )
(define ESM_BROAD_CLASS_SIZE 8 )
(define EVERY_CONSOLE_ID -1 )
(define EWC #x100000 )
(define EXTENSION #x004000 )
(define Env_Cat_Air 1 )
(define Env_Cat_Subsurface 3 )
(define Env_Cat_Surface 2 )

(define ENV_CAT_AIR 1 )
(define ENV_CAT_SUBSURFACE 3 )
(define ENV_CAT_SURFACE 2 )

(define FIFTH_FRAME_OFFSET 8 )
(define FIVE_TIMES 5 )
(define FIXED_CONST #x040000 )
(define FM 6 )
(define FOURTH_FRAME_OFFSET 6 )
(define FRAME_BYTES 8 )
(define FRAME_WORDS 2 )
(define FTSW #x000000 )
(define FTSW #x100000 )
(define FUEL_TIME_NOVALUE 0 )
(define HALF_PI 1.57079632679489661923132169163975144 )
(define HAVCO 4 )
(define HEIGHTMASK #x0000FF )
(define HMASKM5 #x0000FF )
(define HUNDREAD_TIMES 100 )
(define ICU_ALL_DOMAIN 4 )
(define ICU_IPN_DOMAIN 1 )
(define IFF_CLEAR_1 1 )
(define IFF_CLEAR_1 2 )
(define IFF_CLEAR_1_2_3 0 )
(define IFF_CLEAR_2 1 )
(define IFF_CLEAR_2 4 )
(define IFF_CLEAR_3 1 )
(define IFF_CLEAR_3 6 )
(define IFF_CLEAR_4 1 )
(define IFF_CLEAR_4 3 )
(define IFF_SIF_MANAGEMENT 9 )
(define IFF_iff_mode1_FIRST 0 )
(define IFF_iff_mode1_LAST 59 )
(define IFF_iff_mode2_3_FIRST 0 )
(define IFF_iff_mode2_3_last 4095 )
(define INTERRUPT_MASK #x00000007 )
(define INVALID_DLP_IFF_MODE1 #xFFFFFFFF )
(define INVALID_DLP_IFF_MODE2 #xFFFFFFFF )
(define INVALID_DLP_IFF_MODE3 #xFFFFFFFF )
(define INVALID_DLP_IFF_MODE4 #xFFFFFFFF )
(define INVALID_FIELD_VALUE -1 )
(define INVALID_IFF_MODE -1 )
(define INVALID_TRACK_ID 0 )
(define INVALID_PU INVALID_TRACK_ID)
(define KILLO 1000.0 )
(define KNTDS_NOT_RESPONSE 4 )
(define L11_EOR 3 )
(define L11_PTR 6 )
(define L11_PTT 5 )
(define L11_PTTB 7 )
(define L11_RST 2 )
(define LABEL_NUMBER_M11B 1 )
(define LABEL_NUMBER_M11C 2 )
(define LABEL_NUMBER_M11D 3 )
(define LABEL_NUMBER_M11M 12 )
(define LABEL_NUMBER_M4A 0 )
(define LABEL_NUMBER_M4B 1 )
(define LABEL_NUMBER_M4C 2 )
(define LABEL_NUMBER_M4D 3 )
(define LABEL_NUMBER_M6A 0 )
(define LABEL_NUMBER_M6B 1 )
(define LABEL_NUMBER_M6C 2 )
(define LABEL_NUMBER_M6D 3 )
(define LABEL_NUMBER_M9A 0 )
(define LABEL_NUMBER_M9B 1 )
(define LABEL_NUMBER_M9C 2 )
(define LABEL_NUMBER_M9D 3 )
(define LABEL_NUMBER_M9E 4 )
(define LABEL_NUMBER_M9F 5 )
(define LABEL_NUMBER_M9G 6 )
(define LAN_FAILURE -1 )
(define LOCK_STRUCT_MAX_COUNT 10 )
(define LSB_7_BIT_MASK #x7F )
(define M10A 0 )
(define M10ACANTPROAMP 267 )
(define M10ACI 268 )
(define M10ALABEL 265 )
(define M10AMN 263 )
(define M10AORDER 266 )
(define M10APURUADDEE 264 )
(define M10ARC 269 )
(define M10ATN1 270 )
(define M10ATN2 271 )
(define M11BAC 327 )
(define M11BFT 326 )
(define M11BFTSW 320 )
(define M11BLABEL 318 )
(define M11BMN 317 )
(define M11BORDA 321 )
(define M11BORDB 322 )
(define M11BORDC 323 )
(define M11BORDD 324 )
(define M11BTN 319 )
(define M11BWPT 325 )
(define M11CAC 346 )
(define M11CBSW 332 )
(define M11CFUEL 347 )
(define M11CLABEL 329 )
(define M11CMN 328 )
(define M11CNAS 344 )
(define M11CNCD 337 )
(define M11CNCM 341 )
(define M11CNCT 339 )
(define M11CNPS 345 )
(define M11CNR 343 )
(define M11CNSD 338 )
(define M11CNSM 342 )
(define M11CNST 340 )
(define M11CSENSOR26 333 )
(define M11CSENSOR27 334 )
(define M11CSENSOR28 335 )
(define M11CSENSOR30 336 )
(define M11CTIME 331 )
(define M11CTN 330 )
(define M11DLABEL 349 )
(define M11DMN 348 )
(define M11DMODE1 355 )
(define M11DMODE2 354 )
(define M11DMODE3 356 )
(define M11DMODE4 352 )
(define M11DSPECCODE 357 )
(define M11DSW 351 )
(define M11DTN 350 )
(define M11DTR 353 )
(define M11MCAT 419 )
(define M11MGENTYPE 422 )
(define M11MLABEL 416 )
(define M11MMN 415 )
(define M11MNATION 420 )
(define M11MPUSRC 423 )
(define M11MSPECTYPE 421 )
(define M11MSPI 417 )
(define M11MTN 418 )
(define M1203STIN 435 )
(define M1230CHAR1 453 )
(define M1230CHAR2 454 )
(define M1230CHAR3 455 )
(define M1230NUM1 451 )
(define M1230NUM2 452 )
(define M1230TN 450 )
(define M1231CNT 361 )
(define M1231GMT 362 )
(define M1231MN 358 )
(define M1231RR 360 )
(define M1231SI 359 )
(define M12AT 436 )
(define M12DT 437 )
(define M12HEIGHT 441 )
(define M12IFFM1 446 )
(define M12IFFM2 447 )
(define M12IFFM3A 448 )
(define M12IFFMC 449 )
(define M12MI 445 )
(define M12STI 433 )
(define M12STIN 434 )
(define M12SUBLABEL 432 )
(define M12SW 442 )
(define M12TT 440 )
(define M12XCOOR 438 )
(define M12XDOT 443 )
(define M12YCOOR 439 )
(define M12YDOT 444 )
(define M1307ADDRESSEE 465 )
(define M1307CHARN 466 )
(define M1307CHARN1 467 )
(define M1307CHARN2 468 )
(define M1307CHARN3 469 )
(define M1307EI 458 )
(define M1307GI 460 )
(define M1307LI 461 )
(define M1307NUM 463 )
(define M1307ORIGIN 464 )
(define M1307TI 459 )
(define M1307TNM 462 )
(define M13SI 456 )
(define M13SUBLABEL 457 )
(define M14CI 282 )
(define M14HI 281 )
(define M14MN 272 )
(define M14NOS 276 )
(define M14PURUSOURCE 278 )
(define M14TNFRIEND 279 )
(define M14TNTARGET 280 )
(define M14WES 273 )
(define M14WH 277 )
(define M14WR 275 )
(define M14WT 274 )
(define M15COMAMPLMASK #x000FFF )
(define M15COMD 286 )
(define M15COMMAMPLI 290 )
(define M15IT 292 )
(define M15MN 283 )
(define M15RC 288 )
(define M15RCMASK #x700000 )
(define M15SP1 289 )
(define M15TNADDE 284 )
(define M15TNADDEEMASK #x0007F0 )
(define M15TNTARGET 291 )
(define M15TWA 285 )
(define M15WN 293 )
(define M15WT 287 )
(define M1DLAT 4 )
(define M1DLONG 6 )
(define M1MN 0 )
(define M1PURU 5 )
(define M1RP 1 )
(define M1SP1 3 )
(define M1SPI 2 )
(define M2ID 23 )
(define M2MN 21 )
(define M2SI 24 )
(define M2TN 22 )
(define M2TQ 25 )
(define M2XCOOR 26 )
(define M2YCOOR 27 )
(define M3ID 42 )
(define M3MN 40 )
(define M3SI 43 )
(define M3TN 41 )
(define M3TQ 44 )
(define M3XCOOR 45 )
(define M3YCOOR 46 )
(define M4ADRTYPE 64 )
(define M4AID 63 )
(define M4ALABEL 67 )
(define M4AMN 61 )
(define M4ANRT 65 )
(define M4ASI 66 )
(define M4ATN 62 )
(define M4AXCOOR 68 )
(define M4AYCOOR 69 )
(define M4BDATUMERROR 91 )
(define M4BHOURS 89 )
(define M4BLABEL 87 )
(define M4BMINUTES 88 )
(define M4BMISSION 85 )
(define M4BMN 83 )
(define M4BMSLCAP 92 )
(define M4BSP1 86 )
(define M4BTIMESW 90 )
(define M4BTN 84 )
(define M4CCS 97 )
(define M4CID 95 )
(define M4CLABEL 99 )
(define M4CMN 93 )
(define M4CSI 98 )
(define M4CSW 96 )
(define M4CTN 94 )
(define M4CXCOOR 100 )
(define M4CYCOOR 101 )
(define M4DAF 123 )
(define M4DAUDIO 125 )
(define M4DBB 124 )
(define M4DBRT 118 )
(define M4DBSW 119 )
(define M4DDOPP 127 )
(define M4DID 117 )
(define M4DLABEL 120 )
(define M4DLAYER 128 )
(define M4DMN 115 )
(define M4DSPP 126 )
(define M4DTN 116 )
(define M4DXCOOR 121 )
(define M4DYCOOR 122 )
(define M5MN 145 )
(define M5POINT 148 )
(define M5POINTAMP 149 )
(define M5SI 147 )
(define M5TN 146 )
(define M5XCOOR 150 )
(define M5YCOOR 151 )
(define M6AAC 179 )
(define M6AACT 170 )
(define M6ABA 168 )
(define M6ABC 169 )
(define M6ABEARING 174 )
(define M6AELEVATION 177 )
(define M6AFREQUENCY 181 )
(define M6AJRSL 176 )
(define M6ALABEL 171 )
(define M6AMN 166 )
(define M6APL 173 )
(define M6ASW 178 )
(define M6ATE 172 )
(define M6ATIMESTALE 180 )
(define M6ATN 167 )
(define M6ATNOFORIGIN 175 )
(define M6BFB 184 )
(define M6BLABEL 187 )
(define M6BMN 182 )
(define M6BPL 186 )
(define M6BTE 185 )
(define M6BTN 183 )
(define M6BXCOOR 188 )
(define M6BYCOOR 189 )
(define M6CJT 208 )
(define M6CLABEL 210 )
(define M6CMN 206 )
(define M6CPRF 213 )
(define M6CPS 212 )
(define M6CSCH 211 )
(define M6CSP1 209 )
(define M6CTN 207 )
(define M6DBEARING 235 )
(define M6DBW 237 )
(define M6DCCV 233 )
(define M6DCONF 231 )
(define M6DCTRL 222 )
(define M6DEMITTERNR 229 )
(define M6DEWC 224 )
(define M6DLABEL 225 )
(define M6DMN 220 )
(define M6DMODENR 230 )
(define M6DMUL 232 )
(define M6DPERIOD 226 )
(define M6DRC 223 )
(define M6DRCV 228 )
(define M6DRD 236 )
(define M6DRTN 234 )
(define M6DTN 221 )
(define M6DTNADDEE 227 )
(define M811MCU 429 )
(define M811MCURACT 425 )
(define M811MDISCID 430 )
(define M811MMISSION 424 )
(define M811MOPSTAT 426 )
(define M811MSW 427 )
(define M811MTN2 428 )
(define M81AAWC 9 )
(define M81ASWC 10 )
(define M81CAC 11 )
(define M81ENVCAT 17 )
(define M81HC 12 )
(define M81HD 14 )
(define M81MN 7 )
(define M81MU 19 )
(define M81PURU 8 )
(define M81SI 20 )
(define M81SP1 13 )
(define M81TY 18 )
(define M81XDOT 15 )
(define M81YDOT 16 )
(define M82HEIGHT 30 )
(define M82HOURS 34 )
(define M82HS 39 )
(define M82IDAMP 38 )
(define M82MINUTES 33 )
(define M82MN 28 )
(define M82SP1 35 )
(define M82SW 36 )
(define M82SZ 37 )
(define M82TN 29 )
(define M82XDOT 31 )
(define M82YDOT 32 )
(define M83CM 50 )
(define M83HC 60 )
(define M83HOURS 54 )
(define M83IDAMP 58 )
(define M83MINUTES 53 )
(define M83MN 47 )
(define M83SP1 55 )
(define M83SP2 59 )
(define M83SW 56 )
(define M83SZ 57 )
(define M83TN 48 )
(define M83UC 49 )
(define M83XDOT 51 )
(define M83YDOT 52 )
(define M84AASWPTTYPE 71 )
(define M84ACA 74 )
(define M84ACB 73 )
(define M84ACBI 78 )
(define M84ACLASS 72 )
(define M84ADEPTH 75 )
(define M84ADI 76 )
(define M84AMN 70 )
(define M84ANDUR 82 )
(define M84ANRAD 81 )
(define M84APOSSUB 80 )
(define M84ASENSOR 77 )
(define M84ASPEED 79 )
(define M84CAC 106 )
(define M84CBA 104 )
(define M84CBEARING 105 )
(define M84CCAL 113 )
(define M84CCHNAMP 108 )
(define M84CCHNBR 112 )
(define M84CMN 102 )
(define M84CMRF 103 )
(define M84CRANGE 107 )
(define M84CTD 111 )
(define M84CTLOST 114 )
(define M84CTREM 110 )
(define M84CTYPE 109 )
(define M84DBA 132 )
(define M84DBD 131 )
(define M84DBEARING1 137 )
(define M84DBEARING2 142 )
(define M84DBI1 138 )
(define M84DBI2 143 )
(define M84DCDEPHT 133 )
(define M84DCLASS 134 )
(define M84DCLASSAMP 135 )
(define M84DFAAF 141 )
(define M84DMN 129 )
(define M84DRANGE 139 )
(define M84DRANGEACC 140 )
(define M84DSAAF 144 )
(define M84DSENSOR 130 )
(define M84DSW 136 )
(define M85HD 163 )
(define M85HDSW 164 )
(define M85HOURS 161 )
(define M85MINUTES 160 )
(define M85MN 152 )
(define M85REF 155 )
(define M85RELTNTN 153 )
(define M85SP1 156 )
(define M85SP2 159 )
(define M85SP3 165 )
(define M85SW 154 )
(define M85TSW 162 )
(define M85XDOT 157 )
(define M85YDOT 158 )
(define M86BAC 200 )
(define M86BBA 193 )
(define M86BBC 199 )
(define M86BBEARING 194 )
(define M86BBI 195 )
(define M86BCONF 204 )
(define M86BEMITTERNR 202 )
(define M86BEVSW 201 )
(define M86BFM 198 )
(define M86BFREQFREQRANGE 197 )
(define M86BLS 196 )
(define M86BMODE 203 )
(define M86BPEC 205 )
(define M86BRS 192 )
(define M86BTIMESTALE 191 )
(define M86Bn 190 )
(define M86CARP 218 )
(define M86CARPSW 219 )
(define M86CMN 214 )
(define M86CPOLAR 215 )
(define M86CPULSEWIDTH 217 )
(define M86CSP1 216 )
(define M89FBRG 405 )
(define M89FCAT 401 )
(define M89FHOURS 400 )
(define M89FMAJAXIS 407 )
(define M89FMINAXIS 406 )
(define M89FMINUTES 399 )
(define M89FMN 398 )
(define M89FPF 404 )
(define M89FSQC 403 )
(define M89FSRC 402 )
(define M9A9ACT 296 )
(define M9A9ISAC 303 )
(define M9A9LABEL 295 )
(define M9A9MI 304 )
(define M9A9MN 294 )
(define M9A9MODE1 297 )
(define M9A9MODE2 298 )
(define M9A9MODE3 299 )
(define M9A9MODE4 300 )
(define M9A9PURU 302 )
(define M9A9TN 301 )
(define M9AC1CI 431 )
(define M9ACT 240 )
(define M9AI 242 )
(define M9BACT 382 )
(define M9BLABEL 381 )
(define M9BMN 380 )
(define M9BTN1 384 )
(define M9BTN2 385 )
(define M9BTNORIGIN 383 )
(define M9CLABEL 364 )
(define M9CMN 363 )
(define M9COPERPOS 367 )
(define M9CPUADDEE 366 )
(define M9CPUADDRESS 365 )
(define M9CXCOORD 368 )
(define M9CYCOORD 369 )
(define M9DLABEL 306 )
(define M9DMN 305 )
(define M9DNETCYCLE 316 )
(define M9DRQ1 308 )
(define M9DRQ2 315 )
(define M9DRQ3 313 )
(define M9DRQ4 311 )
(define M9DSW 310 )
(define M9DTN1 309 )
(define M9DTN2 307 )
(define M9DTN3 314 )
(define M9DTN4 312 )
(define M9E19TN 388 )
(define M9E19TNA1 389 )
(define M9E19TNA2 390 )
(define M9E19TNN 391 )
(define M9E3SW 386 )
(define M9E5SW 387 )
(define M9EACT 252 )
(define M9EMISSNR 259 )
(define M9EMISSNRA1 261 )
(define M9EMISSNRA2 262 )
(define M9EMISSNRN 260 )
(define M9ENVCAT 241 )
(define M9ETN 251 )
(define M9EVC 253 )
(define M9EVC1 254 )
(define M9EVC2 255 )
(define M9EVC3 256 )
(define M9EVC4 257 )
(define M9EVCF 258 )
(define M9FACT 395 )
(define M9FLABEL 393 )
(define M9FMN 392 )
(define M9FSI 409 )
(define M9FSW 408 )
(define M9FTN 394 )
(define M9FTNREL 414 )
(define M9FXCOOR 396 )
(define M9FXCRATE 412 )
(define M9FXCSW 413 )
(define M9FXDOT 410 )
(define M9FYCOOR 397 )
(define M9FYDOT 411 )
(define M9F_BASIC 0 )
(define M9F_SECONDARY 1 )
(define M9GEW 377 )
(define M9GLABEL 371 )
(define M9GLATDEG 373 )
(define M9GLATMIN 372 )
(define M9GLONGDEG 376 )
(define M9GLONGMIN 375 )
(define M9GMN 370 )
(define M9GNS 374 )
(define M9ID 243 )
(define M9IDAMP 244 )
(define M9LABEL 239 )
(define M9MN 238 )
(define M9PURUAS 247 )
(define M9SI 245 )
(define M9SP 250 )
(define M9SPI 249 )
(define M9STI 248 )
(define M9TN 246 )
(define MAXIMUL_LINK_POINTERS 500 )
(define MAXIMUM_NUMBER_OF_BITS 24 )
(define MAXIMUM_NUMBER_OF_DELETED_TRACKS 5 )
(define MAXIMUM_OF_TRAINING_TRACKS #o177 )
(define MAXIMUM_TRACKS_TO_REPORT_SPECIAL_CODE_CHANGES 200 )
(define MAX_AC_Type 15 )
(define MAX_AMPL_SIZE 8 )
(define MAX_ASW_POINT_TYPE 63 )
(define MAX_Ampl_Class_Type 7 )
(define MAX_BA_Type 3 )
(define MAX_BA_Type 7 )
(define MAX_CHANNEL_DATA_LENGTH 8192 )
(define MAX_CLASS_SIZE 8 )
(define MAX_DLRP_DELTA_RADIAN (degree-to-radian 17.06640625 ))
(define MAX_PU_ADDRESS 63 )
(define MAX_EMITTER_MODE MAX_PU_ADDRESS)
(define MAX_EMITTER_NUMBER 16383 )
(define MAX_ID_SIZE 16 )
(define MAX_INITIAL_OPNOTE_LIST 100 )
(define MAX_MOMENT (* 24 60 60 ) )
(define MAX_NETWORK_TRACKS 500 )
(define MAX_NETWORK_TRACK_NUMBER_TYPE 4095 )
(define MAX_OP_NOTES 500 )
(define MAX_PU 62 )
(define MAX_PU_NUMBER_RANGE 62 )
(define MAX_RECEPTION_QUALITY 7 )
(define MAX_SIMULATED_TRACKS_PER_PU 400 )
(define MAX_SOURCE_ID 2147483647 )
(define MAX_TRACKS 5000)
(define MAX_TRACK_ID 2000000000 )
(define MAX_TRACK_ID_TYPE 2000000000 )
(define MAX_weapon_e 11 )
(define MCANTCO #x300000 )
(define MEGA 1000000.0 )
(define MESSAGE_NUMBER_M0 0 )
(define MESSAGE_NUMBER_M1 1 )
(define MESSAGE_NUMBER_M10 10 )
(define MESSAGE_NUMBER_M11 11 )
(define MESSAGE_NUMBER_M12 12 )
(define MESSAGE_NUMBER_M13 13 )
(define MESSAGE_NUMBER_M14 14 )
(define MESSAGE_NUMBER_M15 15 )
(define MESSAGE_NUMBER_M2 2 )
(define MESSAGE_NUMBER_M3 3 )
(define MESSAGE_NUMBER_M4 4 )
(define MESSAGE_NUMBER_M5 5 )
(define MESSAGE_NUMBER_M6 6 )
(define MESSAGE_NUMBER_M7 7 )
(define MESSAGE_NUMBER_M8 8 )
(define MESSAGE_NUMBER_M9 9 )
(define MICRO 0.000001 )
(define MILLI 0.001 )
(define MILLION_TIMES 10000 )
(define MINIMUM_SECOND_FOR_QUALITY_DECREASE 20 )
(define MINIMUM_TIME_FOR_NEW_ALLOC 120 )
(define MIN_PU_ADDRESS_TYPE 1 )
(define MIN_PU_NUMBER_RANGE 1 )
(define MIN_SOURCE_ID 0 )
(define MISSILE_CONST #x080000 )
(define Mission_Spare 11 )
(define NATIONAL_TAG_SUBLABEL 6 )
(define NDDS_EMUL_LOGLEVEL_FUN #x00000001 )
(define NDDS_EMUL_LOGLEVEL_INSERT_DATA #x00000008 )
(define NDDS_EMUL_LOGLEVEL_READ_DATA #x00000002 )
(define NDDS_EMUL_LOGLEVEL_WRITE_DATA #x00000004 )
(define NDDS_MESSAGE_SERIAL_MAX 1024 )
(define NETMODE_BROADCAST 4 )
(define NETMODE_INDEX 3 )
(define NETMODE_NET_SYNC 0 )
(define NETMODE_NET_TEST 1 )
(define NETMODE_ROLE_CALL 2 )
(define NETMODE_SHORT_BROADCAST 3 )
(define NETWORK_ID_LAST 2000000000 )
(define NETWORK_ID_START  1 )
(define NETWORK_TRACK_QUALITY_TYPE_FIRST 0 )
(define NM_TO_M 1852.0 )
(define NO_FAILURE 0 )
(define NO_FIND #x0C0000 )
(define NO_STATEMENT 0 )
(define NTAG_START 0 )
(define NTDS_EI_EOR 3 )
(define NTDS_EI_PTR 6 )
(define NTDS_EI_PTTB 7 )
(define NTDS_EI_PTTD 5 )
(define NTDS_EI_RESET 2 )
(define ONE_DAY_IN_SEC (* 24 60 60 ) )
(define ONE_DAY_IN_SEC (* 24 60 60 ))
(define ONE_MINUTE_IN_SEC 60 )
(define ONE_TIME 1 )
(define OPNOTE_SERIAL_MODULATOR 256 )
(define OPNOTE_SUBLABEL 7 )
(define ORD_ASSUME_CONTROL 0 )
(define ORD_CONTROL_AND_ENGAGE 1 )
(define ORD_LAUNCH_FIGHTER 4 )
(define ORD_LAUNCH_HELI 5 )
(define ORD_RETURN_TO_BASE 3 )
(define ORD_SPARE6 6 )
(define ORD_SPARE7 7 )
(define ORD_TRANSFER_CONTROL 2 )
(define ORIGINAL_ORDER_RC 0 )
(define OWNSHIP_WEAPON_CONFIG_UNAVAILABLE #xFF )
(define PI 3.14159265358979323846264338327950288 )
(define PMASK #x000FFF )
(define PMASKM1 #x01FFFF )
(define POINT_AMPLIFY_CORRIDOR_TAB 3 )
(define POINT_AMPLIFY_DAN_BUOY 1 )
(define POINT_AMPLIFY_MARSHAL_PT 1 )
(define POINT_AMPLIFY_ORIBIT_POINT 1 )
(define POINT_AMPLIFY_REPLENISHMENT 5 )
(define POINT_AMPLIFY_RESCUE 6 )
(define POINT_AMPLIFY_SEARCH_AREA_POINT 7 )
(define POINT_AMPLIFY_TANKER 0 )
(define POINT_AMPLIFY_TOMCAT 1 )
(define POINT_ECM_FIX 0 )
(define POINT_EMERGENCY 7 )
(define POINT_ENEMY 15 )
(define POINT_HAZARD 2 )
(define POINT_MINE_WARFARE 3 )
(define POINT_REFERENCE_POINT_GENERAL 4 )
(define POINT_SITE 13 )
(define POINT_STATION_AIR 6 )
(define POINT_STATION_AIR_EXT 9 )
(define POINT_STATION_GENERAL 5 )
(define POINT_SUPPORTING_UNIT 14 )
(define POUND_TO_KG_CONVERSION 0.453592 )
(define PREAASWTORP0M4C #x8C0004 )
(define PREAASWTORP0M84C #x000008 )
(define PREAFRAME #x00000C )
(define PREAFRAME #x0001EC )
(define PREAFRAME #x00020C )
(define PREAFRAME #x00040C )
(define PREAFRAME #x00060C )
(define PREAFRAME #x00080C )
(define PREAFRAME #x00300D )
(define PREAFRAME #x00380D )
(define PREAFRAME #x08000C )
(define PREAFRAMEM1 #x000001 )
(define PREAFRAMEM11C #x00002B )
(define PREAFRAMEM11D #x00003B )
(define PREAFRAMEM11M #x0000CB )
(define PREAFRAMEM1231 #x0001FC )
(define PREAFRAMEM14 #x00000E )
(define PREAFRAMEM14WES_ENG_BROKEN #x000080 )
(define PREAFRAMEM14WES_ENG_INTERRUP #x0000A0 )
(define PREAFRAMEM14WES_HEAD_UP #x000090 )
(define PREAFRAMEM14WES_TARGET_DISTROYED #x000050 )
(define PREAFRAMEM15RCIS2 #x200000 )
(define PREAFRAMEM15RCIS7 #x700000 )
(define PREAFRAMEM15_assign #x00600F )
(define PREAFRAMEM15_assume_duties #x02400F )
(define PREAFRAMEM15_break_engagement_of_weapon_specified #x01A00F )
(define PREAFRAMEM15_cease_conducting_procedures #x02200F )
(define PREAFRAMEM15_cease_duties #x02600F )
(define PREAFRAMEM15_cease_engage #x00800F )
(define PREAFRAMEM15_cease_fire #x00C00F )
(define PREAFRAMEM15_cease_proceeding_to_point #x01E00F )
(define PREAFRAMEM15_conduct_procedures #x02000F )
(define PREAFRAMEM15_cover #x00E00F )
(define PREAFRAMEM15_engage #x00400F )
(define PREAFRAMEM15_engage_asm_ssm #x02800F )
(define PREAFRAMEM15_engage_with_weapon_specified #x01800F )
(define PREAFRAMEM15_hold_fire #x00A00F )
(define PREAFRAMEM15_proceed_to_point #x01C00F )
(define PREAFRAMEM15_salvo_clear #x01000F )
(define PREAFRAMEM15_weapons_free #x00000F )
(define PREAFRAMEM15_weapons_tight #x00200F )
(define PREAFRAMEM2 #x000002 )
(define PREAFRAMEM3 #x000003 )
(define PREAFRAMEM4B #x400004 )
(define PREAFRAMEM5 #x000005 )
(define PREAFRAMEM6AACT0 #x000006 )
(define PREAFRAMEM6AACT1 #x200006 )
(define PREAFRAMEM6B #x400006 )
(define PREAFRAMEM6C #x800006 )
(define PREAFRAMEM81 #x000008 )
(define PREAFRAMEM811M #x000008 )
(define PREAFRAMEM82 #x000008 )
(define PREAFRAMEM83 #x000008 )
(define PREAFRAMEM85SW0 #x000008 )
(define PREAFRAMEM85SW1 #x010008 )
(define PREAFRAMEM86C #x000008 )
(define PREAFRAMEM89F #x000008 )
(define PREAFRAMEM9AC1 #x000109 )
(define PREAFRAMEM9AC2 #x000209 )
(define PREAFRAMEM9AC3 #x000309 )
(define PREAFRAMEM9AC4 #x000409 )
(define PREAFRAMEM9AC5 #x000509 )
(define PREAFRAMEM9AC6 #x000609 )
(define PREAFRAMEM9AC7 #x000709 )
(define PREAFRAMEM9AC9 #x000909 )
(define PREAFRAMEM9B #x000019 )
(define PREAFRAMEM9C #x000029 )
(define PREAFRAMEM9DSW0 #x000039 )
(define PREAFRAMEM9DSW1 #x800039 )
(define PREAFRAMEM9G #x000069 )
(define PREAMBAFRAME #x00000A )
(define PREAMBAFRAME #x80003B )
(define PREAMBAFRAME #xC00006 )
(define PREAMBFRAMEA #x100049 )
(define PREAMBFRAMEA #x200049 )
(define PREAMBFRAMEA #x300049 )
(define PREAMBFRAMEA #x500049 )
(define PREAMBFRAMEA #x600049 )
(define PREANOTACKM84A #x000008 )
(define PREASUBDATUM0M84A #x000008 )
(define PREASUBDATUM1M84A #x000008 )
(define PREASUBSURFTQ0M84A #x000008 )
(define PREASUBSURFTQ1M84A #x000008 )
(define PREBFRAME #x000000 )
(define PREBFRAME #x000200 )
(define PREBFRAMEM11CSW0 #x000000 )
(define PREBFRAMEM11CSW1 #x000001 )
(define PREBFRAMEM11CSW2 #x000002 )
(define PREBFRAMEM4B #x000000 )
(define PREBFRAMEM4B #x000800 )
(define PREBFRAMEM82SW1 #x010000 )
(define PREBFRAMEM83SW1 #x010000 )
(define PREBFRAMEM85D #x100800 )
(define PREBFRAMEM85H #x000800 )
(define PREBFRAMEM85N #x0FF800 )
(define PREBFRAMEM89F #x000000 )
(define PREBFRAMEM9AC1 #x800000 )
(define PREBFRAMEM9AC3 #x080000 )
(define PREBFRAMEM9B #x000000 )
(define PREBFRAMEM9F #x000000 )
(define PREBSUBDATUM1M84A #x002000 )
(define PU_ADDRESS_LAST 63 )
(define PU_ENV_AIR #x030000 )
(define PU_ENV_LAND #x020000 )
(define PU_ENV_SUBSURFACE #x010000 )
(define PU_ENV_SURFACE #x000000 )
(define PU_NUMBER_RANGE 62 )
(define QUARTER_PI 0.78539816339744830961566084581987572 )
(define RADIAN_TO_ARCMINUTE 3437.7467707849392526078892888463 )
(define RADIAN_TO_ARCSECOND 206264.80624709635515647335733078 )
(define RC #x200000 )
(define RC #x400000 )
(define RCV_Evaluate_Sector 15 )
(define RCV_Evaluate_Track 14 )
(define RCV_Request_Periodic_Report 0 )
(define RCV_Request_Update_And_Watch 3 )
(define RCV_Request_Update_Then_Watch 3 )
(define RC_CANT_COMPLY 3 )
(define RC_CANT_COMPLY 6 )
(define RC_CANT_PROCESS 7 )
(define RC_COMPLIANCE_REQUIRED 0 )
(define RC_MACHINE_RECEIPT 2 )
(define RC_NO_COMPLIANCE 1 )
(define RC_SPARE_1 1 )
(define RC_SPARE_4 4 )
(define RC_SPARE_5 5 )
(define RC_WILL_COMPLY 3 )
(define RECEIVED_TRAINING_TRACKS_RANGE_MAX MAXIMUM_OF_TRAINING_TRACKS )
(define RECEIVED_TRAINING_TRACKS_RANGE_MAX MAXIMUM_OF_TRAINING_TRACKS)
(define RECEPTION_QUALITY_CALCULATE_CYCLE 8 )
(define RESPONSE #x0D0000 )
(define R_C_NOT_REQUIRED_CONST #x100000 )
(define SECOND_FRAME_OFFSET 2 )
(define SENSOR_ON 1 )
(define SI 0 )
(define SIMULATION_TRACK 0 )
(define SIXTH_PI 0.52359877559829887308 )
(define SI_TRACK_NOT_SIMULATED 0 )
(define SMASK #x0000FF )
(define SMASK #x000FFF )
(define SOURCE_FILTER_FORWARDING_ISDL_RECEIVED 2 )
(define SOURCE_FILTER_FORWARDING_LINKK_RECEIVED 4 )
(define SPECIAL_CODE_TYPE_FIRST 0 )
(define SPECIAL_CODE_TYPE_LAST 4095 )
(define SPI_NO_SPECIAL_PROCESSING_REQUIRED 0 )
(define STATUS_EI #x04 )
(define STOPINDICATION #x080000 )
(define STOP_TRACKCOMM_ALERT 7 )
(define SWITCH_TIME 1 )
(define SWITCH_XYDOT 0 )
(define SW_REFERENCE_SONOBUOY 3 )
(define SW_SONOBUOY_POSITION 2 )
(define SW_SPARE 1 )
(define SW_Velocity 0 )
(define South 1 )
(define Src_ASW_Sensor 4 )
(define Src_EW 1 )
(define Src_Intel 2 )
(define Src_Sosus 3 )
(define TASK_DEFAULT_STACK (* 200 1024 ))
(define TASK_TRACK_INPUT_PRIORITY 101 )
(define TASK_TRACK_INPUT_STACK_SIZE 100000 )
(define TEN_TIMES 10 )
(define THIRD_FRAME_OFFSET 4 )
(define THIRD_PI 1.04719755119659774615 )
(define THOUSAND_TIMES 1000 )
(define THREE_TIMES 3 )
(define TIME_STALE #x0001F0 )
(define TM_INVALID_NTN -1 )
(define TO_LINK11_NETWORK 1 )
(define TRACKCOMM_ALERT 5 )
(define TRACK_QUALITY_7 7 )
(define TRACK_QUALITY_OF_MANUAL_TRACK 0 )
(define TWO_PI 6.28318530717958647692528676655900576 )
(define Time_Remaining_No_Statement 15 )
(define WAIT_READ_VECTOR #x41 )
(define WAIT_WRITE_VECTOR #x42 )
(define WILLCO 3 )
(define WORD_BYTES 4 )
(define West 1 )
(define Word_Size 32 )
(define command_and_control_source_id 119 )
(define house_keeping_source_id 118 )
(define max_time_without_m5 360 )
(define max_time_without_m9b 240 )
(define retransmission_request 1 )
(define three_times 3 )

(define SIMULATED_TRACK 1)
(define  EMERGENCY  0)



(define SI_TRACK_NOT_SIMULATED  0)
(define SPI_NO_SPECIAL_PROCESSING_REQUIRED  0)


(define TDL_FILTER_NON_REAL_TIME  1)	;;Ticket:1608 송영환 추가
(define TDL_FILTER_CIVIL  2) ;;Ticket:1608 송영환 추가
(define 	LINK_STATUS_LINK_NOT_INVOLVED   0)
(define 	LINK_STATUS_TX_PROHIBITED       1)     
(define 	LINK_STATUS_TRANSMITTED         2)     
(define 	LINK_STATUS_CORRELATED          3)     
(define 	LINK_STATUS_LINK_RECEIVED       4)
(define 	TDL_WE_STATUS_WEAPON_STATUS     0)
(define 	TDL_WE_STATUS_ENGAGEMENT_STATUS 1)
(define TDL_FILTER_AREA_NONE     0)
(define TDL_FILTER_AREA_CIRCLE   1) 
(define TDL_FILTER_AREA_SECTOR   2) 
(define TDL_FILTER_AREA_RING     3) 
(define TDL_FILTER_AREA_POLYGON  4)
(define TDL_FILTER_ENVIRONMENT_AIR          1)
(define TDL_FILTER_ENVIRONMENT_SURFACE      2)
(define TDL_FILTER_ENVIRONMENT_SUBSURFACE   4)
(define TDL_FILTER_ENVIRONMENT_LAND         8)
(define TDL_FILTER_ENVIRONMENT_UNKNOWN      16)
(define TDL_FILTER_ENVIRONMENT_SPACE        32)
(define   TDL_FILTER_IDENTITY_UNKNOWN        1 )						
(define 	TDL_FILTER_IDENTITY_PENDING         2 )
(define 	TDL_FILTER_IDENTITY_ASSUMED_FRIEND  4 )
(define 	TDL_FILTER_IDENTITY_FRIEND          8 )
(define 	TDL_FILTER_IDENTITY_NEUTRAL         16)
(define TDL_FILTER_KIND_POINT          1)
(define TDL_FILTER_KIND_BEARING        2)
(define TDL_FILTER_KIND_SPECIAL_POINT  4)
(define TDL_FILTER_NON_REAL_TIME  1)	;;Ticket:1608 송영환 추가
(define TDL_FILTER_CIVIL          2)		;;Ticket:1608 송영환 추가
(define 	TDL_ORDER_WEAPONS_FREE                   0)
(define 	TDL_ORDER_WEAPONS_TIGHT                  1)
(define 	TDL_ORDER_ENGAGE                         2)
(define 	TDL_ORDER_ASSIGN                         3)
(define 	TDL_ORDER_CEASE_ENGAGE                   4)
(define 	TDL_ORDER_HOLD_FIRE                      5)
(define 	TDL_ORDER_CEASE_FIRE                     6)
(define 	TDL_ORDER_COVER                          7)
(define 	TDL_ORDER_SALVO_CLEAR                    8)
(define 	TDL_ORDER_ENGAGE_SPECIFIC                9)
(define 	TDL_ORDER_CEASE_ENGAGE_SPECIFIC         10)
(define 	TDL_ORDER_PROCEED_TO_POINT              11)
(define 	TDL_ORDER_CEASE_PROCEED_TO_POINT        12)
(define 	TDL_ORDER_PAIRING                       13)
(define 	TDL_ORDER_ASSOCIATION                   14)
(define 	TDL_ORDER_CORRELATION                   15)
(define 	TDL_ORDER_TERMINATE_PAIRING_ASSOCIATION 16)
(define 	TDL_ORDER_DLP_REPLY                     17)
(define TDL_MODECODE_NONE_BY_OPERATOR #x0 ) ;;ticket:1513 20110107 김동일 | IFF MODE 값 사용자 변경여부
(define TDL_MODECODE1_BY_OPERATOR     #x1 ) ;;ticket:1513 20110107 김동일 | IFF MODE 값 사용자 변경여부
(define TDL_MODECODE2_BY_OPERATOR     #x2 ) ;;ticket:1513 20110107 김동일 | IFF MODE 값 사용자 변경여부
(define TDL_MODECODE3_BY_OPERATOR     #x4 ) ;;ticket:1513 20110107 김동일 | IFF MODE 값 사용자 변경여부
(define TDL_MODECODE4_BY_OPERATOR     #x8 ) ;;ticket:1513 20110107 김동일 | IFF MODE 값 사용자 변경여부
	


(define  DID_AC_AIR_DIR_ACTION                        5968)
(define  DID_AC_AIR_DIR_ACTION2                       5969)
(define  DID_AC_AIR_DIR_ADVICE                        5970)
(define  DID_AC_AIR_DIR_ADVICE2                       5971)
(define  DID_AC_AIR_DIR_DATA                          5941)
(define  DID_AC_AIR_DIR_DATA2                         5942)
(define  DID_AC_AIR_DIR_DATA_REQ                      5943)
(define  DID_AC_AIR_DIR_DATA_REQ2                     5944)
(define  DID_AC_AIR_DIR_PARAMETER                     5945)
(define  DID_AC_AIR_DIR_PARAMETER2                    5946)
(define  DID_AC_AIR_DIR_WAYPOINT                      5947)
(define  DID_AC_AIR_DIR_WAYPOINT2                     5948)
(define  DID_AC_AIR_ROUTE                             6028)
(define  DID_AC_AIR_ROUTE_ACK                         6030)
(define  DID_AC_DISPLAY_ROUTE                         6208)
(define  DID_AC_HELI_REC_ACTION                       5972)
(define  DID_AC_HELI_REC_ACTION2                      5973)
(define  DID_AC_HELI_REC_APPROACH_DATA                5974)
(define  DID_AC_HELI_REC_APPROACH_DATA2               5975)
(define  DID_AC_HELI_REC_COM_PARAMETER                5949)
(define  DID_AC_HELI_REC_COM_PARAMETER2               5950)
(define  DID_AC_HELI_REC_DATA                         5951)
(define  DID_AC_HELI_REC_DATA2                        5952)
(define  DID_AC_HELI_REC_DATA_REQ                     5953)
(define  DID_AC_HELI_REC_DATA_REQ2                    5954)
(define  DID_AC_HELI_REC_DESCENT_DATA                 5976)
(define  DID_AC_HELI_REC_DESCENT_DATA2                5977)
(define  DID_AC_HELI_REC_PARAMETER                    5955)
(define  DID_AC_HELI_REC_PARAMETER2                   5956)
(define  DID_AC_HELI_REC_WAYPOINT                     5957)
(define  DID_AC_HELI_REC_WAYPOINT2                    5958)
(define  DID_AC_SEPA_RULE_DATA                        5959)
(define  DID_AC_SEPA_RULE_DATA_REQ                    5960)
(define  DID_AC_SEPA_TRACK_INFO                       5978)
(define  DID_AC_SEPA_TRACK_INFO_REQ                   5961)
(define  DID_AC_SHOL_DATA                             5962)
(define  DID_AC_SHOL_DATA_REQ                         5963)
(define  DID_AC_VECTAC_ACTION                         5979)
(define  DID_AC_VECTAC_ADVICE                         5980)
(define  DID_AC_VECTAC_DATA                           5964)
(define  DID_AC_VECTAC_DATA_REQ                       5965)
(define  DID_AC_VECTAC_PARAMETER                      5966)
(define  DID_AC_VECTAC_WAYPOINT                       5967)
(define  DID_AIS_SHIP_INFO                            5656)
(define  DID_ASWPLAN_ACORN_DISPLAY                    6010)
(define  DID_ASWPLAN_ACORN_EDIT                       6034)
(define  DID_ASWPLAN_ACORN_INFO                       5981)
(define  DID_ASWPLAN_AIRPLAN44_DISPLAY                6011)
(define  DID_ASWPLAN_AIRPLAN44_EDIT                   6035)
(define  DID_ASWPLAN_AIRPLAN44_INFO                   5982)
(define  DID_ASWPLAN_AIRPLAN45_DISPLAY                6012)
(define  DID_ASWPLAN_AIRPLAN45_EDIT                   6036)
(define  DID_ASWPLAN_AIRPLAN45_INFO                   5983)
(define  DID_ASWPLAN_AIRPLAN46_DISPLAY                5984)
(define  DID_ASWPLAN_AIRPLAN46_DISPLAY_EDIT           6037)
(define  DID_ASWPLAN_AIRPLAN46_EDIT                   6038)
(define  DID_ASWPLAN_AIRPLAN46_INFO                   5985)
(define  DID_ASWPLAN_AIRPLAN47_DISPLAY                6013)
(define  DID_ASWPLAN_AIRPLAN47_EDIT                   6039)
(define  DID_ASWPLAN_AIRPLAN47_INFO                   5986)
(define  DID_ASWPLAN_AIRPLAN48_DISPLAY                6014)
(define  DID_ASWPLAN_AIRPLAN48_EDIT                   6040)
(define  DID_ASWPLAN_AIRPLAN48_INFO                   5987)
(define  DID_ASWPLAN_AIRPLAN49_DISPLAY                6015)
(define  DID_ASWPLAN_AIRPLAN49_EDIT                   6041)
(define  DID_ASWPLAN_AIRPLAN49_INFO                   5988)
(define  DID_ASWPLAN_AIRPLAN50_DISPLAY                6016)
(define  DID_ASWPLAN_AIRPLAN50_EDIT                   6042)
(define  DID_ASWPLAN_AIRPLAN50_INFO                   5989)
(define  DID_ASWPLAN_AIRPLAN51_DISPLAY                6017)
(define  DID_ASWPLAN_AIRPLAN51_EDIT                   6043)
(define  DID_ASWPLAN_AIRPLAN51_INFO                   5990)
(define  DID_ASWPLAN_AIRPLAN_EDIT                     6044)
(define  DID_ASWPLAN_AIRPLAN_INFO                     6018)
(define  DID_ASWPLAN_ASW_INFO_REQ_EDIT                6045)
(define  DID_ASWPLAN_ASW_PLAN_EDIT                    6046)
(define  DID_ASWPLAN_ASW_PLAN_INFO                    6183)
(define  DID_ASWPLAN_CIRCULARATTACK_EDIT              6047)
(define  DID_ASWPLAN_CIRCULARATTACK_INFO              5991)
(define  DID_ASWPLAN_CORDON_DISPLAY                   6019)
(define  DID_ASWPLAN_CORDON_EDIT                      6048)
(define  DID_ASWPLAN_CORDON_INFO                      5992)
(define  DID_ASWPLAN_DEEPCREEP_EDIT                   6066)
(define  DID_ASWPLAN_DEEPCREEP_INFO                   6029)
(define  DID_ASWPLAN_DEPARTURE_ENTRY_SCREEN_EDIT      6049)
(define  DID_ASWPLAN_DEPARTURE_ENTRY_SCREEN_INFO      5993)
(define  DID_ASWPLAN_FENCE_EDIT                       6050)
(define  DID_ASWPLAN_FENCE_INFO                       5994)
(define  DID_ASWPLAN_GEOSECTOR_EDIT                   6051)
(define  DID_ASWPLAN_GEOSECTOR_INFO                   5995)
(define  DID_ASWPLAN_HITANDRUN_EDIT                   6067)
(define  DID_ASWPLAN_HITANDRUN_INFO                   6031)
(define  DID_ASWPLAN_LOCKON_EDIT                      6052)
(define  DID_ASWPLAN_LOCKON_INFO                      5996)
(define  DID_ASWPLAN_NEW_ACORN_DISPLAY                6032)
(define  DID_ASWPLAN_NEW_ACORN_EDIT                   6068)
(define  DID_ASWPLAN_NEW_ACORN_INFO                   6033)
(define  DID_ASWPLAN_NOTACK_EDIT                      6053)
(define  DID_ASWPLAN_NOTACK_INFO                      5997)
(define  DID_ASWPLAN_OAKTREE_DISPLAY                  6020)
(define  DID_ASWPLAN_OAKTREE_EDIT                     6054)
(define  DID_ASWPLAN_OAKTREE_INFO                     5998)
(define  DID_ASWPLAN_PINEAPPLE_EDIT                   6055)
(define  DID_ASWPLAN_PINEAPPLE_INFO                   5999)
(define  DID_ASWPLAN_PLANNET_DISPLAY                  6021)
(define  DID_ASWPLAN_PLANNET_EDIT                     6056)
(define  DID_ASWPLAN_PLANNET_INFO                     6000)
(define  DID_ASWPLAN_REDWOOD_EDIT                     6057)
(define  DID_ASWPLAN_REDWOOD_INFO                     6001)
(define  DID_ASWPLAN_SECTOR_SCREEN_EDIT               6058)
(define  DID_ASWPLAN_SECTOR_SCREEN_INFO               6002)
(define  DID_ASWPLAN_SKELETON_SCREEN_DISPLAY          6022)
(define  DID_ASWPLAN_SKELETON_SCREEN_EDIT             6059)
(define  DID_ASWPLAN_SKELETON_SCREEN_INFO             6003)
(define  DID_ASWPLAN_SONOBUOY_DISPLAY                 6023)
(define  DID_ASWPLAN_SONOBUOY_EDIT                    6060)
(define  DID_ASWPLAN_SONOBUOY_INFO                    6004)
(define  DID_ASWPLAN_SQUEEZE_EDIT                     6061)
(define  DID_ASWPLAN_SQUEEZE_INFO                     6005)
(define  DID_ASWPLAN_SUB_MOVE_AREA_DISPLAY            6024)
(define  DID_ASWPLAN_SUB_MOVE_AREA_EDIT               6062)
(define  DID_ASWPLAN_SUB_MOVE_AREA_INFO               6006)
(define  DID_ASWPLAN_SUB_PATROL_AREA_DISPLAY          6025)
(define  DID_ASWPLAN_SUB_PATROL_AREA_EDIT             6063)
(define  DID_ASWPLAN_SUB_PATROL_AREA_INFO             6007)
(define  DID_ASWPLAN_TDA_DISPLAY                      6026)
(define  DID_ASWPLAN_TDA_EDIT                         6064)
(define  DID_ASWPLAN_TDA_INFO                         6008)
(define  DID_ASWPLAN_TDZ_DISPLAY                      6027)
(define  DID_ASWPLAN_TDZ_EDIT                         6065)
(define  DID_ASWPLAN_TDZ_INFO                         6009)
(define  DID_CIWS_CDS_TRACK_DATA                      5816)
(define  DID_CIWS_COMMAND_ACK                         5827)
(define  DID_CIWS_DESIG_TRACK_INFO                    5828)
(define  DID_CIWS_EMCON                               5817)
(define  DID_CIWS_ENG_STATUS                          5807)
(define  DID_CIWS_MODE_SET_INFO                       5808)
(define  DID_CIWS_NO_ENG_SECTOR_DEF                   5819)
(define  DID_CIWS_PROCESSED_TRACK_DATA                5809)
(define  DID_CIWS_RADAR_SECTOR_CONTROL                5820)
(define  DID_CIWS_SECTOR_DEF_REQ                      6082)
(define  DID_CIWS_SPEED_THRESHOLD_SET                 5811)
(define  DID_CIWS_SURFACE_CUE                         5821)
(define  DID_CIWS_SURFACE_CUE_ACK                     5822)
(define  DID_CIWS_SURFACE_CUE_REQ                     5823)
(define  DID_CIWS_THREAT_TRACK_INFO                   5829)
(define  DID_CIWS_WEAPON_DESIG                        5825)
(define  DID_CIWS_WEAPON_DIRECTIVE_ACK                5812)
(define  DID_CIWS_WEAPON_SECTOR_INFO                  5813)
(define  DID_CIWS_WEAPON_STATE_CONTROL                5826)
(define  DID_CIWS_WEAPON_SYS_STATUS                   5815)
(define  DID_COMM_ALERT                               1555)
(define  DID_COMM_ALERT_RESULT_ACK                    1610)
(define  DID_COMM_FILE_UPDATE                         2585)
(define  DID_COMM_HCI_NETWORK_TRACK_BALANCE           6173)
(define  DID_COMM_INF_CTRL                            2117)
(define  DID_COMM_INIT_TRACK                          1259)
(define  DID_COMM_JOYSTICK_ALLOC                      1467)
(define  DID_COMM_JOYSTICK_ALLOC_STATUS               1622)
(define  DID_COMM_KILL_ASSESSMENT                     1436)
(define  DID_COMM_LOGOFF                              2509)
(define  DID_COMM_MODIFY_TRACK_INFO                   1261)
(define  DID_COMM_NETWORK_TRACK_CANCEL                2527)
(define  DID_COMM_NETWORK_TRACK_INFO                  2526)
(define  DID_COMM_NETWORK_TRACK_SHAPE_INFO            6163)
(define  DID_COMM_OPER_RSC_ALLOC_DEALLOC_REQ          1433)
(define  DID_COMM_PRIMITIVE_TRACK_ADD_INFO_REQ        2396)
(define  DID_COMM_PRIMITIVE_TRACK_CANCEL              2347)
(define  DID_COMM_PRIMITIVE_TRACK_INFO                1785)
(define  DID_COMM_RSC_ALLOC_DEALLOC_RESULT            1561)
(define  DID_COMM_RSC_DEALLOC_NOTIFY                  1799)
(define  DID_COMM_RSC_ENGAGEABLE_STATUS               1836)
(define  DID_COMM_RSC_ENGAGEMENT_INFO                 1801)
(define  DID_COMM_SIM_TRACK_CTRL                      2510)
(define  DID_COMM_SIM_TRACK_CTRL_ACK                  2511)
(define  DID_COMM_SK_ENGAGED_TRACK_STATUS             2421)
(define  DID_COMM_SUBSYSTEM_STATUS_INFO               2119)
(define  DID_COMM_SW_STATUS                           2285)
(define  DID_COMM_SYSTEM_PERFORMANCE_INFO             5357)
(define  DID_COMM_SYS_PARAMETER_REQ                   1283)
(define  DID_COMM_TDL_CDO                             2593)
(define  DID_COMM_TDL_CONFLICT                        1526)
(define  DID_COMM_TDL_FILTER_INFO                     5699)
(define  DID_COMM_TDL_FILTER_SETTING                  2369)
(define  DID_COMM_TDL_INFO_REQ                        5499)
(define  DID_COMM_TDL_JTDLS_COMMMAND_ORDER            5673)
(define  DID_COMM_TDL_LINK11_COMMAND_ORDER            1516)
(define  DID_COMM_TDL_MAX_RX_TRACK_COUNT              5697)
(define  DID_COMM_TDL_MAX_RX_TRACK_COUNT_SETTING      2563)
(define  DID_COMM_TDL_NTN                             1908)
(define  DID_COMM_TDL_POINTER                         1883)
(define  DID_COMM_TDL_TQ_UPDATE                       2601)
(define  DID_COMM_TDL_WEAPON_ENGAGEMENT               2425)
(define  DID_COMM_TDL_WEAPON_ENGAGEMENT_SETTING       2299)
(define  DID_COMM_TIME_AND_DATE_REQ                   1285)
(define  DID_COMM_TORPEDO_ALERT                       2293)
(define  DID_COMM_TORPEDO_ALERT_INFO                  5838)
(define  DID_COMM_TORPEDO_BITMAP_NOTIFICATION         2623)
(define  DID_COMM_WEAPON_RESTRICTION_STATE_REQ        2418)
(define  DID_COMM_WF_USER_OFFSET_VALUE_SET_REQ        1437)
(define  DID_EOTS_AIM_POINT_CTRL                      5709)
(define  DID_EOTS_AIM_POINT_STATUS                    5708)
(define  DID_EOTS_CALIBRATION_CTRL                    1468)
(define  DID_EOTS_CALIBRATION_STATUS                  1767)
(define  DID_EOTS_DIRECTOR_STATUS                     1925)
(define  DID_EOTS_EOTS_TRACK_INFO                     2297)
(define  DID_EOTS_EQUIP_CTRL                          1469)
(define  DID_EOTS_EQUIP_STATUS                        1766)
(define  DID_EOTS_FORCED_MEMORY_TRACKING_CTRL         3022)
(define  DID_EOTS_FRONT_DIRECTION_CTRL                2427)
(define  DID_EOTS_FRONT_DIRECTION_STATUS              2428)
(define  DID_EOTS_JOYSTICK_DATA                       1475)
(define  DID_EOTS_LOCK_AND_LRF_STATUS                 2521)
(define  DID_EOTS_LOCK_ON_CTRL                        2517)
(define  DID_EOTS_LRF_FIRE_ON                         2518)
(define  DID_EOTS_SECONDARY_TARGET                    2305)
(define  DID_EOTS_SECTOR_SEARCH_CTRL                  1471)
(define  DID_EOTS_SECTOR_SEARCH_STATUS                1764)
(define  DID_EOTS_SLAVE_TRACKING_CTRL                 1476)
(define  DID_EOTS_SLAVE_TRACKING_CTRL_STATUS          1765)
(define  DID_EOTS_TRACKING_CTRL                       1473)
(define  DID_EOTS_TRACKING_CTRL_STATUS                1768)
(define  DID_EOTS_TRACKING_MAIN_CTRL                  2522)
(define  DID_EOTS_TRACKING_MAIN_INFO                  2519)
(define  DID_EOTS_TRACKING_SENSOR_CTRL                1474)
(define  DID_EOTS_TRACKING_SENSOR_STATUS              1763)
(define  DID_ES_PRIMTRK_ADD_INFO                      2398)
(define  DID_ES_STATUS                                1788)
(define  DID_ES_TRK_LIST                              1566)
(define  DID_EW_BRN_LIST                              5848)
(define  DID_EW_BRN_RPT_REQ                           5857)
(define  DID_EW_BRN_SEC                               5856)
(define  DID_EW_DEL_BRN_RPT_REQ                       5858)
(define  DID_EW_EMITTER_LIST_INFO                     5867)
(define  DID_EW_EMITTER_LIST_SET_REQ                  5869)
(define  DID_EW_HK_STATUS                             5850)
(define  DID_EW_INH_JAM_SECTOR                        5868)
(define  DID_EW_INH_JAM_SECTOR_REQ                    5870)
(define  DID_EW_JAMMING_CMD                           5851)
(define  DID_EW_MAN_MODE_INFO                         5852)
(define  DID_EW_PRIMTRK_ADD_INFO                      5853)
(define  DID_EW_STATUS                                5854)
(define  DID_EW_TRK_ADD_INFO_REQ                      5859)
(define  DID_EW_TRK_LIST                              5849)
(define  DID_EW_TRK_STATUS_SET_REQ                    5855)
(define  DID_FFX_VIEW_OPERATION                       3231)
(define  DID_GENPLAN_AAW_PLAN_EDIT                    5710)
(define  DID_GENPLAN_AAW_PLAN_INFO                    1699)
(define  DID_GENPLAN_ASUW_PLAN_EDIT                   5711)
(define  DID_GENPLAN_ASUW_PLAN_INFO                   1694)
(define  DID_GENPLAN_CHARGE_EDIT                      5924)
(define  DID_GENPLAN_CHARGE_INFO                      5923)
(define  DID_GENPLAN_COMPLAN_EDIT                     5713)
(define  DID_GENPLAN_COMPLAN_INFO                     1695)
(define  DID_GENPLAN_EMCONF_EDIT                      6108)
(define  DID_GENPLAN_EMCONF_INFO                      6107)
(define  DID_GENPLAN_EMCON_EDIT                       5714)
(define  DID_GENPLAN_EMCON_INFO                       1700)
(define  DID_GENPLAN_GENERAL_EDIT                     5715)
(define  DID_GENPLAN_GENERAL_INFO                     2163)
(define  DID_GENPLAN_NBC_DISPLAY                      1702)
(define  DID_GENPLAN_NBC_DISPLAY_EDIT                 5716)
(define  DID_GENPLAN_NBC_EDIT                         5717)
(define  DID_GENPLAN_NBC_INFO                         1701)
(define  DID_GENPLAN_NGS_PLAN_EDIT                    5712)
(define  DID_GENPLAN_NGS_PLAN_INFO                    3257)
(define  DID_GENPLAN__EMCON_INFO_WINDOW_POPUP         2413)
(define  DID_GUN127_AIM_MODE_SET                      5763)
(define  DID_GUN127_AMMUNTION_SELECT_ORDER            5764)
(define  DID_GUN127_BM_AMMUNITION_INVENTORY           5720)
(define  DID_GUN127_BM_BARREL_INDICATE_POSITION       5721)
(define  DID_GUN127_BM_BARREL_INFORMATION             5722)
(define  DID_GUN127_BM_CORRECTION_DATA_ACK            5724)
(define  DID_GUN127_BM_DEFAULT_PARAMETER              5725)
(define  DID_GUN127_BM_ENG_TIME_INFO                  5726)
(define  DID_GUN127_BM_EOTS_LOCK_ON_STATUS_REQ        5727)
(define  DID_GUN127_BM_FIRE_BT_CTRL                   5728)
(define  DID_GUN127_BM_FIRE_CMD_ACK                   5729)
(define  DID_GUN127_BM_FIRE_INFO                      5730)
(define  DID_GUN127_BM_GUN_STATUS_INFO                5731)
(define  DID_GUN127_BM_HIGH_MANEUVER_TGT_INFO         5732)
(define  DID_GUN127_BM_INFO                           5733)
(define  DID_GUN127_BM_MVR_STATUS                     5757)
(define  DID_GUN127_BM_OSD_WEATHER_REQ                5758)
(define  DID_GUN127_BM_PAC_DATA_ALL                   5759)
(define  DID_GUN127_BM_RESET_TRACKING_ACK             5760)
(define  DID_GUN127_CORRECTION_DATA                   5774)
(define  DID_GUN127_CTRL_ORDER                        5765)
(define  DID_GUN127_FUZE_SET                          5766)
(define  DID_GUN127_HIGH_MANEUVER_TGT_SOLUTION        5767)
(define  DID_GUN127_HIGH_SOLUTION                     5776)
(define  DID_GUN127_MVR_SET                           5768)
(define  DID_GUN127_PAC_DATA_SET                      5769)
(define  DID_GUN127_PARA_SET                          5770)
(define  DID_GUN127_PHP_DISPLAY                       5771)
(define  DID_GUN127_STAR_SHELL_SET                    5772)
(define  DID_GUN127_THROW_OFF_SET                     5773)
(define  DID_GUN127_TRN_STATUS                        5785)
(define  DID_GUN76_AIM_MODE_SET                       5569)
(define  DID_GUN76_BM_BARREL_INDICATE_POSITION        5644)
(define  DID_GUN76_BM_BARREL_INFORMATION              5540)
(define  DID_GUN76_BM_CORRECTION_DATA_ACK             5539)
(define  DID_GUN76_BM_DEFAULT_PARAMETER               5542)
(define  DID_GUN76_BM_ENG_TIME_INFO                   5551)
(define  DID_GUN76_BM_EOTS_LOCK_ON_STATUS_REQ         5550)
(define  DID_GUN76_BM_FIRE_BT_CTRL                    5645)
(define  DID_GUN76_BM_FIRE_CMD_ACK                    5646)
(define  DID_GUN76_BM_FIRE_INFO                       5647)
(define  DID_GUN76_BM_FIRE_STATUS                     5581)
(define  DID_GUN76_BM_FIRING_DURATION_TIME_ACK        5648)
(define  DID_GUN76_BM_GUN_DAILY_FIRE_COUNT            5649)
(define  DID_GUN76_BM_GUN_STATUS_INFO                 5650)
(define  DID_GUN76_BM_INFO_FIRE_SET_INFO              5651)
(define  DID_GUN76_BM_INFO_MAIN                       5652)
(define  DID_GUN76_BM_OSD_WEATHER_REQ                 5548)
(define  DID_GUN76_BM_PAC_DATA_ALL                    5653)
(define  DID_GUN76_BM_RESET_TRACKING_ACK              5552)
(define  DID_GUN76_CORRECTION_DATA                    5567)
(define  DID_GUN76_CTRL_ORDER                         5565)
(define  DID_GUN76_DAILY_FIRE_COUNT                   5571)
(define  DID_GUN76_DEFAULT_PARA_REQ                   5572)
(define  DID_GUN76_FIRING_DURATION_TIME               5641)
(define  DID_GUN76_NGS_CORRECTION_DATA                5578)
(define  DID_GUN76_PAC_DATA_SET                       5558)
(define  DID_GUN76_PARA_SET                           5563)
(define  DID_GUN76_PHP_DISPLAY                        5642)
(define  DID_GUN76_THROW_OFF_SET                      5643)
(define  DID_GUN76_TRN_STATUS                         5659)
(define  DID_GUN76_TRN_STATUS_REQ                     5660)
(define  DID_GUN_BM_AMMUNITION_INVENTORY              2540)
(define  DID_GUN_BM_MVR_STATUS                        3030)
(define  DID_HMS_BEARING_LIST                         5903)
(define  DID_HMS_ENERGYSPECTRUM                       5894)
(define  DID_HMS_HMSINFO                              5895)
(define  DID_HMS_MAX_SENSE_RANGE                      5896)
(define  DID_HMS_MAX_SENSE_RANGE_INFO                 5904)
(define  DID_HMS_PRIMTRK_ADD_INFO                     5897)
(define  DID_HMS_RADAR_TRACK                          5901)
(define  DID_HMS_RANGE                                5939)
(define  DID_HMS_SONAR_ORDER                          5902)
(define  DID_HMS_SONAR_ORDER_ACK                      5898)
(define  DID_HMS_TORPEDO_ALERT_LIST                   5905)
(define  DID_HMS_TORPEDO_DETECT_DISP                  5899)
(define  DID_HMS_TORPEDO_DISCERN_DISP                 5900)
(define  DID_IFF_BDS_DISP_DATA                        5394)
(define  DID_IFF_BIT_INFO                             1967)
(define  DID_IFF_CODE_SET                             1477)
(define  DID_IFF_CODE_STATUS                          1623)
(define  DID_IFF_EQUIP_CTRL                           3088)
(define  DID_IFF_EQUIP_CTRL_ACK                       3270)
(define  DID_IFF_EQUIP_STATUS                         3089)
(define  DID_IFF_INTERROGATE_STATUS                   1966)
(define  DID_IFF_MODE1_STATUS                         1625)
(define  DID_IFF_MODE2_STATUS                         1626)
(define  DID_IFF_MODE3A_STATUS                        1627)
(define  DID_IFF_MODE3A_TIME                          2122)
(define  DID_IFF_MODE_DATA                            1624)
(define  DID_IFF_MODE_INFO_REQ                        2500)
(define  DID_IFF_PRIMTRK_ADD_INFO                     5344)
(define  DID_IFF_RADAR_SILENCE_CTRL_ACK               2214)
(define  DID_IISS_GFE_MESSAGE                         5916)
(define  DID_INFRA_IPN_WC_INIT_CTRL                   5582)
(define  DID_IPNTRN_GUN_AMMOLIST                      2608)
(define  DID_IPNTRN_IFF_STATUS                        5657)
(define  DID_IRST_MODE_CTRL                           6215)
(define  DID_IRST_PANORAMIC_CTRL                      6216)
(define  DID_IRST_PANORAMIC_REQ                       6225)
(define  DID_IRST_PANORAMIC_STATUS                    6220)
(define  DID_IRST_POWER_CTRL                          6229)
(define  DID_IRST_POWER_STATUS                        6232)
(define  DID_IRST_PRIMTRK_ADD_INFO                    6234)
(define  DID_IRST_SEARCH_SECTOR_CTRL                  6219)
(define  DID_IRST_SEARCH_SECTOR_STATUS                6223)
(define  DID_IRST_SECTOR_SURVEIL_CTRL                 6217)
(define  DID_IRST_SECTOR_SURVEIL_REQ                  6224)
(define  DID_IRST_SECTOR_SURVEIL_STATUS               6221)
(define  DID_IRST_SENSOR_CONFIG_CTRL                  6230)
(define  DID_IRST_SENSOR_CONFIG_STATUS                6231)
(define  DID_IRST_STATUS                              5740)
(define  DID_IRST_TRK_LIST                            5937)
(define  DID_ISDL_AIRCRAFT_SHIP_CONTROL               1874)
(define  DID_ISDL_AIRCRAFT_SHIP_CONTROL_SETTING       2115)
(define  DID_ISDL_ASSOCIATION                         1875)
(define  DID_ISDL_COMMAND                             1877)
(define  DID_ISDL_COMMAND_LIST                        2489)
(define  DID_ISDL_COMMAND_ORDER_ACK                   2512)
(define  DID_ISDL_CORRELATION_STATUS                  1863)
(define  DID_ISDL_ENGAGEMENT_STATUS                   1878)
(define  DID_ISDL_GEN_CTRL_ACK                        1880)
(define  DID_ISDL_GEN_CTRL_SETTING                    1536)
(define  DID_ISDL_INFORMATION_DIFFERENCE_REPORT       1867)
(define  DID_ISDL_MAIN_WND_INFO                       2485)
(define  DID_ISDL_NETWORK_TRACK_ADD_INFO              2582)
(define  DID_ISDL_NTN                                 1868)
(define  DID_ISDL_OPNOTE_INFO                         5700)
(define  DID_ISDL_OPNOTE_SEND                         1617)
(define  DID_ISDL_PU_TABLE_CONFIG                     2577)
(define  DID_ISDL_PU_TABLE_CONFIG_SETTING             2584)
(define  DID_ISDL_REMOTE_TRACK_LIST                   2492)
(define  DID_ISDL_REMOTE_TRACK_SEARCH_SETTING         2455)
(define  DID_ISDL_TDL_OPNOTE_INFO                     1881)
(define  DID_ISDL_TDL_OPNOTE_SEND                     5701)
(define  DID_ISDL_TDL_RESILIENCE                      6127)
(define  DID_ISDL_TRACK_ALERT                         1872)
(define  DID_ISDL_TRACK_HOOKING_REQ                   2587)
(define  DID_ISDL_WEAPON_STATUS                       1884)
(define  DID_JTDLS_ADMISSION_RESPONSE                 5622)
(define  DID_JTDLS_ALERT_LIST                         5635)
(define  DID_JTDLS_COMMAND_LINE                       5666)
(define  DID_JTDLS_COMMAND_LIST                       5624)
(define  DID_JTDLS_CONTROL_UNIT_CHANGE                6179)
(define  DID_JTDLS_CORREATION                         5625)
(define  DID_JTDLS_ENGAGEMENT_STATUS_LIST             5626)
(define  DID_JTDLS_FILTER                             6180)
(define  DID_JTDLS_FREETEXT                           6185)
(define  DID_JTDLS_FREETEXT_LIST                      5639)
(define  DID_JTDLS_HANDOVER                           6177)
(define  DID_JTDLS_IDENTIFIER_LIST                    6184)
(define  DID_JTDLS_MISSION_ASSIGNMENT                 6174)
(define  DID_JTDLS_NETWORK_TRACK_ADD_INFO             5623)
(define  DID_JTDLS_NETWORK_TRACK_ADD_INFO_FOR_MD      5667)
(define  DID_JTDLS_NETWORK_TRACK_ASSOCIATION_LIST     5627)
(define  DID_JTDLS_NETWORK_TRACK_PAIRING_LIST         5628)
(define  DID_JTDLS_SHAPE_LIST                         5640)
(define  DID_JTDLS_TARGET_SORTING_LIST                5654)
(define  DID_JTDLS_THREAT_WARNING_LIST                5629)
(define  DID_JTDLS_TRACK_SEND_RESULT                  5655)
(define  DID_JTDLS_VECTOR                             6176)
(define  DID_KEYBOARD_SHORTCUTS                       5398)
(define  DID_KNCCS_KNCCS_TRACK_LIST                   1860)
(define  DID_KNCCS_STATUS_INFO                        1861)
(define  DID_KSAAM_BREAK_ENG_COMPLETED                5799)
(define  DID_KSAAM_DESIGNATION                        5798)
(define  DID_KSAAM_DOCTRINE_REQ                       6080)
(define  DID_KSAAM_DOCTRINE_SETTINGS                  5800)
(define  DID_KSAAM_DOCTRINE_SETTINGS_REQ              5824)
(define  DID_KSAAM_EMERGENCY_DESTRUCTION              6081)
(define  DID_KSAAM_EMERGENCY_DESTRUCTION_REQ          5814)
(define  DID_KSAAM_FIRE_BT_CTRL                       5805)
(define  DID_KSAAM_JET_VANES_REPORT                   5806)
(define  DID_KSAAM_LAUNCH_STATUS                      5801)
(define  DID_KSAAM_LOCAL_TGT_CMD                      6079)
(define  DID_KSAAM_LOCAL_TGT_STATUS                   6077)
(define  DID_KSAAM_MISSILE_TRAJECTORY_DATA            5810)
(define  DID_KSAAM_REPEATBACK                         5802)
(define  DID_KSAAM_STATUS                             5804)
(define  DID_KSAAM_STATUS_REQ                         6078)
(define  DID_KSSM_ENGAGEMENT_ORDER                    5743)
(define  DID_KSSM_ENGAGEMENT_ORDER_REQ                5744)
(define  DID_KSSM_ENGAGEMENT_PLAN                     5751)
(define  DID_KSSM_ENGAGEMENT_STATUS                   5748)
(define  DID_KSSM_EQUIPMENT_STATUS                    5749)
(define  DID_KSSM_INTERFACE_CONTROL                   5753)
(define  DID_KSSM_PLAN_APPROVAL                       5754)
(define  DID_KSSM_PLAN_PROFILE                        5752)
(define  DID_KSSM_STATUS_INFO_REQ                     5755)
(define  DID_KSSM_TDA_DISPLAY                         5756)
(define  DID_KSSM_TGT_INFO                            5745)
(define  DID_KSSM_TGT_INFO_REQ                        5746)
(define  DID_KSSM_TRACK_DATA_MSG                      5747)
(define  DID_KSSM_TRACK_REQUEST                       5750)
(define  DID_KTSLM_ENGAGEMENT_ORDER                   5761)
(define  DID_KTSLM_ENGAGEMENT_ORDER_REQ               5777)
(define  DID_KTSLM_ENGAGEMENT_PLAN                    5790)
(define  DID_KTSLM_ENGAGEMENT_STATUS                  5778)
(define  DID_KTSLM_EQUIPMENT_STATUS                   5779)
(define  DID_KTSLM_INTERFACE_CONTROL                  5792)
(define  DID_KTSLM_PLAN_APPROVAL                      5793)
(define  DID_KTSLM_PLAN_PROFILE                       5791)
(define  DID_KTSLM_STATUS_INFO_REQ                    5794)
(define  DID_KTSLM_TDA_DISPLAY                        5795)
(define  DID_KTSLM_TGT_INFO                           5762)
(define  DID_KTSLM_TGT_INFO_REQ                       5780)
(define  DID_KTSLM_TRACK_DATA_MSG                     5775)
(define  DID_KTSLM_TRACK_REQUEST                      5781)
(define  DID_KVLA_ENG_INFO_LIST                       5871)
(define  DID_KVLA_ENG_PLAN_APPROVAL_CMD               5861)
(define  DID_KVLA_ENG_PLAN_DISPLAY_INFO               6194)
(define  DID_KVLA_ENG_PLAN_DISPLAY_ONFOFF             6195)
(define  DID_KVLA_ENG_STATUS                          5862)
(define  DID_KVLA_FIRE_PERMIT_CMD                     5863)
(define  DID_KVLA_INHIBIT_REQ                         6211)
(define  DID_KVLA_KVLS_STATUS                         6204)
(define  DID_KVLA_SECTOR_TRACK_INFO                   6190)
(define  DID_KVLA_STATUS_INFO                         5864)
(define  DID_KVLA_TARGET_INDICATION                   5860)
(define  DID_KVLA_TI_SET_REQ                          5865)
(define  DID_KVLA_TORPEDO_SET_REQ                     5866)
(define  DID_LINK11_ADMISSION                         6097)
(define  DID_LINK11_ADMISSION_SETTING                 6091)
(define  DID_LINK11_AIRCRAFT_CONTROL                  6098)
(define  DID_LINK11_AIRCRAFT_CONTROL_ORDER_SETTING    6092)
(define  DID_LINK11_AIRCRAFT_MISSION_STATUS           6103)
(define  DID_LINK11_AIRCRAFT_MISSION_STATUS_SETTING   6093)
(define  DID_LINK11_COMMAND_LINE                      6111)
(define  DID_LINK11_COMMAND_ORDER                     6099)
(define  DID_LINK11_COMMAND_ORDER_SETTING             6112)
(define  DID_LINK11_CONFLICT                          6100)
(define  DID_LINK11_DP_INPUT                          6226)
(define  DID_LINK11_DTS_CONTROL_DATA                  6101)
(define  DID_LINK11_DTS_CONTROL_DATA_SETTING          6094)
(define  DID_LINK11_DTS_NDDSINTF                      6228)
(define  DID_LINK11_IP_INPUT                          6227)
(define  DID_LINK11_LOOPTEST_SETTING                  6095)
(define  DID_LINK11_NETWORK_TRACK_ADD_INFO            6110)
(define  DID_LINK11_OPNOTE_SETTING                    6096)
(define  DID_LINK11_TDL_OPNOTE_INFO                   6104)
(define  DID_LINK11_TEST_RESULT                       6102)
(define  DID_LINKK_FREETEXT_LIST                      5636)
(define  DID_LINK_COMMAND_RESPONSE                    6197)
(define  DID_LYNXESM_HELI_INFO                        5737)
(define  DID_LYNXESM_PRIMTRK_ADD_INFO                 5736)
(define  DID_LYNXESM_STATUS                           5738)
(define  DID_LYNXESM_TRK_INFO_REQ                     5739)
(define  DID_LYNXESM_TRK_LIST                         5735)
(define  DID_MASS_CLOUD_DATA                          5607)
(define  DID_MASS_CRITERIA                            5614)
(define  DID_MASS_CRITERIA_REQ                        5682)
(define  DID_MASS_ENG_INFO_LIST                       2536)
(define  DID_MASS_ENG_REPORT                          5608)
(define  DID_MASS_ER_MSG                              5936)
(define  DID_MASS_HK_STATUS                           5615)
(define  DID_MASS_RESOURCE_STATUS                     5609)
(define  DID_MASS_STATUS                              5610)
(define  DID_MASS_TD_MSG                              5611)
(define  DID_MASS_TI_LIST                             5612)
(define  DID_MASS_TI_SET_REQ                          5618)
(define  DID_MASS_TQ_LIST                             5613)
(define  DID_MCS_GUN_FIRE_CMD                         1269)
(define  DID_MCS_KSAAM_FIRE_CMD                       1271)
(define  DID_MCS_RCWS_FIRE_CMD                        5663)
(define  DID_MCS_ROCKET_FIRE_CMD                      5664)
(define  DID_MCS_SIMROCKET_FIRE_CMD                   6246)
(define  DID_MCS_SLTS_FIRE_CMD                        1270)
(define  DID_MCS_TACM_FIRE_CMD                        1272)
(define  DID_MD_COORD_CHANGE                          6209)
(define  DID_MD_HIGH_MANEUVER_PHP_INFO                2607)
(define  DID_MD_TDL_AIRCRAFT_CONTROL_INFO             2461)
(define  DID_MD_TDL_POINTER                           1537)
(define  DID_MD_TDL_TRAINING_TRACK_CONFIRM            2499)
(define  DID_MD_TM_LINK_SEND_CANCEL                   1265)
(define  DID_MD_TM_MANUAL_CANCEL                      2590)
(define  DID_MD_TM_MANUAL_FUSION                      1262)
(define  DID_MD_TM_SURF_TRACKING_INITIATION           2123)
(define  DID_MD_TM_SURF_TRACKING_SELECTION            5922)
(define  DID_MD_WF_ENG_CH_LIST_REQ                    1435)
(define  DID_MFC_JTDLS_ADMISSION_SETTTING             5621)
(define  DID_MFC_JTDLS_ALERT_RES                      6181)
(define  DID_MFC_JTDLS_ASS_PAI                        6168)
(define  DID_MFC_JTDLS_COMMAND                        6167)
(define  DID_MFC_JTDLS_CONTROL_UNIT_CHANGE            6165)
(define  DID_MFC_JTDLS_CORRELATION_REQ                5632)
(define  DID_MFC_JTDLS_ENGAGEMENT                     6169)
(define  DID_MFC_JTDLS_FILTER_SETTING                 5637)
(define  DID_MFC_JTDLS_FREETEXT_TX                    5661)
(define  DID_MFC_JTDLS_INFO_REQ                       5633)
(define  DID_MFC_JTDLS_MISSION_ASSIGNMENT             6175)
(define  DID_MFC_JTDLS_NTDB_CLEAR                     5630)
(define  DID_MFC_JTDLS_SET_OWNSHIP_INFO               5634)
(define  DID_MFC_JTDLS_SHAPE                          6171)
(define  DID_MFC_JTDLS_TARGET_SORTING                 6166)
(define  DID_MFC_JTDLS_THREAT_WARNING                 6172)
(define  DID_MFC_JTDLS_TRACK_ADD_INFO                 6170)
(define  DID_MFC_JTDLS_VECTOR                         6164)
(define  DID_MFC_JTDL_HANDOVER                        6178)
(define  DID_MFC_SIMKSAAM_FIRE_CMD                    6212)
(define  DID_MFC_TM_MANUAL_TRACK_WIPE                 2022)
(define  DID_MFC_TRN_IFF_STATUS_REQ                   2416)
(define  DID_NAV_ANCH_RUN                             1258)
(define  DID_NAV_ANCH_RUN_ACK                         1585)
(define  DID_NAV_ARRIVE_RUN                           1254)
(define  DID_NAV_ARRIVE_RUN_ACK                       1581)
(define  DID_NAV_COASTSAIL_INFO                       1252)
(define  DID_NAV_COASTSAIL_INFO_ACK                   1579)
(define  DID_NAV_COLL_INFO                            1251)
(define  DID_NAV_COLL_INFO_ACK                        1577)
(define  DID_NAV_COLL_TRACK_INFO                      1578)
(define  DID_NAV_CPA_INFO                             2550)
(define  DID_NAV_CPA_REQ                              2551)
(define  DID_NAV_DISPLAY_ANCH                         2653)
(define  DID_NAV_DISPLAY_ANCH_COMPLETE                5681)
(define  DID_NAV_DISPLAY_ARRIVE                       2654)
(define  DID_NAV_DISPLAY_COLL                         5680)
(define  DID_NAV_DISPLAY_CPA                          2655)
(define  DID_NAV_DISPLAY_DIST                         2656)
(define  DID_NAV_DISPLAY_LOWSAIL                      3240)
(define  DID_NAV_DISPLAY_SAIL                         2657)
(define  DID_NAV_DISPLAY_SCOUT                        2658)
(define  DID_NAV_DISPLAY_STAT                         2659)
(define  DID_NAV_DISPLAY_ZIG                          2660)
(define  DID_NAV_DIST_RUN                             1255)
(define  DID_NAV_DIST_RUN_ACK                         1582)
(define  DID_NAV_KEEP_SAIL_RUN                        5676)
(define  DID_NAV_KEEP_SAIL_RUN_ACK                    5679)
(define  DID_NAV_RESCUE_RUN                           5677)
(define  DID_NAV_RESCUE_RUN_ACK                       5678)
(define  DID_NAV_SAIL_PLAN                            1249)
(define  DID_NAV_SAIL_PLAN_ACK                        1575)
(define  DID_NAV_SAIL_RUN                             1250)
(define  DID_NAV_SAIL_RUN_ACK                         1576)
(define  DID_NAV_SCOUT_RUN                            2120)
(define  DID_NAV_SCOUT_RUN_ACK                        2121)
(define  DID_NAV_STAT_RUN                             1253)
(define  DID_NAV_STAT_RUN_ACK                         1580)
(define  DID_NAV_ZIG_PLAN                             1256)
(define  DID_NAV_ZIG_PLAN_ACK                         1583)
(define  DID_NAV_ZIG_RUN                              1257)
(define  DID_NAV_ZIG_RUN_ACK                          1584)
(define  DID_NMM_AREA                                 5409)
(define  DID_NMM_MGR                                  5410)
(define  DID_NRS_TRACK_INFO                           5335)
(define  DID_OBSERVER_POS_DISPLAY                     6109)
(define  DID_OSD_ALTITUDE_WEATHER_INFO                1637)
(define  DID_OSD_AUTOHISTORY_DATA_RESIL               5694)
(define  DID_OSD_AUTOHISTORY_LIST_RESIL               5696)
(define  DID_OSD_COMMON_DATA_RESIL                    5688)
(define  DID_OSD_ENV_CTRL                             1485)
(define  DID_OSD_ENV_INFO                             1636)
(define  DID_OSD_HISTORY_CTRL                         1486)
(define  DID_OSD_HISTORY_DATA_RESIL                   5693)
(define  DID_OSD_HISTORY_INFO                         1633)
(define  DID_OSD_HISTORY_LIST_INFO_RESIL              5692)
(define  DID_OSD_HISTORY_LIST_RESIL                   5695)
(define  DID_OSD_INFO                                 1634)
(define  DID_OSD_NECODE_CHANGE                        5323)
(define  DID_OSD_NECODE_CTRL                          2315)
(define  DID_OSD_NECODE_INFO                          2316)
(define  DID_OSD_NECODE_RESIL                         5691)
(define  DID_OSD_OSD_CTRL                             1488)
(define  DID_OSD_SAIL_DISPPLAY                        2588)
(define  DID_OSD_STAB                                 2548)
(define  DID_OSD_STAB_OSD                             2381)
(define  DID_OSD_USE_FLAG_RESIL                       5690)
(define  DID_OSD_WEATHER_CTRL                         1489)
(define  DID_OSD_WEATHER_INFO_RESIL                   5689)
(define  DID_RCWS_BREAK_ENG                           6203)
(define  DID_RCWS_BREAK_ENG_COMPLETED                 6189)
(define  DID_RCWS_ENG_CONTROL                         6192)
(define  DID_RCWS_ENG_STATUS                          5671)
(define  DID_RCWS_FIRE_BT_CTRL                        5675)
(define  DID_RCWS_FIRING_CONTROL                      6191)
(define  DID_RCWS_SECTOR_TRACK_INFO                   6193)
(define  DID_RCWS_SECTOR_TRACK_REQ                    6202)
(define  DID_RCWS_STATUS                              5670)
(define  DID_RCWS_TD_LIST                             5672)
(define  DID_RCWS_TD_MSG                              5669)
(define  DID_RES_NAV_DIST                             5706)
(define  DID_RES_NAV_PLAN                             5702)
(define  DID_RES_NAV_SCOUT                            5704)
(define  DID_RES_NAV_STAT                             5707)
(define  DID_RES_NAV_ZIG_RUN                          5705)
(define  DID_RM_ALL_TARGET_POSITION_INFO              5580)
(define  DID_ROCKET_BREAK_ENG_COMPLETED               6129)
(define  DID_ROCKET_DESIGNATION                       6116)
(define  DID_ROCKET_DOCTRINE_SETTINGS                 6113)
(define  DID_ROCKET_DOCTRINE_SETTINGS_REQ             6114)
(define  DID_ROCKET_EMERGENCY_DESTRUCTION_REQ         6131)
(define  DID_ROCKET_FIRE_BT_CTRL                      5674)
(define  DID_ROCKET_REPEATBACK                        6128)
(define  DID_ROCKET_STATUS                            6115)
(define  DID_ROCKET_TRAJECTORY_DATA                   6130)
(define  DID_RVDUTVD_SELECT_TV_VIDEO_ACK              2407)
(define  DID_RVDUTVD_STATUS                           2534)
(define  DID_RVDUTVD_TV_CONNECTION_STATUS             2025)
(define  DID_RVP_FILE_DELETE_ACK                      2394)
(define  DID_RVP_RNR_CMD_ACK                          2391)
(define  DID_RVP_RVD_STATUS                           5719)
(define  DID_RVP_RVR_STATUS                           2533)
(define  DID_RVR_FILE_LIST_ACK                        2393)
(define  DID_SD_HCISET_SAVE                           6118)
(define  DID_SD_LOGOFF                                6210)
(define  DID_SIMCIWS_STATUS                           5830)
(define  DID_SIMCIWS_STATUS_REQ                       5831)
(define  DID_SIMEOTS_STATUS                           2126)
(define  DID_SIMEOTS_STATUS_REQ                       2132)
(define  DID_SIMES_STATUS                             1791)
(define  DID_SIMES_STATUS_REQ                         1459)
(define  DID_SIMEW_STATUS                             6083)
(define  DID_SIMEW_STATUS_REQ                         6084)
(define  DID_SIMGUN127_TRN_RELOAD_AMMO                6073)
(define  DID_SIMGUN127_TRN_STATUS                     6074)
(define  DID_SIMGUN127_TRN_STATUS_REQ                 6106)
(define  DID_SIMHMS_STATUS                            6085)
(define  DID_SIMHMS_STATUS_REQ                        6087)
(define  DID_SIMIRST_SECTOR_SURVEIL_CTRL              6241)
(define  DID_SIMIRST_SECTOR_SURVEIL_REQ               6236)
(define  DID_SIMIRST_SECTOR_SURVEIL_STATUS            6237)
(define  DID_SIMIRST_STATUS                           5741)
(define  DID_SIMIRST_STATUS_REQ                       5742)
(define  DID_SIMIRST_TRN_SECTOR_SURVEIL_REQ           6235)
(define  DID_SIMKSSM_STATUS                           6090)
(define  DID_SIMKSSM_STATUS_REQ                       6089)
(define  DID_SIMKTSLM_STATUS                          6133)
(define  DID_SIMKTSLM_STATUS_REQ                      6134)
(define  DID_SIMKTSLM_WAYPOINT_INFO                   6214)
(define  DID_SIMKVLA_FIRE_PLAN_SET_INFO               6201)
(define  DID_SIMKVLA_FIRE_PLAN_SET_INFO_ACK           6213)
(define  DID_SIMKVLA_STATUS_INFO_REQ                  6198)
(define  DID_SIMMASS_STATUS                           5619)
(define  DID_SIMMASS_STATUS_REQ                       5620)
(define  DID_SIMNRS_STATUS                            6076)
(define  DID_SIMNRS_STATUS_REQ                        6105)
(define  DID_SIMRCWS_FIRE_BT_INPUT                    6245)
(define  DID_SIMRCWS_STATUS                           5687)
(define  DID_SIMRCWS_STATUS_REQ                       5683)
(define  DID_SIMROCKET_STATUS                         6243)
(define  DID_SIMROCKET_STATUS_REQ                     6199)
(define  DID_SIMROCKET_SWITCH_CMD                     6242)
(define  DID_SIMROCKET_TD_LIST                        6244)
(define  DID_SIMSLTS_STATUS                           1848)
(define  DID_SIMSLTS_STATUS_REQ                       5832)
(define  DID_SIMSRS_STATUS                            2124)
(define  DID_SIMSRS_STATUS_REQ                        2130)
(define  DID_SIMTASS_STATUS                           1795)
(define  DID_SIMTASS_STATUS_REQ                       1460)
(define  DID_SKP_COMMAND                              2591)
(define  DID_SLTS_DOGBOX_DISPLAY_INFO                 5803)
(define  DID_SLTS_ENG_INFO                            5796)
(define  DID_SLTS_FIRE_BT_CTRL                        5782)
(define  DID_SLTS_FIRE_DATA_SET_REQ                   5788)
(define  DID_SLTS_LAUNCHER_TUBE_DATA_SET_REQ          5787)
(define  DID_SLTS_STATUS_INFO                         5783)
(define  DID_SLTS_STATUS_SET_REQ                      5786)
(define  DID_SLTS_TORPEDO_INFO_SET_REQ                5789)
(define  DID_SLTS_WF_DATA                             5784)
(define  DID_SLTS_WF_LIST                             5797)
(define  DID_SM_ALERT_RESULT                          1389)
(define  DID_SM_ALLOC_STATUS_COMMAND                  6206)
(define  DID_SM_ALLOC_STATUS_CONTROL                  6205)
(define  DID_SM_ALLOC_STATUS_REPORT                   5684)
(define  DID_SM_ALL_SYS_STATUS_INFO                   1591)
(define  DID_SM_ASSIGNMENT_INFO                       2496)
(define  DID_SM_AUTH_CHANGE_REQ                       2529)
(define  DID_SM_DISP_ALERT                            6247)
(define  DID_SM_HB_INFO                               5665)
(define  DID_SM_HCISET_INFO                           6117)
(define  DID_SM_INCORRECT_MSG                         1588)
(define  DID_SM_INF_HISTORY_INFO                      2161)
(define  DID_SM_INF_HISTORY_INFO_REQ                  6070)
(define  DID_SM_LOGOUT_CMD                            2531)
(define  DID_SM_LOG_CONTROL_CMD                       2541)
(define  DID_SM_MODE_ALLOCATION_INFO                  5418)
(define  DID_SM_MODE_CHANGE_CMD                       2139)
(define  DID_SM_MODE_CHANGE_REQ                       2138)
(define  DID_SM_MODE_CHANGE_STATUS                    5328)
(define  DID_SM_MODE_ENV_SET_CMD                      6182)
(define  DID_SM_MODE_FG_NODE_REL_INFO                 5419)
(define  DID_SM_MODE_STATUS_INFO                      1586)
(define  DID_SM_NET_POLL_TIME_AND_THRESHOLD_EDIT      1305)
(define  DID_SM_NMS_INFO_REQ                          1287)
(define  DID_SM_NMS_NET_PERFORM                       1710)
(define  DID_SM_NMS_NET_POLL_TIME_AND_THRESHOLD       1714)
(define  DID_SM_NMS_PORT_STATISTIC                    1713)
(define  DID_SM_NMS_PORT_STATUS                       1712)
(define  DID_SM_NMS_PORT_USAGE                        1711)
(define  DID_SM_NMS_RESILIENCE                        5464)
(define  DID_SM_NMS_SYSTEM_STATUS_INFO                1706)
(define  DID_SM_NMS_SYS_INFO                          1707)
(define  DID_SM_NMS_SYS_PERFORM                       1708)
(define  DID_SM_NMS_SYS_POLL_TIME_AND_THRESHOLD       1715)
(define  DID_SM_NMS_SYS_STATUS                        1709)
(define  DID_SM_OPER_IDPW_CHANGE_REQ                  1281)
(define  DID_SM_OPER_INFO                             2472)
(define  DID_SM_OPER_INFO_EDIT                        5453)
(define  DID_SM_OPER_LOGIN_INFO                       2493)
(define  DID_SM_OPER_LOGIN_REQ                        1279)
(define  DID_SM_OPER_ROLE_INFO                        1587)
(define  DID_SM_PRE_CONDITION_INFO                    5698)
(define  DID_SM_ROLE_INFO                             2467)
(define  DID_SM_ROLE_INFO_EDIT                        5454)
(define  DID_SM_ROLE_LOGIN_REQ                        2494)
(define  DID_SM_ROLE_SERVICE_INFO                     1589)
(define  DID_SM_SERVICE_GROUP_INFO                    2516)
(define  DID_SM_SERVICE_INFO                          5451)
(define  DID_SM_SUBSYSTEM_STATUS_INFO_REQ             2832)
(define  DID_SM_SYSTEM_PERFORMANCE_INFO_REQ           5358)
(define  DID_SM_SYS_DETAIL_INFO                       5322)
(define  DID_SM_SYS_PARA_FILE_RESULT                  5685)
(define  DID_SM_SYS_PARA_FILE_UPDATE                  5686)
(define  DID_SM_SYS_PARA_VAL                          1592)
(define  DID_SM_SYS_PARA_VAL_EDIT                     5461)
(define  DID_SM_SYS_POLL_TIME_AND_THRESHOLD_EDIT      1306)
(define  DID_SM_TIME_AND_DATE                         1593)
(define  DID_SM_TIME_AND_DATE_EDIT                    5462)
(define  DID_SM_UPS_TECH_STATUS_INFO                  5417)
(define  DID_SM_USERMANAGER_INFO_EDIT_STATUS          5450)
(define  DID_SRS_CLIMATE_STATE_REPORT                 1939)
(define  DID_SRS_JAMMER_MAP                           3256)
(define  DID_SRS_RADAR_STATUS                         1949)
(define  DID_SRS_SLK500_CLIMATE_STATE_REPORT          5833)
(define  DID_SRS_SLK500_CLUTTER_THRESHOLD_CTRL        5935)
(define  DID_SRS_SLK500_CLUTTER_THRESHOLD_STATUS      5912)
(define  DID_SRS_SLK500_EQUIP_CTRL                    5917)
(define  DID_SRS_SLK500_EQUIP_STATUS                  5906)
(define  DID_SRS_SLK500_JAMMER_MAP                    5834)
(define  DID_SRS_SLK500_JAMMER_STROBE_REPORT          5920)
(define  DID_SRS_SLK500_RADAR_VIDEO_STATUS            5908)
(define  DID_SRS_SLK500_RF_CHANNEL_CTRL               5918)
(define  DID_SRS_SLK500_RF_CHANNEL_STATUS             5909)
(define  DID_SRS_SLK500_SECTOR_CTRL                   5919)
(define  DID_SRS_SLK500_SECTOR_REPORT                 5910)
(define  DID_SRS_SLK500_SRS_TRACK_INFO                5913)
(define  DID_SRS_SLK500_TWS_B_SCOPE_REPORT            5911)
(define  DID_SRS_SLK500_TWS_CALIBRATION               5914)
(define  DID_SRS_SLK500_TWS_TRACK_INFO                5915)
(define  DID_SRS_SLK500_VIDEO_CTRL                    5921)
(define  DID_SRS_SRS_SHUTDOWN_ACK                     1942)
(define  DID_SRS_TWS_CTRL_ACK                         1929)
(define  DID_SRS_XSPS550K_EQUIP_CTRL                  1491)
(define  DID_SRS_XSPS550K_EQUIP_STATUS                1738)
(define  DID_SRS_XSPS550K_JAMMER_STROBE_REPORT        1932)
(define  DID_SRS_XSPS550K_RADAR_VIDEO_STATUS          1950)
(define  DID_SRS_XSPS550K_RF_CHANNEL_CTRL             1494)
(define  DID_SRS_XSPS550K_RF_CHANNEL_STATUS           2309)
(define  DID_SRS_XSPS550K_SECTOR_CTRL                 1495)
(define  DID_SRS_XSPS550K_SECTOR_REPORT               1933)
(define  DID_SRS_XSPS550K_SRS_TRACK_INFO              2574)
(define  DID_SRS_XSPS550K_TWS_B_SCOPE_REPORT          1928)
(define  DID_SRS_XSPS550K_TWS_CALIBRATION             1926)
(define  DID_SRS_XSPS550K_TWS_TRACK_INFO              1927)
(define  DID_SRS_XSPS550K_VIDEO_CTRL                  1498)
(define  DID_SS_ALL_SELECT_TV_STATUS                  5367)
(define  DID_SS_ALL_SELECT_TV_STATUS_INFO             5442)
(define  DID_SS_ALL_SELECT_TV_STATUS_REQ              5368)
(define  DID_SS_AUDIO_DISTRIBUTE_CMD                  5443)
(define  DID_SS_AW_RESIL_INFO                         5420)
(define  DID_SS_COA_OPERATION                         3232)
(define  DID_SS_DISP_DISTRIBUTE_INFO                  2302)
(define  DID_SS_DISP_UPDOWN_SELECT                    3254)
(define  DID_SS_DRAW_SERVICE                          2819)
(define  DID_SS_FOC_DATA_TB                           5503)
(define  DID_SS_FOC_INFO                              1725)
(define  DID_SS_FOC_REQ                               1388)
(define  DID_SS_FOC_RESIL_INFO                        5528)
(define  DID_SS_HINDRANCE_INFO                        3247)
(define  DID_SS_HINDRANCE_REQ                         3246)
(define  DID_SS_ICM_RECEIVE                           1724)
(define  DID_SS_ICM_SEND                              1387)
(define  DID_SS_MSG_RECEIVE                           1723)
(define  DID_SS_MSG_SEND                              1386)
(define  DID_SS_PLATFORMLIB_EQUIP_INFO                3248)
(define  DID_SS_PLATFORMLIB_EQUIP_REQ                 3253)
(define  DID_SS_PLATFORMLIB_LINK_INFO                 3249)
(define  DID_SS_PLATFORMLIB_LINK_REQ                  3250)
(define  DID_SS_PLATFORMLIB_TRACK_QUERY               2116)
(define  DID_SS_PLATFORMLIB_UNIT_INFO                 3252)
(define  DID_SS_PLATFORMLIB_UNIT_REQ                  3251)
(define  DID_SS_RNR_SYNC                              2600)
(define  DID_SS_RVP_FILE_DELETE_CMD                   2389)
(define  DID_SS_RVP_PLAY_SPEED_CMD                    5927)
(define  DID_SS_RVP_RNR_CMD                           2386)
(define  DID_SS_RVP_RNR_STATUS                        3090)
(define  DID_SS_RVR_FILE_LIST_REQ                     2388)
(define  DID_SS_SELECT_TV_INFO                        5361)
(define  DID_SS_STATUS_INFO                           1737)
(define  DID_SS_SUB_PREDICTION_POS                    5413)
(define  DID_SS_TACINFO_COMMAND                       2611)
(define  DID_SS_TACINFO_COMMAND_ACK                   2612)
(define  DID_SS_TAC_FILE_DELETE_ACK                   5930)
(define  DID_SS_TAC_FILE_DELETE_CMD                   5926)
(define  DID_SS_TAC_PLAY_SPEED_CMD                    5929)
(define  DID_SS_TAC_RNR_CMD                           5925)
(define  DID_SS_TAC_RNR_CMD_ACK                       5931)
(define  DID_SS_TAC_RNR_STATUS                        6187)
(define  DID_SS_TAC_STATUS                            5932)
(define  DID_SS_TAC_SYNC_INFO                         5460)
(define  DID_SS_TA_GROUP_INFO                         3241)
(define  DID_SS_TA_GROUP_REQ                          3242)
(define  DID_SS_TA_INITIALIZE                         3243)
(define  DID_SS_TA_SHAPE_INFO                         3244)
(define  DID_SS_TA_SHAPE_REQ                          3245)
(define  DID_SS_TVD_SELECT_TV_VIDEO                   1730)
(define  DID_SS_TVP_AUDIO_FILE_DELETE_CMD             6125)
(define  DID_SS_TVP_AUDIO_RNR_CMD                     6126)
(define  DID_SS_TVP_FILE_DELETE_CMD                   1729)
(define  DID_SS_TVP_PLAY_SPEED_CMD                    5928)
(define  DID_SS_TVP_RNR_CMD                           1726)
(define  DID_SS_TVP_RNR_STATUS                        6186)
(define  DID_SS_TVR_FILE_LIST_REQ                     1728)
(define  DID_SS_TVR_STATUS_REQ                        1727)
(define  DID_SS_TV_CONNECT_STATUS_CMD                 1731)
(define  DID_SS_TV_CONNECT_STATUS_REQ                 5529)
(define  DID_SS_TV_SELECT_VIDEO                       2210)
(define  DID_SS_VIDEOFILE_DATA_LIST_INFO              5444)
(define  DID_SS_VIDEO_DISTRIBUTE_CMD                  2303)
(define  DID_SS_VIDEO_FILE_DELETE_ACK                 1722)
(define  DID_SS_VIDEO_FILE_DELETE_CMD                 1385)
(define  DID_SS_VIDEO_FILE_LIST_ACK                   1721)
(define  DID_SS_VIDEO_FILE_LIST_CMD                   1384)
(define  DID_SS_VIDEO_PLAY_SPEED_CMD                  5324)
(define  DID_SS_VIDEO_RNR_CMD                         1382)
(define  DID_SS_VIDEO_RNR_CMD_ACK                     1719)
(define  DID_SS_VIDEO_STATUS                          1720)
(define  DID_SS_VIDEO_STATUS_REQ                      1383)
(define  DID_SS_VIDEO_TIME                            2663)
(define  DID_SS_WARN_AREA_INFO                        1378)
(define  DID_SS_WARN_AREA_INFO_ACK                    1735)
(define  DID_SUBSYSTEM_HEARTBEAT                      6086)
(define  DID_TACM_MAX_SENSE_RANGE                     5846)
(define  DID_TACM_RANGE                               5940)
(define  DID_TACTICAL_AREA                            2559)
(define  DID_TASS_TACM_CONSOLE_INFO                   5842)
(define  DID_TASS_TACM_DECOY_PATTERN                  5934)
(define  DID_TASS_TACM_ENERGYSPECTRUM                 5844)
(define  DID_TASS_TACM_FIRED_DECOY_INFO               5835)
(define  DID_TASS_TACM_FIRE_BT_CTRL                   5836)
(define  DID_TASS_TACM_FIRE_MODE_INFO                 5841)
(define  DID_TASS_TACM_FIRE_PATTERN_SET_REQ           5839)
(define  DID_TASS_TACM_LAUNCHER_INFO                  5843)
(define  DID_TASS_TACM_LAUNCHER_INIT_VALUE            5845)
(define  DID_TASS_TACM_PRIMTRK_ADD_INFO               6196)
(define  DID_TASS_TACM_RESET_DCY_REQ                  6120)
(define  DID_TASS_TACM_SURFACE_POINT_TRACK_INFO       6119)
(define  DID_TASS_TACM_TI_ENG_CMD                     5938)
(define  DID_TASS_TACM_TORPEDO_ALERT_LIST             5837)
(define  DID_TASS_TACM_TORPEDO_DISCERN_DISP           5847)
(define  DID_TASS_TACM_WF_DATA                        5840)
(define  DID_TASS_TACM_WF_LIST                        5872)
(define  DID_TDA_SELECT_INFO                          2558)
(define  DID_TDL_ACIM_RESIL                           6207)
(define  DID_TDL_AIRCRAFT_CONTROL_INFO                2462)
(define  DID_TDL_FUEL_AND_TIME                        2637)
(define  DID_TM_ACK_ID_CONFLICT                       3021)
(define  DID_TM_ALERT_ID_CONFLICT                     3020)
(define  DID_TM_BEARING_TRACK_CANCEL                  2490)
(define  DID_TM_BEARING_TRACK_INFO                    2488)
(define  DID_TM_BEARING_TRACK_INFO_RT_SUP             5404)
(define  DID_TM_BEARING_TRACK_INFO_RT_TAC             5405)
(define  DID_TM_CHANGE_TMSINDEX                       1611)
(define  DID_TM_NOTIFY_NEW_DATUM                      2594)
(define  DID_TM_NOTIFY_PT_DELETE                      2542)
(define  DID_TM_NOTIFY_TRAINING_TRACK                 2535)
(define  DID_TM_NSFS_TRACK_INFO                       1606)
(define  DID_TM_NUMBER_OF_TRACK                       1602)
(define  DID_TM_POINT_TRACK_CANCEL                    2487)
(define  DID_TM_POINT_TRACK_INFO                      2486)
(define  DID_TM_POINT_TRACK_INFO_RT_SUP               5406)
(define  DID_TM_POINT_TRACK_INFO_RT_TAC               5403)
(define  DID_TM_RESILIENCE_DATA                       5476)
(define  DID_TM_SELECT_AUTO_ASSOCIATION_STATUS        2513)
(define  DID_TM_SET_AUTO_ASSOCIATION_OPTION           1266)
(define  DID_TM_WEAPON_CAP                            2818)
(define  DID_TM_WEAPON_RESTRICTION_ORDER              1604)
(define  DID_TM_WEAPON_RESTRICTION_SECTOR             1605)
(define  DID_TRN_CSS_TRAIN_JOIN_REQ                   2348)
(define  DID_TRN_CSS_TRAIN_STATUS                     2552)
(define  DID_TRN_ENV_ENVIRONMENT_REQ                  5429)
(define  DID_TRN_FILTER_CMD                           3235)
(define  DID_TRN_LIB_AIRCLA_CONT                      5421)
(define  DID_TRN_LIB_AIRCLA_CONT_REQ                  5430)
(define  DID_TRN_LIB_MIS_CONT                         5422)
(define  DID_TRN_LIB_MIS_CONT_REQ                     5431)
(define  DID_TRN_LIB_SEN_CONT                         5423)
(define  DID_TRN_LIB_SEN_CONT_REQ                     5432)
(define  DID_TRN_LIB_SUBCLA_CONT                      5424)
(define  DID_TRN_LIB_SUBCLA_CONT_REQ                  5433)
(define  DID_TRN_LIB_SURCLA_CONT                      5425)
(define  DID_TRN_LIB_SURCLA_CONT_REQ                  5434)
(define  DID_TRN_PATH_DRAW                            3237)
(define  DID_TRN_SCEXE_ENVIRONMENT                    5426)
(define  DID_TRN_SCEXE_OBJECT_INFO                    5427)
(define  DID_TRN_SCEXE_OP_EVENT                       2578)
(define  DID_TRN_SCEXE_START_STOP_CONT                1646)
(define  DID_TRN_SCEXE_START_STOP_CONT_REQ            5435)
(define  DID_TRN_SCON_MIS_CONT                        2565)
(define  DID_TRN_SCON_MIS_CONT_REQ                    5436)
(define  DID_TRN_SCON_OBJECT_CONT                     2560)
(define  DID_TRN_SCON_OBJECT_CONT_REQ                 5438)
(define  DID_TRN_SCON_OBJ_INFO_EDT                    1644)
(define  DID_TRN_SCON_OBJ_INFO_EDT_REQ                5437)
(define  DID_TRN_SCON_SCN_CONT                        1639)
(define  DID_TRN_SCON_SCN_CONT_REQ                    5439)
(define  DID_TRN_SCON_SCN_REMOTE                      2602)
(define  DID_TRN_SCON_SEN_CONT                        2567)
(define  DID_TRN_SCON_SEN_CONT_REQ                    5440)
(define  DID_TRN_SCON_SNAP_CONT                       1645)
(define  DID_TRN_SCON_SNAP_CONT_REQ                   5441)
(define  DID_TRN_SIMIRST_SECTOR_SURVEIL_ACK           6248)
(define  DID_TRN_SIM_ONOFF                            1456)
(define  DID_TRN_SLTS_STATUS_REQ                      1465)
(define  DID_TRN_SYMBOL_DRAW                          3236)
(define  DID_TRN_TRS_STATUS                           6069)
(define  DID_TRN_TRS_STATUS_REQ                       2136)
(define  DID_TRN_WAYPOINT_DRAW                        3238)
(define  DID_TRN_WPSIM_ACK                            3273)
(define  DID_TRN_WPSIM_REQ                            3274)
(define  DID_TRS_ALERT_CTRL                           5886)
(define  DID_TRS_ALERT_STATUS                         5873)
(define  DID_TRS_EQUIP_CTRL                           5887)
(define  DID_TRS_EQUIP_STATUS                         5874)
(define  DID_TRS_JOYSTICK_DATA                        5888)
(define  DID_TRS_OPERATE_CTRL                         5889)
(define  DID_TRS_OPERATE_STATUS                       5875)
(define  DID_TRS_RADAR_CTRL                           5890)
(define  DID_TRS_RADAR_STATUS                         5876)
(define  DID_TRS_RAW_DATA_ALL_OUTPUT                  5877)
(define  DID_TRS_RAW_DATA_OUTPUT                      5878)
(define  DID_TRS_SECONDARY_TARGET                     5879)
(define  DID_TRS_SECTOR_SEARCH_CTRL                   5891)
(define  DID_TRS_SECTOR_SEARCH_REPORT                 5880)
(define  DID_TRS_STATUS                               5881)
(define  DID_TRS_TRACKING_CTRL                        5892)
(define  DID_TRS_TRACKING_STATUS                      5882)
(define  DID_TRS_TRACK_INFO                           5883)
(define  DID_TRS_TWO_TARGET_INFO                      5884)
(define  DID_TRS_VIDEO_CTRL                           5893)
(define  DID_TRS_VIDEO_STATUS                         5885)
(define  DID_TVP_AUDIOD_STATUS                        6123)
(define  DID_TVP_AUDIOR_STATUS                        6124)
(define  DID_TVP_AUDIO_FILE_DELETE_ACK                6121)
(define  DID_TVP_AUDIO_RNR_CMD_ACK                    6122)
(define  DID_TVP_FILE_DELETE_ACK                      1981)
(define  DID_TVP_RNR_CMD_ACK                          1978)
(define  DID_TVP_TVD_STATUS                           5734)
(define  DID_TVP_TVR_STATUS                           1980)
(define  DID_TVR_FILE_LIST_ACK                        1979)
(define  DID_WC_GUN_AMMUNITION_SELECT_ORDER           6071)
(define  DID_WF_AIR_THREAT_LIST                       1542)
(define  DID_WF_ASW_SENSOR_RANGE_REQ                  2291)
(define  DID_WF_ENGAGED_TRACK_STATUS                  1553)
(define  DID_WF_ENG_CH_LIST                           1547)
(define  DID_WF_ENG_INFO_LIST                         1548)
(define  DID_WF_EVERY_WF_RSC_STATUS                   2506)
(define  DID_WF_FIRE_AUTHORIZE                        1549)
(define  DID_WF_FIRE_AUTHORIZE_REQ                    1441)
(define  DID_WF_NSFS_INFO                             1551)
(define  DID_WF_NSFS_INFO_SET_REQ                     5658)
(define  DID_WF_QR_THREAT_LIST                        2152)
(define  DID_WF_RESET_TRACKING                        2156)
(define  DID_WF_RESIL_COMM_DATA                       5448)
(define  DID_WF_RESIL_GEN_ENG_INFO                    5526)
(define  DID_WF_RESIL_GEN_PAC_INFO                    5524)
(define  DID_WF_RESIL_GEN_RESERVED_EC                 5525)
(define  DID_WF_RESIL_GEN_RSC_TIMER                   5523)
(define  DID_WF_RESIL_RSC_ENGAGEABLE_STATUS           5527)
(define  DID_WF_RSC_ALLOC_DEALLOC_ACK                 2507)
(define  DID_WF_RSC_ALLOC_DEALLOC_REQ                 1554)
(define  DID_WF_SUBSURFACE_THREAT_LIST                2151)
(define  DID_WF_SURFACE_THREAT_LIST                   1543)
(define  DID_WF_THREAT_SELECTION_FILTER_INFO          2150)
(define  DID_WF_THREAT_SELECTION_FILTER_SET_REQ       2149)
(define  DID_WF_TORP_THREAT_LIST                      1546)
(define  DID_WF_TRACKING_INFO_LIST                    2569)
(define  DID_WF_TRACK_MANUAL_SELECTION_INFO           2530)
(define  DID_WF_USER_SET_INFO_REQ                     2137)
(define  DID_WF_WASA_QR_MODE                          1550)
(define  DID_WF_WASA_QR_MODE_SET_REQ                  1442)
(define  DID_WF_WEAPON_CAP_SET_REQ                    2817)
(define  DID_WF_WEAPON_RESTRICTION_ORDER_REQ          1444)
(define  DID_WF_WEAPON_RESTRICTION_SECTOR_SET_REQ     1445)
(define  DID__EMCON_REQ                               2400)
(define  DID__EMCON_STATUS_REQ                        2414)
(define  DID__GFE_BIT_INFO                            3271)
(define  DID__GUN40_CORRECTION_DATA                   2200)
(define  DID__INF_CTRL_ACK                            2118)
(define  DID__RSC_FIRE_AUTHORIZE_REQ                  1802)
(define  DID__SIM_ONOFF_ACK                           1748)
(define  DID__TORPEDO_ALERT_INFO                      2555)
(define  DID__TRACK_NUM_REQ                           2300)
