(define system_types-track_kind_aco_bearing_track 1  ) 
(define system_types-track_kind_aco_fix_refpos 0  ) 
(define system_types-track_kind_air_point_track 2  ) 
(define system_types-track_kind_air_refpos 3  ) 
(define system_types-track_kind_asw_refpos 4  ) 
(define system_types-track_kind_datum_refpos 5  ) 
(define system_types-track_kind_ecm_bearing_track 7  ) 
(define system_types-track_kind_ecm_fix_refpos 6  ) 
(define system_types-track_kind_esm_bearing_track 9  ) 
(define system_types-track_kind_esm_fix_refpos 8  ) 
(define system_types-track_kind_gen_refpos 10  ) 
(define system_types-track_kind_land_point_track 13  ) 
(define system_types-track_kind_none 14  ) 
(define system_types-track_kind_subsurface_point_track 11  ) 
(define system_types-track_kind_surface_point_track 12  ) 

(define system_types-sec_gen_refpos_des_pim 17  ) 

