(testsc-require dbid)
(define dbid 0)
(for-each-index-offset
 1
 (lambda (x)
   (set! dbid x )
   
   )
DB_ID_COMM_TDL_CDO
DB_ID_COMM_MODIFY_TRACK_INFO
DB_ID_COMM_TDL_CONFLICT
DB_ID_COMM_TDL_WEAPON_ENGAGEMENT_SETTING
DB_ID_COMM_TDL_LINK11_COMMAND_ORDER
DB_ID_MD_TDL_POINTER
DB_ID_MD_TM_LINK_SEND_CANCEL
DB_ID_LINK11_AIRCRAFT_MISSION_STATUS_SETTING
DB_ID_LINK11_AIRCRAFT_CONTROL_ORDER_SETTING
DB_ID_TM_POINT_TRACK_INFO
DB_ID_TM_BEARING_TRACK_INFO
DB_ID_TM_NOTIFY_TRAINING_TRACK
DB_ID_TM_POINT_TRACK_CANCEL
DB_ID_TM_BEARING_TRACK_CANCEL
DB_ID_EW_PRIMTRK_ADD_INFO
DB_ID_HMS_PRIMTRK_ADD_INFO
DB_ID_LYNXESM_PRIMTRK_ADD_INFO
-1
 )

