(testsc-require system_types)
(testsc-require l11const)
(testsc-debug "t-27")

;; (case (testsc-get-testnum)
;;   ((9)
;;    (define testsc 1)
;;    (define  te system_types-threat ) 
;;    (mmsg-set
;;     (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
;;     (list  M86BRS  SECOND_FRAME_OFFSET 1)
;;     (list M86BEVSW  SECOND_FRAME_OFFSET 0)
;;     (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14)
;;     (list  M86BBA  SECOND_FRAME_OFFSET 3  )))
;;   )

(case (testsc-get-testnum)
  ((9)
   (define testsc 1)
   (define  te system_types-threat ) 
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 1)
    (list M86BEVSW  SECOND_FRAME_OFFSET 0)
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )))
  ((14)
   (define testsc 1)
   (define  te system_types-threat ) 
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 1)
    (list M86BFM  SECOND_FRAME_OFFSET 1)
    (list M86BEVSW  SECOND_FRAME_OFFSET 0)
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )))
  ((10)
   (define testsc 1)
   (define  te system_types-non_threat ) 
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 1)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )
    (list M86BEVSW  SECOND_FRAME_OFFSET 1 )
    (list M86BFM  SECOND_FRAME_OFFSET 1)
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14 )))
  ((15)
   (define testsc 1)
   (define  te system_types-non_threat ) 
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 1)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )
    (list M86BEVSW  SECOND_FRAME_OFFSET 1 )
    (list M86BFM  SECOND_FRAME_OFFSET 1)
    (list  M86BMODE  SECOND_FRAME_OFFSET 1)
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14 )))

  ((11)
   (define testsc 1)
   (define  te system_types-unknown_threat_evaluation ) 
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 1)
    (list M86BEVSW  SECOND_FRAME_OFFSET 0)
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )))
  ((12)
   (define testsc 1)
   (define  te system_types-pending_threat_evaluation ) 
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 1)
    (list M86BEVSW  SECOND_FRAME_OFFSET 0)
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )))

  ((16)
   (define testsc 1)
   (define  te system_types-threat ) 
   (mmsg-set
    (list M86BTIMESTALE  SECOND_FRAME_OFFSET 10)
    (list  M86BRS  SECOND_FRAME_OFFSET 0)
    (list M86BEVSW  SECOND_FRAME_OFFSET 0)
    (list M86BFREQFREQRANGE  SECOND_FRAME_OFFSET 14)
    (list  M86BBA  SECOND_FRAME_OFFSET 3  )))

  )
