(testsc-require dlplink11types)
(testsc-require system_types)

(case (testsc-get-testnum)
  ((1)
   (define testsc 1 )
   (for-each
    (lambda (x)
      (testsc-track-nset x (list 'transmission_info.track_alert_counter  1))    
      (testsc-track-nset x (list 'transmission_info.info_validation 1))) (num-list 1 5))   
   (testsc-track-nset 1 (list 'transmission_info.track_alert_counter  0))    
   (testsc-track-nset 2 (list 'transmission_info.kind_of_alert FORCETELL))    
   (testsc-track-nset 3 (list 'transmission_info.kind_of_alert STOP_FORCETELL))    
   (testsc-track-nset 4 (list 'transmission_info.kind_of_alert -1))
   (testsc-track-nset 5 (list 'transmission_info.info_validation 0))
  ))
