(case (testsc-get-testnum)
  ((39)
   (define testsc 1 )
   (define id   -1 )
   (define pid  -1 )
   (define sid  -1 )
   )
  ((40)
   (define testsc 1 )
   (define id   1000 )
   (define pid  1000 )
   (define sid  1000 )
   ))
