(testsc-require l11const)
(testsc-require system_types)
(testsc-set-debug 1)
(testsc-debug "t92")
(case (testsc-get-testnum)
  ((54)
   (testsc-track-nset 1 (list 'general.track_kind   system_types-track_kind_gen_refpos                        ))
   (testsc-track-nset 1 (list 'general.primary_gen_designator   system_types-pri_gen_refpos_des_emergency     ))
   (testsc-track-nset 1 (list 'general.secondary_gen_designator   system_types-sec_gen_refpos_des_no_statement))
   )
  ((55)
   (testsc-track-nset 1 (list 'general.track_kind   system_types-track_kind_gen_refpos                        ))
   (testsc-track-nset 1 (list 'general.primary_gen_designator   system_types-pri_gen_refpos_des_formation     ))
   (testsc-track-nset 1 (list 'general.secondary_gen_designator   system_types-sec_gen_refpos_des_formation_centre ))
   )
  ((56)
   (testsc-track-nset 1 (list 'general.track_kind   system_types-track_kind_gen_refpos                        ))
   (testsc-track-nset 1 (list 'general.track_kind    system_types-track_kind_air_point_track ))
   (testsc-track-nset 1 (list 'general.quality_syst    0 )))
  ((57)
   (testsc-track-nset 1 (list 'general.track_kind    system_types-track_kind_subsurface_point_track ))
   (testsc-track-nset 1 (list 'general.quality_syst  0 )))
  ((58)
   (testsc-track-nset 1 (list 'general.track_kind    system_types-track_kind_subsurface_point_track ))
   (testsc-track-nset 1 (list 'general.quality_syst  0 )))
  ((59)
   (testsc-track-nset 1 (list 'general.track_kind   system_types-track_kind_asw_refpos )                       )
   (testsc-track-nset 1 (list 'general.primary_asw_designator   system_types-pri_asw_refpos_des_search  )      )
   (testsc-track-nset 1 (list 'general.secondary_asw_designator   system_types-sec_asw_refpos_des_notack_area )))

  
  )

(testsc-debug "t92 done")

