

(testsc-require system_types)
(case (testsc-get-testnum)
  ((7)
   (define glm system_types-data_exchange_link11_mode)
   (testsc-track-nset 1 (list 'general.network  1) )
   )
  ((16)
   (define glm system_types-data_exchange_link11_mode)
   (testsc-track-nset 1 (list 'general.network  1) )
   (testsc-track-nset 1 (list 'general.track_existence  system_types-aop_track) )
   (testsc-track-nset 1 (list 'training_NTN  1) )
   )
  ((17)
   (define glm system_types-data_exchange_link11_mode)
   (testsc-track-nset 1 (list 'general.network  1) )
   (testsc-track-nset 1 (list 'general.track_existence  -1) )
   (testsc-track-nset 1 (list 'training_NTN  0) )
   )
  ((18)
   (define glm system_types-data_exchange_link11_mode)
   (testsc-track-nset 1 (list 'general.network  0) )
   (testsc-track-nset 1 (list 'general.track_existence  -1) )
   (testsc-track-nset 1 (list 'training_NTN  0) )
   )
  
  ((8)
   (define testsc 1 )
   (define glm system_types-data_exchange_link11_mode)
   (define ipt system_types-data_exchange_link11_mode)
   (define itd 0)
   (testsc-track-nset 1 (list 'general.network  0) )
   (testsc-track-nset 1 (list 'general.track_existence  system_types-real_track) )
   (testsc-track-nset 1 (list 'general.quality_syst  1) )
   (testsc-track-nset 1 (list 'general.network_track_phase  (+ 1  system_types-wiped)) )

   )
  ((9)
   (define testsc 1 )
   (define glm system_types-data_exchange_link11_mode)
   (define ipt system_types-data_exchange_link11_mode)
   (testsc-track-nset 1 (list 'general.network  0) )
   (testsc-track-nset 1 (list 'general.track_existence  -1) )
   (testsc-track-nset 1 (list 'general.quality_syst  1) )
   )

  )
