
;; (testsc-require l11const)
;; (testsc-require system_types)
;; (testsc-require dlplink11types)
(define testsc 1 )
(define mas 3)
(anset  0 )
(tnset 0)
(case (testsc-get-testnum)
  ((2)
   (define testsc 1 )
   (anset  0 '_cdo_check.counter 10)
   (anset  1 '_cdo_check.counter 10)
   )
  ((3)
   (define testsc 1 )
   (define pdtrh 1 )
   (anset  0 '_cdo_check.counter 10)
   (anset  1 '_cdo_check.counter 10)
   )
  )


