
(testsc-require l11const)
(testsc-require system_types)
(testsc-require dlplink11types)

(case (testsc-get-testnum)
  ((11)
   (define testsc  1)
    (define ts -1) 
    (define noc 1) 
    (define nic 1) 
    )

  ((12)
   (define testsc  1)
    (define ts system_types-running) 
    (define noc 0) 
    (define nic 1) 
   )
  ((13)
   (define testsc  1)
    (define ts system_types-running) 
    (define noc 2) 
    (define nic 1) 
    )
  ((14)
   (define testsc  1)
    (define ts system_types-running) 
    (define noc 1) 
    (define tp1 1) 
    (define nic 1) 
    )
  ((15)
   (define testsc  1)
    (define ts system_types-running) 
    (define noc 2) 
    (define tp1 1) 
    (define ntc 2) 
    (define nic 1) 
    )
  ((16)
   (define testsc  1)
    (define ts system_types-running) 
    (define noc 2) 
    ;; (define tp1 1) 
    (define nic 1) 
    (define ntc 2) 
    )
  ((17)
   (define testsc  1)
   (define noc 2) 
   (define tp1 1) 
   (define ntc 2) 
   (define nic 1) 
   (define ts system_types-running) 
   )
  ((18)
   (define testsc  1)
   (define ts system_types-running) 
   (define noc 2) 
   ;;(define tp1 1) 
   (define nic 1) 
   )

  
  )

