(define ulMsgID 0)
(define i_enStatus 0)

(for-each-index-offset
 1
 (lambda (x)
   (set! ulMsgID x ))
 -1
 DB_ID_LINK11_DP_INPUT
 DB_ID_SLTS_STATUS_INFO
 DB_ID_SM_ALERT_RESULT
 DB_ID_SM_ALL_SYS_STATUS_INFO
 DB_ID_SM_SYS_PARA_VAL
 DB_ID_SM_TIME_AND_DATE
 DB_ID_TDL_FUEL_AND_TIME
 DB_ID_TM_BEARING_TRACK_CANCEL
 DB_ID_TM_BEARING_TRACK_INFO
 DB_ID_TM_NOTIFY_TRAINING_TRACK
 DB_ID_TM_POINT_TRACK_CANCEL
 DB_ID_TM_POINT_TRACK_INFO
 DB_ID_COMM_FILE_UPDATE
 DB_ID_COMM_IPN_FILE_UPDATE_CMD
 DB_ID_LINK11_TDL_OPNOTE_INFO
 DB_ID_COMM_TDL_FILTER_SETTING
 DB_ID_FR_UPDATE_NOTIFY
 DB_ID_LINK11_OPNOTE_SETTING
 DB_ID_SM_ALLOC_STATUS_REPORT
 DB_ID_SM_ALL_SYS_STATUS_INFO
 DB_ID_LINK11_DP_INPUT
DB_ID_COMM_ALERT
DB_ID_COMM_ALERT_RESULT_ACK
DB_ID_COMM_MODIFY_TRACK_INFO
DB_ID_COMM_NETWORK_TRACK_CANCEL
DB_ID_COMM_NETWORK_TRACK_INFO
DB_ID_COMM_PRIMITIVE_TRACK_ADD_INFO_REQ
DB_ID_COMM_PRIMITIVE_TRACK_INFO
DB_ID_COMM_SUBSYSTEM_STATUS_INFO
DB_ID_COMM_SW_STATUS
DB_ID_COMM_SYS_PARAMETER_REQ
DB_ID_COMM_TDL_CDO
DB_ID_COMM_TDL_MAX_RX_TRACK_COUNT
DB_ID_COMM_TDL_NTN
DB_ID_COMM_TDL_POINTER
DB_ID_COMM_TDL_TQ_UPDATE
DB_ID_COMM_TDL_WEAPON_ENGAGEMENT
DB_ID_LINK11_ADMISSION
DB_ID_LINK11_AIRCRAFT_CONTROL
DB_ID_LINK11_AIRCRAFT_MISSION_STATUS
DB_ID_LINK11_COMMAND_LINE
DB_ID_LINK11_COMMAND_ORDER
DB_ID_LINK11_CONFLICT
DB_ID_LINK11_DTS_CONTROL_DATA
DB_ID_LINK11_DTS_NDDSINTF
DB_ID_LINK11_NETWORK_TRACK_ADD_INFO
DB_ID_LINK11_TEST_RESULT
DB_ID_COMM_PRIMITIVE_TRACK_CANCEL
DB_ID_COMM_TDL_CONFLICT
DB_ID_COMM_TDL_FILTER_INFO
DB_ID_COMM_TDL_LINK11_COMMAND_ORDER
DB_ID_COMM_TDL_MAX_RX_TRACK_COUNT_SETTING
DB_ID_COMM_TDL_WEAPON_ENGAGEMENT_SETTING
DB_ID_EW_PRIMTRK_ADD_INFO
DB_ID_HMS_PRIMTRK_ADD_INFO
DB_ID_ISDL_NETWORK_TRACK_ADD_INFO
DB_ID_KSAAM_STATUS
DB_ID_KSSM_EQUIPMENT_STATUS
DB_ID_KVLA_STATUS_INFO
DB_ID_LINK11_ADMISSION_SETTING
DB_ID_LINK11_AIRCRAFT_CONTROL_ORDER_SETTING
DB_ID_LINK11_AIRCRAFT_MISSION_STATUS_SETTING
DB_ID_LINK11_DTS_CONTROL_DATA_SETTING
DB_ID_LINK11_IP_INPUT
DB_ID_LINK11_LOOPTEST_SETTING
DB_ID_LYNXESM_PRIMTRK_ADD_INFO
DB_ID_MD_TDL_POINTER
DB_ID_MD_TM_LINK_SEND_CANCEL
DB_ID_OSD_INFO
)

(if (=  (testsc-get-testnum) 5)
    (set! i_enStatus RET_DELETED))

(if (>  (testsc-get-testnum) 70)
    (set! i_enStatus RET_DELETED))
