(testsc-require l11const)
(testsc-require system_types)
(testsc-require dlplink11types)
(testsc-require icmsdefine)

(case (testsc-get-testnum)
  ( (17)
    (define testsc 1 )
    (define iff1 1 )
    (define iff2 2 )
    (define iff3 3 )
    (define iff4usecount 1 )
    (define iff4-1 -1)
    (define iff4-2 4)
    ;; (define mcbf TDL_MODECODE1_BY_OPERATOR)
    (tnset 1 'general.iff_data.iff_mode1 1 )
    (tnset 1 'link11.iff_mode1_local 0 )
    (tnset 1 'link11.iff_mode2_conflict_state 0)
    (tnset 1 'link11.iff_mode4_conflict_state 1)
    )
  ((18)
   (define testsc 1 )
   (define iff1 1 )
   (define iff2 2 )
   (define iff3 3 )
   (define iff4usecount 1 )
   (define iff4-1 4)
   (define iff4-2 4)
   (define mcbf (+ TDL_MODECODE2_BY_OPERATOR  TDL_MODECODE3_BY_OPERATOR ))
   (tnset 1 'general.iff_data.iff_mode1 1 )
   (tmset 1 'link11.iff_mode1_local 1)
   (tmset 1 'own_or_lro 0)
   (tnset 1 'general.iff_data.iff_mode1_changed 0 )
   (tnset 1 'link11.iff_mode2_conflict_state 1)
   (tnset 1 'cmsdata.iff_mode2 2)
   (tnset 1 'general.iff_data.iff_mode2 2)
   (tnset 1 'cmsdata.iff_mode3 3)
   (tnset 1 'general.iff_data.iff_mode3 3)
   (tnset 1 'link11.iff_mode4_conflict_state 0)
   (tnset 1 'general.iff_data.iff_mode4 4     )
   (tnset 1 'cmsdata.iff_mode4          3     )
   )
  ((19)
   (define testsc 1 )
   (define iff1 0 )
   (define iff2 2 )
   (define iff3 3 )
   (tnset 1 general.iff_data.iff_mode1 1 )
   (tmset 1 'link11.iff_mode1_local 1             )
   (tmset 1 'own_or_lro 1                         )
   (tnset 1 'general.iff_data.iff_mode1_changed 1 )
   (tnset 1 'link11.iff_mode2_conflict_state 1    )
   (tnset 1 'cmsdata.iff_mode2 3                  )
   (tnset 1 'general.iff_data.iff_mode2 2         )
   (tnset 1 'cmsdata.iff_mode3 4                  )
   (tnset 1 'general.iff_data.iff_mode3 3         )
   (tnset 1 'general.iff_data.iff_mode4 4         )
   (tnset 1 'cmsdata.iff_mode4  4                 ))


  
  ((22)
   (define testsc 1 )
   (define iff1 1 )
   (define iff2 2 )
   (define iff3 3 )
   (define iff4 -1 )
   (define gmr system_types-mode4_reject)
   (tnset 1 general.iff_data.iff_mode1 1 )
   (tmset 1 'link11.iff_mode1_local 1             )
   (tmset 1 'own_or_lro 1                         )
   (tnset 1 'general.iff_data.iff_mode1_changed 1 )
   (tnset 1 'link11.iff_mode2_conflict_state 1    )
   (tnset 1 'cmsdata.iff_mode2 3                  )
   (tnset 1 'general.iff_data.iff_mode2 2         )
   (tnset 1 'cmsdata.iff_mode3 4                  )
   (tnset 1 'general.iff_data.iff_mode3 3         )
   (tnset 1 'general.iff_data.iff_mode4 4         )
   (tnset 1 'cmsdata.iff_mode4  -1                 ))
  ((23)
   (define testsc 1 )
   (define iff4 1 )
   (tnset 1 'cmsdata.iff_mode4  1                 ))
  ((24)
   (define testsc 1 )
   (define iff4 1 )
   (define gmr system_types-mode4_reject)
   (tnset 1 'cmsdata.iff_mode4  1                 ))

  )
