(testsc-require l11const)
(testsc-require system_types)
(testsc-require dlplink11types)


(case (testsc-get-testnum)
  ((10)
   (define testsc 1)
   (mmsg-set (list M4ADRTYPE 0 2))
   )
  ((11)
   (define testsc 1)
   (mmsg-set (list M4ADRTYPE 0 3)
             (list  M84AASWPTTYPE  SECOND_FRAME_OFFSET ASW_POINT_ACOUSTIC_FIX ))
   )
  ((12)
   (define testsc 1)
   (mmsg-set (list M4ADRTYPE 0 3)
             (list  M84AASWPTTYPE  SECOND_FRAME_OFFSET -1 ))
   )
  ((13)
   (define testsc 1)
   (mmsg-set (list M4ADRTYPE 0 -1)
             (list  M84AASWPTTYPE  SECOND_FRAME_OFFSET -1 ))
   )
  
  )
